### ISSUE TITLE
Aptly does not generate Contents File

### ISSUE THREAD

**Issue by 65HQqp5QTq8QwA3f** [smira/aptly#142]
Aptly does not generate Contents File

For main component of wheezy distribution for amd64 architecture, this file would normally be located at
>/dists/wheezy/main/Contents-amd64.gz

Steps to reproduce:
1. Use aptly to create a local repository, add packages to the local repository, and publish the repository.
2. Configure /etc/apt/sources.list to include published repository.
3. Run a command which relies on the the contents file, for example, update-command-not-found.

Ignoring source without Contents File:
>http://example.com/dists/wheezy/main/Contents-amd64.gz

The same repository works perfectly for installing and upgrading packages, just not with any command which relies on the contents file.

**Comment by gittex** [comment]
:+1: 

We also rely on this Contents files for generating dependencies during automated builds of deb packages.

This feature would be very appreciated.

**Comment by activars** [comment]
+1

**Comment by Benoit-Sittler** [comment]
Contents file are also needed by the apt-file tool https://wiki.ubuntu.com/AptFile , it would be really nice to be able to use this tool with an aptly repository.

**Comment by smira** [comment]
Done in `master`, available as nightly build `aptly_0.9.6~dev+78+g933b019`

**Comment by smira** [comment]
Better support with no external `liblzma` dependency in nightly build `aptly_0.9.6~dev+87+gba08ffe`.
