### ISSUE TITLE
Aptly publish drop won't drop corrupted published repository, no force option

### ISSUE THREAD

**Issue by Hobbsee** [smira/aptly#153]
In a futile attempt to clean things up, I ran rm on a number of debs [1], and removed them from their respective aptly repos, and ran aptly db cleanup.  This has gotten aptly repo back to the correct number of packages, and packages can be added to these repos directly.

I then tried to publish some new packages, which failed with:
```
$ aptly -config=aptly.conf -gpg-key="803709B6" -force-overwrite=true publish update precise v1
WARNING: force overwrite mode enabled, aptly might corrupt other published repositories sharing the same package pool.

Loading packages...
Generating metadata files and linking package files...
Finalizing metadata files...
Signing file 'Release' with gpg, please enter your passphrase when prompted:
Clearsigning file 'Release' with gpg, please enter your passphrase when prompted:
Cleaning up prefix "v1" components experimental, main...
ERROR: unable to update: unable to load package with key Pamd64 flapjack 1.0.0~+20140911074259-v1.0.0-trusty-1 2b7caa2968a1f693: key not found
```

The publish update hasn't taken notice that a number of packages have been removed from the filesystem.  That's understandable enough, so I tried to drop the publish (to later go and create them again with the correct packages).  This failed with:

```
$ for distro in precise trusty; do aptly -config=aptly.conf publish drop ${distro} 0.9; done
Removing /home/ubuntu/omnibus-flapjack/aptly/public/0.9/dists/precise...
Cleaning up prefix "0.9" components experimental, main...
ERROR: unable to remove: unable to load package with key Pamd64 flapjack 0.9.5~+20141008003938-v0.9.5-trusty-1 11155af4595696b6: key not found
Removing /home/ubuntu/omnibus-flapjack/aptly/public/0.9/dists/trusty...
Cleaning up prefix "0.9" components experimental, main...
ERROR: unable to remove: unable to load package with key Pamd64 flapjack 0.9.3~+20140901123122-v0.9.3-precise-1 a5c00d00975f3f61: key not found
```

There appears to be no way to force-remove publishes when they're corrupt.  --force does not work here.  In my view, beyond checking for existence, drop shouldn't try to verify the state of the publish before dropping it.

[1] I subsequently learned that this is the wrong way to do things, so won't try this again.

**Comment by smira** [comment]
Fixed in `master`, available as nightly build `aptly_0.9.5~dev+12+gf8bca46`

**Comment by smira** [comment]
@antonio you might be interested in that fix as well.

How to use: if `aptly publish drop` fails with error message on 'Cleaning up prefix ...` phase, you can try running it with `-force-drop` flag, it would ignore errors and continue dropping published repository "no matter what".

**Comment by antonio** [comment]
> @antonio you might be interested in that fix as well.
> 
> How to use: if aptly publish drop fails with error message on 'Cleaning up prefix ...phase, you can try running it with-force-drop` flag, it would ignore errors and continue dropping published repository "no matter what".

@smira this did the trick! I was able to drop the published repositories, recreate them and get rid of the errors. Thanks a lot.
