### ISSUE TITLE
Repository consisting of current installed packages

### ISSUE THREAD

**Issue by StevePotter** [smira/aptly#156]
Hello there!  I'm building a machine with an embedded PC inside.  My base image has only the packages that I need.  I don't want people to be able to install packages that haven't been authorized.  So, I'd like to create a repository that only has the packages that are currently installed on the system.  Then I'll publish that and have it as the only repository on production units.  Is this possible with aptly?

**Comment by smira** [comment]
Closing on inactivity, please feel free to re-open
