### ISSUE TITLE
accept globbing for aptly names

### ISSUE THREAD

**Issue by rtrsparq** [smira/aptly#158]
It would be really finger friendly if the <name> passed to many aptly commands could be globs i.e. glob(3)

For example I might have a naming convention for my snapshots { snap-main, snap-updates } it would be nice if I could just drop them all with a single command command `aptly drop snapshot snap\*`

The <name> argument would just be glob matched against the name list aptly maintains in its database.

**Comment by fewaffles** [comment]
Sounds like a candidate for a shell completion script.

**Comment by smira** [comment]
Shell completion is available for aptly: https://github.com/smira/aptly/blob/master/bash_completion.d/aptly
