### ISSUE TITLE
Can't publish to S3

### ISSUE THREAD

**Issue by chook** [smira/aptly#161]
I follow http://www.aptly.info/tutorial/repo/ (created the user, exported the AWS_* env vars)

When publish I get an error:

ERROR: unable to publish: unable to process packages: error getting information about pool/main/t/takipi/takipi_3.8.2_amd64.deb from S3: us-east-1:deb.takipi.com/: 403 Forbidden

http://deb.takipi.com/ is already set up as a static hosted site

**Comment by chook** [comment]
Also tried with nightly: aptly_0.9~dev+88+gf228ad8_amd64.deb.
Same error.

Some more info that might help:

> aptly repo show -with-packages takipi-release
Name: takipi-release
Comment:
Default Distribution: squeeze
Default Component: main
Number of packages: 2
Packages:
  takipi_3.7.4_amd64
  takipi_3.8.2_amd64

**Comment by smira** [comment]
@chook there should be something wrong with the AWS authentication tokens (or policy attached to your  bucket). aptly was trying to get information about file in S3 bucket and failed. 

There could be many reasons for that, but please make sure you have correct policy attached (AWS Policy Simulator might help) and that you have correct AWS keys in environment. You might get this error if you put key ID and access key in wrong variables (swapped them).

**Comment by chook** [comment]
Swap it is! Thanks

More than 5 years of AWS usage, ALWAYS had the key_id ABOVE the secret key :octopus:
