### ISSUE TITLE
Option --passphrase-file broken

### ISSUE THREAD

**Issue by oCCtet** [smira/aptly#162]
Password is queried even if -passphrase-file option is used with `aptly publish ...`. This is because GnuPG seems to ignore the --passphrase-file option unless --no-use-agent is also given.

aptly 0.8
Ubuntu 14.04

**Comment by oCCtet** [comment]
More details... Ubuntu by default enables GPG agent via `use-agent` option in  ~/.gnupg/gpg.conf. Thus a workaround is to comment out said option as a per-user basis (viable only if aptly is used with a dedicated userid).

IMHO aptly should explicitly pass --no-use-agent with --passphrase-file. Rationale for this is that the user has explicitly told to use the passphrase from the given file, and GPG should honor that.

**Comment by smira** [comment]
I have test for that option, but since it doesn't have user-agent in gpg.conf, it passes okay. I'll add that, thanks!

**Comment by smira** [comment]
Fixed in `master`.
