### ISSUE TITLE
aptly graph to support more output options

### ISSUE THREAD

**Issue by oCCtet** [smira/aptly#163]
It would be nice if `aptly graph` would support output options, e.g. `-type=svg` and `-stdout=false` -- so that (as an example) a SVG-format graph could be generated to stdout.

Use case: repo server has a CGI program that generates an up-to-date graph (using the above options) as a response to an HTTP request.

EDIT: Considering [discussion], the ability to dump the graph to stdout is probably not needed. Still, the option to generate SVG would be welcome (scalable vector graphic instead of a bitmap is so much nicer when the amount of mirros/repos/snapshots is very high).

  [discussion]: https://groups.google.com/d/msg/aptly-discuss/NIi1Q6TS29o/E_mraqjoCQ8J

**Comment by smira** [comment]
Adding here, so that it is not missed: deb package should recommend `graphviz` package.

**Comment by smira** [comment]
Done in `master`.
