### ISSUE TITLE
Feature: Added OpenStack Swift backend

### ISSUE THREAD

**Issue by sbadia** [smira/aptly#164]
Hi,
I planed to work on the OpenStack Swift support in Aptly, using this [go swift](https://github.com/ncw/swift.git) bindings and following your rought plan of [gcs backend](https://github.com/smira/aptly/issues/136#issuecomment-61622186)

* [x] create wrapper around Swift implementing aptly.PublishedStorage interface
* [x] create configuration for SwiftPublishRoot in https://github.com/smira/aptly/blob/master/utils/config.go
* [x] create swift.PublishedStorage based on config and prefix in AptlyContext.GetPublishedStorage: https://github.com/smira/aptly/blob/master/context/context.go#L247
* [x] that should be all on implementation side, we need system test to verify correct operations, like one for S3: https://github.com/smira/aptly/blob/master/system/t06_publish/s3.py

Code in progress :smile:
Let me know, if it's OK for you.

**Comment by smira** [comment]
@sbadia that should be fantastic!

**Comment by smira** [comment]
Already merged.
