### ISSUE TITLE
bash completion!

### ISSUE THREAD

**Issue by lambdafu** [smira/aptly#171]
Of course :) would make the command line a lot more comfortable, with automatic command/option completion and also completion on mirror/snapshot/repo-names.

By the way, I was a bit surprised to see long options introduced with a single-dash. Interesting touch.

**Comment by smira** [comment]
Long options with single dash is something that comes from Go standard library.

As for bash completion, it is available already in Debian package, or you can use this repo: https://github.com/aptly-dev/aptly-bash-completion

**Comment by lambdafu** [comment]
Awesome! Just for reference, here are the steps to get this working in a vanilla ubuntu docker image:

```
RUN wget https://github.com/aptly-dev/aptly-bash-completion/raw/master/aptly -O /etc/bash_completion.d/aptly
RUN apt-get update && apt-get install -y bash-completion
RUN echo ". /etc/bash_completion" >> /root/.bashrc
```

Thanks a lot for your work, I appreciate it!
