### ISSUE TITLE
Packages files not being sorted triggers a bug with pxe/netinstall

### ISSUE THREAD

**Issue by srvg** [smira/aptly#172]
We are setting up aptly to have a managed repository for a set of machines. These repo's are also used as a mirror for installation using a preseeded netboot, using 0.8 with udeb support.

Now we are stumbling on this bug during the preseeded debian-installer phase:

    https://bugs.launchpad.net/ubuntu/+source/util-linux/+bug/1242285

We tested the same netinstall using the upstream ubuntu mirrors directly, and that works sithout a problem, which made me wonder what aptly does differently here.

One of the last comments notes a workaround to that bug, which is sorting the Packages file (alphabetically) with apt-sortpkg.

Checking on the Packages file from out aptly repo, and the upstream base repo at least confirms the aptly Pakcages list is not sorted alphabetically:

    Looking at the index file from our (aptly) mirror:
     
    $ grep -e Package:\ util-linux -e Package:\ insserv Packages
    Package: util-linux
    Package: util-linux-locales
    Package: insserv
     
    From upstream archive.ubuntu.com/ubuntu/dists/trusty/main/binary-amd64/Packages.gz
     
    $ zgrep -e Package:\ util-linux -e Package:\ insserv Packages.gz
    Package: insserv
    Package: util-linux
    Package: util-linux-locales

That bug effectively complains about 'insserv' not being available when installing util-linux.

I don't know if the Packages file is supposed to be sorted, and could'nt find any reference to that, but I suspect that might solve our problem at least.

We managed to apt-sortkpkgs the Packages file, and update hashes and signatures manually, and I can now confirm the Packages file being sorted solves this problem.

Reference list discussion: https://groups.google.com/d/msg/aptly-discuss/FwBaquDXvGk/zv3q-uab6-YJ

**Comment by smira** [comment]
The issue could be not only package order, but also field order. 

So canonical order is defined here:

http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/vivid/apt/vivid/view/head:/apt-pkg/tagfile.cc#L504

**Comment by smira** [comment]
@srvg,  done in `master`, please try latest nightly build `aptly_0.9~dev+123+g0665f22`. Thanks a lot!

**Comment by srvg** [comment]
Problem solved with this, thank you very much!
