### ISSUE TITLE
Allow using soft links for publishing

### ISSUE THREAD

**Issue by qwach** [smira/aptly#173]
Aptly currently uses hard links to publish files from local repositories. Unfortunately, hard links aren't always possible - for example, OpenAFS doesn't allow hard links between files in different directories. Please add an option to use soft links instead.

**Comment by qwach** [comment]
This is mostly #120. Just fall back to soft links if hard links don't work, then to plain copying if soft links don't either?

**Comment by smira** [comment]
Probably it should be configuration option.

**Comment by d9pouces** [comment]
Is this enhancement still planned for a future version?

**Comment by dpedu2** [comment]
+1
