### ISSUE TITLE
Possible to seperate http library into separate repository?

### ISSUE THREAD

**Issue by fire** [smira/aptly#177]
Is possible to separate the http library. I'm using it in my downloader and it would be neater to have it as a different project.

I want to change it so it supports ftp logins.

**Comment by smira** [comment]
@fire I believe current http downloaded is too much intermixed with other stuff in aptly. ftp part itself is available as separate library: https://github.com/smira/go-ftp-protocol

**Comment by smira** [comment]
And ftp logins should go to https://github.com/smira/go-ftp-protocol

I can make downloader separate library, but I'm not sure when I would have time to do that.

**Comment by fire** [comment]
My plans for my download have switched to https and tar.xz (currently on tar.gz). It would be helpful if you could make the downloader a separate library.

**Comment by smira** [comment]
No progress so far
