### ISSUE TITLE
Security concerns about http://www.aptly.info/download/

### ISSUE THREAD

**Issue by hartwork** [smira/aptly#178]
Hi!
Thanks for making aptly and releasing it as software libre!

There are a few things that I stumbled upon on http://www.aptly.info/download/ that I would like to point out and ask for improvement about:

(1) The user is asked to run
```
$ gpg --keyserver keys.gnupg.net --recv-keys 2A194991
$ gpg -a --export 2A194991 | sudo apt-key add -
```
to set up GPG verification. My concerns are that:
* short key IDs are used rather than long ones or the whole fingerprint
* no waterproof against MITM between user and keys.gnupg.net (you could offer a pubkey download through SSL yourself)
* the [whole page](http://www.aptly.info/download/) should be served through (valid) SSL and SSL only (https://www.aptly.info/download/ is broken)

(2) Links to Bintray lack SSL:
```
--- http://dl.bintray.com/smira/aptly/0.8/
+++ https://dl.bintray.com/smira/aptly/0.8/

--- http://dl.bintray.com/smira/aptly/0.8/debian-squeeze-x64/aptly
+++ http://dl.bintray.com/smira/aptly/0.8/debian-squeeze-x64/aptly
```
and so on.

Best, Sebastian

**Comment by smira** [comment]
@hartwork thanks for pointing this out. It's something I should take care about.

**Comment by smira** [comment]
@hartwork I've fixed (2) and for (1) used long key ID for my own key. I'll implement https:// for aptly.info as well, but it would take some time...

**Comment by smira** [comment]
https://www.aptly.info/ is up now, there are some small caching issues still.

**Comment by hartwork** [comment]
That was fast. Very nice!

**Comment by smira** [comment]
Pubkey download via https:// done, would be published with next release.

**Comment by hartwork** [comment]
Thanks!
