### ISSUE TITLE
Aptly (itself) should advertise pubkey downloads through htttps://, not http://

### ISSUE THREAD

**Issue by hartwork** [smira/aptly#179]
Similar to #178, aptly itself is advertising for pbkey downloads without SSL:

> Sometimes keys are stored in repository root in file named Release.key, to import such key:
>
> wget -O - http://some.repo/repository/Release.key | gpg --no-default-keyring --keyring trustedkeys.gpg --import

Please turn that to say `https://`, instead. Thanks!

**Comment by smira** [comment]
I'm not sure if many mirrors support https at all... But this change looks good to me.

**Comment by smira** [comment]
Thank, fixed!

**Comment by hartwork** [comment]
Excellent!
