### ISSUE TITLE
gpg command recommended by aptly missing "--no-default-keyring"?

### ISSUE THREAD

**Issue by hartwork** [smira/aptly#182]
aplty recommended running
```
gpg --keyring /usr/share/keyrings/debian-archive-keyring.gpg --export \
    | gpg --no-default-keyring --keyring trustedkeys.gpg --import
```
(from code at https://github.com/smira/aptly/blob/master/utils/gpg.go#L160)
to me, which pulls the _default keyring_ into `trustedkeys.gpg` as well.
For a fix, the left hand side seems to need `--no-default-keyring`, too.

**Comment by smira** [comment]
Thanks, fixed!
