### ISSUE TITLE
HTTP/1.1 502 Proxy Error

### ISSUE THREAD

**Issue by msura** [smira/aptly#189]
I've discovered some problems related to proxy handling in latest nightly. Aplty 0.8 is working fine.
Please check attached symptoms and let me know, If you need some additional info.

root@ute-image:/etc/apt# uname -a
Linux ute-image 2.6.32-5-amd64 #1 SMP Tue May 13 16:34:35 UTC 2014 x86_64 GNU/Linux

root@ute-image:/etc/apt# cat /etc/debian_version
6.0.10

root@ute-image:/etc/apt# cat /etc/apt/sources.list 
deb http://repo.aptly.info/ squeeze main

root@ute-image:~# dpkg -l | grep aptly
ii  aptly                                0.8                            Debian repository management tool

root@ute-image:/etc/apt# env | grep -i proxy
http_proxy=http://xxx.xxx.xxx.xxx:8080

root@ute-image:~# aptly mirror list
Config file not found, creating default config at /root/.aptly.conf

No mirrors found, create one with `aptly mirror create ...`.

root@ute-image:~# wget http://opensource.wandisco.com/wandisco-debian.gpg -O - | apt-key add -

root@ute-image:~# aptly mirror create -architectures=amd64 squeeze-wandisco-svn17 http://opensource.wandisco.com/debian/ squeeze svn17

root@ute-image:~# aptly mirror update squeeze-wandisco-svn17
...
Mirror `squeeze-wandisco-svn17` has been successfully updated.

==================================================

root@ute-image:~# dpkg -P aptly
(Reading database ... 85738 files and directories currently installed.)
Removing aptly ...
Processing triggers for man-db ...

root@ute-image:~# rm -rf /root/.aptly*

root@ute-image:~# cat /etc/apt/sources.list
deb http://repo.aptly.info/ nightly main

root@ute-image:~# env | grep -i proxy
http_proxy=http://xxx.xxx.xxx.xxx:8080

root@ute-image:~# apt-get update
root@ute-image:~# apt-get install aptly

root@ute-image:~# dpkg -l | grep aptly
ii  aptly                                0.9~dev+134+g403c727           Debian repository management tool

root@ute-image:~# aptly mirror list
Config file not found, creating default config at /root/.aptly.conf

No mirrors found, create one with `aptly mirror create ...`.

root@ute-image:~# aptly mirror create -architectures=amd64 squeeze-wandisco-svn17 http://opensource.wandisco.com/debian/ squeeze svn17
Downloading http://opensource.wandisco.com/debian/dists/squeeze/InRelease...
Downloading http://opensource.wandisco.com/debian/dists/squeeze/Release...
ERROR: unable to fetch mirror: HTTP code 502 while fetching http://opensource.wandisco.com/debian/dists/squeeze/Release

Proxy response (from tcpdump):
HTTP/1.1 502 Proxy Error ( The Uniform Resource Locator (URL) does not use a recognized protocol. Either the protocol is not supported or the request was not typed correctly. Confirm that a valid protocol is in use (for example, HTTP for a Web request).  )^M
Via: 1.1 FIESPRX004^M
Connection: close^M
Proxy-Connection: close^M
Pragma: no-cache^M
Cache-Control: no-cache^M
Content-Type: text/html^M
Content-Length: 4223  ^M

**Comment by smira** [comment]
The problem most probably is workaround for S3 552b11e2 (#130).

Package URLs in this repo contain `+` (e.g. http://opensource.wandisco.com/debian/dists/squeeze/svn17/binary-amd64/libsvn-dev_1.7.19-1+WANdisco_amd64.deb)

**Comment by smira** [comment]
Even though it could be not connected with `+` in URLs. I'll dig into that further.

Thanks for reporting that!

**Comment by smira** [comment]
@msura what kind of http proxy software do you use?

**Comment by smira** [comment]
Fixed in `master`. @msura could you please try latest nightly build `aptly_0.9~dev+135+g1b0eb9d`?

**Comment by msura** [comment]
root@ute-image:/etc/apt# dpkg -l | grep aptly
ii  aptly                                0.9~dev+135+g1b0eb9d           Debian repository management tool

root@ute-image:/etc/apt# aptly mirror create -architectures=amd64 squeeze-wandisco-svn17 http://opensource.wandisco.com/debian/ squeeze svn17
root@ute-image:/etc/apt# aptly mirror update squeeze-wandisco-svn17
...
Mirror `squeeze-wandisco-svn17` has been successfully updated.

Seems to be ok. Thanks for the fix!
