### ISSUE TITLE
Adding a package from published repo to new repo truncates the package

### ISSUE THREAD

**Issue by hcgrove** [smira/aptly#190]
This surprised me quite a lot. I had a package in one repository and wanted it in one more. I hadn't build it myself, so I only had access to the published package. I then debugged the problem on our test server, and got it down to:

root@aptly-test:/var/lib/aptly# aptly version
aptly version: 0.8
root@aptly-test:/var/lib/aptly# aptly repo show --with-packages systems-production-wheezy
Name: systems-production-wheezy
Comment:
Default Distribution: wheezy
Default Component: main
Number of packages: 1
Packages:
  one.com-authorized-keys_43_all
root@aptly-test:/var/lib/aptly# ls -la public/systems-production/pool/main/o/one.com-authorized-keys/
total 20
drwxr-xr-x 2 root root  2048 Feb  4 15:00 .
drwxr-xr-x 5 root root  2048 Feb  4 13:56 ..
-rw-r--r-- 2 root root 12068 Feb  4 15:00 one.com-authorized-keys_43_all.deb
root@aptly-test:/var/lib/aptly# aptly repo show --with-packages systems-test-wheezy
Name: systems-test-wheezy
Comment:
Default Distribution: wheezy
Default Component: main
Number of packages: 0
Packages:
root@aptly-test:/var/lib/aptly# aptly repo add systems-test-wheezy public/systems-production/pool/main/o/one.com-authorized-keys/one.com-authorized-keys_43_all.deb
Loading packages...
[+] one.com-authorized-keys_43_all added
root@aptly-test:/var/lib/aptly# ls -la public/systems-production/pool/main/o/one.com-authorized-keys/
total 8
drwxr-xr-x 2 root root 2048 Feb  4 15:00 .
drwxr-xr-x 5 root root 2048 Feb  4 13:56 ..
-rw-r--r-- 2 root root    0 Feb  4 15:04 one.com-authorized-keys_43_all.deb

**Comment by smira** [comment]
This is a bug, it has been fixed in #127, please try nightly build, it contains this fix.
