### ISSUE TITLE
Aptly should read control field names case-insensitively when adding packages to repo

### ISSUE THREAD

**Issue by antaflos** [smira/aptly#193]
Experimenting with Aptly I noticed that adding some of the packages our developers build in-house doesn't work quite as it should. When running `aptly repo add myrepo somedeb_1.0.0-*_all.deb` I would get the following output:

```
$ aptly repo add myrepo somedeb_1.0.0-*_all.deb
Loading packages...
[+] _1.0.0-1_all added
[+] _1.0.0-2_all added
[+] _1.0.0-3_all added
[+] _1.0.0-4_all added
```

Apparently Aptly doesn't recognise the package names. Looking at the package's `control` file it see this:
```
$ dpkg --info somedeb_1.0.0-1_all.deb
 new debian package, version 2.0.
 size 28236694 bytes: control archive= 4592 bytes.
     201 bytes,     7 lines      control              
   11991 bytes,   127 lines      md5sums              
     346 bytes,    12 lines   *  postinst             #!/bin/bash
 package: somedeb
 Version: 1.0.0-1
 Section: java
 priority: optional
 Architecture: all
 Maintainer: Our Devs <devs@example.com>
 Description: Some Debian package
```

 The problem seems to be that the field containing the package name isn't read by Aptly because it is `package` and not `Package` in the control file (note the wrong case). Same goes for the priority field (`priority` vs `Priority`).

The [Debian policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html) says this about case-sensitivity of field names:

> Field names are not case-sensitive, but it is usual to capitalize the field names using mixed case as shown below. Field values are case-sensitive unless the description of the field says otherwise.

So obviously we should fix our package creation scripts to adhere to the convention of capitalising field names.

But I also think Aptly should read field names case-insensitively, to avoid such problems.

Apart from that I like Aptly very much so far, thanks for creating it! It is definitely more featureful and performant than Freight (which we currently use and which is also great).

**Comment by smira** [comment]
Thanks for reporting that!

**Comment by smira** [comment]
Fixed in `master`, aptly will now complain if package/version/arch is missing. Also field names are case-insensitive now.
