### ISSUE TITLE
Published repo should not list empty `Source:` fields

### ISSUE THREAD

**Issue by kumy** [smira/aptly#195]
Hi,

When playing around with *aptly*, I've found that *reprepro* won't make a mirror from `aptly publish` results.

Error from *reprepro* is:

```
[...]
Calculating packages to get...
  processing updates for 'trusty|multiverse|amd64'
  marking everything to be deleted
  reading './lists/Ubuntu_trusty_multiverse_amd64_Packages'
Error: Field 'Source' is empty!
Stop reading further chunks from './lists/Ubuntu_trusty_multiverse_amd64_Packages' due to previous errors.
[...]
```

Looking in the concerned *Packages* files, I confirmed that certain `Source: ` fileds are empty.
Then I compared the same mirror done with *reprepro*, and _empty_ `Source: ` fields are simply absent.

May you mimic this behaviour ?
Bests

---
aptly 0.9~dev+180+g7925af9

**Comment by smira** [comment]
Thanks for discovering this bug!

Fixed in `master`, nightly build `aptly_0.9~dev+181+g1f73a34` contains the fix.
