### ISSUE TITLE
reverse word ouput from aptly publish list -raw

### ISSUE THREAD

**Issue by kumy** [smira/aptly#197]
Hi,

don't know if it's a good idea or not :question: , but reversing words order from `aptly publish list -raw` would permit piping directly to `aptly drop`.

ex:
```
$ aptly publish list -raw
ubuntu-security/snapshots/20150207 trusty
ubuntu-security/snapshots/20150208 trusty
```
To

```
$ aptly publish list -raw
trusty ubuntu-security/snapshots/20150207
trusty ubuntu-security/snapshots/20150208
```

So we can easily do (maybe with a grep :wink:)
```
aptly publish list -raw | xargs -n 2 aptly publish drop
```

FTR: As a workaround:
```
aptly publish list -raw | sed 's/\(.*\) \(.*\)/\2 \1/' | xargs -n 2 aptly publish drop
```

**Comment by smira** [comment]
I agree 100% that the order I've chosen doesn't work quite well for `aptly publish drop`.

The same has been requested in #107. 

I'm not sure how to do that without breaking backwards compatibility.
