### ISSUE TITLE
question: Why you can't have same package in two different repository?

### ISSUE THREAD

**Issue by Jan-Marcek** [smira/aptly#199]
I would be nice to have..

**Comment by smira** [comment]
You can have same package in as many different repositories and any other aptly objects as you wish. If you have something more specific - feel free to reopen.

**Comment by Jan-Marcek** [comment]
aptly publish snapshot ...
```
Loading packages...
^M13 / 13  100.00 % ^MESC[2KGenerating metadata files and linking package files...
^M1 / 13  7.69 % ^MESC[2KERROR: unable to publish: unable to process packages: error linking file to /home/aptly/.aptly/public/pool/main/o/odn-solr/odn-solr_4.10.2-odn0.10.1_all.deb: file already exists and is different
```


```
 aptly repo -with-packages=true show testing
Name: testing
Comment: Development builds
Default Distribution:
Default Component: main
Number of packages: 13
Packages:
  odn-solr_4.10.2-odn0.10.1_all

```

```

aptly@proxy:~$ aptly repo -with-packages=true show main
Name: main
Comment: Stable releases
Default Distribution:
Default Component: main
Number of packages: 13
Packages:
  odn-solr_4.10.2-odn0.10.1_all
```

then what am I doing wrong? I'm unable to publish two repo with same package.

**Comment by Jan-Marcek** [comment]
please reopen the issue. I don't have a permission.

**Comment by smira** [comment]
Are these packages `odn-solr_4.10.2-odn0.10.1_all` actually the same? Or different?

Could you please show output of `aptly package show -with-references -with-files odn-solr_4.10.2-odn0.10.1_all` ?

**Comment by smira** [comment]
Also you might have this problem if you copied aptly root directory to some place losing information about hardlinks.

**Comment by Jan-Marcek** [comment]
```
$aptly package show -with-references -with-files odn-solr_4.10.2-odn0.10.1_all
Package: odn-solr
Version: 4.10.2-odn0.10.1
Installed-Size: 33294
Priority: extra
Section: web
Maintainer: Someone FIXME <dev@opendata.sk>
Architecture: all
Description: OpenData Node - SOLR engine
MD5sum: 34e662f05e8932b84b9010ab7bfbcdec
SHA1: 0d2a492b4ca485cebfc7424eb90c17f44768e9ea
SHA256: 39377adb1f3de112e3c014b500887e71d5971a3936aac5b714a612b50eeb5892
Homepage: http://opendata.sk
Filename: odn-solr_4.10.2-odn0.10.1_all.deb
Source:
Size: 30132554
Depends: openjdk-7-jre-headless, tomcat7-user

Files in the pool:
  /home/X/.aptly/pool/34/e6/odn-solr_4.10.2-odn0.10.1_all.deb

References to package:
  local repo [main]: Stable releases
  snapshot [odn-jenkins-testing-48]: Snapshot from local repo [main]: Stable releases
  snapshot [odn-jenkins-main-47]: Snapshot from local repo [main]: Stable releases
  snapshot [odn-jenkins-main-46]: Snapshot from local repo [main]: Stable releases
```

**Comment by Jan-Marcek** [comment]
root directory is ? .aptly? I don't copy .aptly -  as far as i remember

**Comment by smira** [comment]
hmmm... 

I would expect `aptly package show` to display two packages. 

From what I see (please correct me if I'm wrong), you've got two local repos, `main` and `testing`. Each of those repos contains package `odn-solr_4.10.2-odn0.10.1_all`, which are actually two different packages with the same name, version and architecture. 

aptly supports this case just fine, but when you try publishing both these repos under the same prefix, both packages  `odn-solr_4.10.2-odn0.10.1_all` would try to use path `/home/aptly/.aptly/public/pool/main/o/odn-solr/odn-solr_4.10.2-odn0.10.1_all.deb` to store package filename. This is how Debian package repo structure works: all distributions share common package pool.

As there are two different files which try to use the same filename, aptly warns you about that and refuses to continue with publishing.

You have two options:

* don't create duplicate packages with different content, e.g. add something like `~testing` to package version for packages in `testing` repo
* publish local repos under different prefixes (last parameter to `aptly publish` commands) to make them use separate `pool` directories

**Comment by Jan-Marcek** [comment]
Yes, I've resolved this problem by option 1. However I haven't understood the reason why I can't do this. It might be not so good user story. Maybe the repositories shouldn't share the pool.

**Comment by smira** [comment]
The reason why you can't do that is that in Debian repository format all distributions share common pool with package files. This is smart thing: it allows you to reuse same package files in multiple distribution sets. 

Debian itself never builds different packages under same (name, version, arch). You don't follow this recommendation and you can only have workaround as publishing prefix.

More on this topic: http://www.aptly.info/doc/feature/duplicate/

**Comment by dburm** [comment]
I agree with Jan-Marcek. The fact that Debian uses common pool is not a reason that you can't separate it. It just "best practice". But sometimes a "best practice" is not applicable for a particular solution.

**Comment by smira** [comment]
@dburm aptly allows you to have separate `pool/` directories by using publishing prefix

**Comment by dburm** [comment]
@smira publishing prefix doesn't allow to use common dists/ directory and multiple pools

**Comment by smira** [comment]
@dburm why do you need single `dists/` ?

**Comment by FlorentCoppint** [comment]
@smira Excuse me to "re-open" a previous issue, but when you say "aptly allows you to have separate pool/ directories by using publishing prefix", I'm not sure you're right, because prefixes are only used for "dists" directory, I didn't find how to have subdirectories in "pool" except setting -component=distribution/main instead of "main". It forces users to set "distribution distribution/main" in their sources.list...

**Comment by smira** [comment]
@FlorentCoppint no, `prefix/` moves `dists/` and `pool/` to `prefix/dists/` and `prefix/pool/`, so they are completely isolated

**Comment by FlorentCoppint** [comment]
Yes, but in the case you want to set-up a single repository (so a single prefix), but publish 2 distributions inside, there can be conflicts with packages all stored in prefix/pool (same name,version,arch but different content for each distribution). I know some repository publishers uses subdirectories into "pool", see for example : https://swupdate.openvpn.net/apt/
An option like this could be implemented in Aptly ?

**Comment by smira** [comment]
@FlorentCoppint no... aptly doesn't support such layout.

**Comment by FlorentCoppint** [comment]
Could it be a future feature ? I will try to take a look on the code, I don't think it's difficult to set this up.

**Comment by cure** [comment]
+1

**Comment by fengkaijia** [comment]
@FlorentCoppint In this way, one same package (same name, version, arch, and content) will still appear multiple times in these subdirectories unless using symlink. I think a better way would be auto-renaming the conflicting package when publishing from snapshot or repo. For example, I have 3 python-tornado_4.2.1-1_amd64.deb (same name, version, arch but with different content) for Trusty, Xenial and Jessie repo, when publishing, aptly will auto-rename these 3 conflicting packages to:

python-tornado_4.2.1-trusty1_amd64.deb
python-tornado_4.2.1-xenial1_amd64.deb
python-tornado_4.2.1-jessie1_amd64.deb

Then they can be placed in a single repository without any issue.

@smira How about adding this as a new feature?

**Comment by kumy** [comment]
IMO problems with versions should be handled at build level, not by aptly.
