### ISSUE TITLE
Getting keys and feeding apt-key in one step

### ISSUE THREAD

**Issue by backupchecker** [smira/aptly#202]
Hi,

In the Aptly documentation [1] you offer to get the GPG key of Aptly repository in 2 steps. It's possible to use only one step for this using the following command:

$ apt-key adv --keyserver keys.gnupg.net --recv-keys E083A3782A194991

[1] : http://www.aptly.info/download/

Hope it helps,
Carl Chenet

**Comment by smira** [comment]
Thanks, Carl, I'll update documentation and tutorials to include that!
