### ISSUE TITLE
Publish repository issue

### ISSUE THREAD

**Issue by zohaibtechknox** [smira/aptly#204]
thi is the issue i got when try to publish repository
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
ERROR: unable to publish: unable to detached sign file: exit status 2

**Comment by smira** [comment]
@zohaibtechknox you need to have GPG key to sign published repository.

You need either to generate one or to skip signing (not recommended) with --skip-signing

More info here: http://www.aptly.info/doc/aptly/publish/

**Comment by zohaibtechknox** [comment]
thanks i have solved it now by warching one of your previous thread :+1:
