### ISSUE TITLE
please can you help me how to publish repository to apache server?

### ISSUE THREAD

**Issue by zohaibtechknox** [smira/aptly#205]
i have a vm and i want to make this as locaapt repository server using apache. please mention this as well how to make packages.gz file in the repoistory thanks in advance.

**Comment by smira** [comment]
`Packages.gz` and other index files would be generated by aptly.

You need any webserver to serve directory `~/.aptly/public` (by default published repositories would be there). `aptly serve` can work for testing as well - it would serve that directory by HTTP.

I can't help you with Apache, but google for 'serving static files with apache` or whatever.

**Comment by zohaibtechknox** [comment]
ok thanks
