### ISSUE TITLE
issue updating on client machine?

### ISSUE THREAD

**Issue by zohaibtechknox** [smira/aptly#206]
i got this error Err when i try to get update of 
 http://192.168.100.111 trusty/main amd64 Packages
  404  Not Found
Ign http://192.168.100.111 trusty/main Translation-en
W: Failed to fetch http://192.168.100.111/dists/trusty/main/binary-amd64/Packages  404  Not Found

**Comment by smira** [comment]
I can't help you with that. There's not enough information.

Point your browser to http://192.168.100.111 

See what you're serving and so on, what you've into apt-sources.

**Comment by zohaibtechknox** [comment]
apt- sources file 
deb http://192.168.100.111/ trusty main

**Comment by smira** [comment]
I can't see what  http://192.168.100.111/ is, right?

You might have amd64 architecture missing there for example, there 1000s of reasons for this failure.

**Comment by zohaibtechknox** [comment]
i cant see the repositoy which created but with aptly  show command i can see how i can create a sub dir for amd64 ?

**Comment by smira** [comment]
If you have amd64 published, `aptly publish list` should show it for your published repositories.

Usually aptly guesses architectures correctly, but in case of problems you can always force architectures while publishing with `-architectures` flag. 

Anyway, please try following some tutorial to try aptly in some simple scenario: http://www.aptly.info/tutorial/

**Comment by zohaibtechknox** [comment]
ok

**Comment by zohaibtechknox** [comment]
this is what aptly publish list showing 
Published repositories:
  * ./trusty [amd64] publishes {main: [ubuntu2]}

**Comment by smira** [comment]
then amd64 is published,

next check contents of `~/.aptly/public`, check that it matches contents of  http://192.168.100.111/ - it should match filesystem contents

**Comment by zohaibtechknox** [comment]
i have made the .aptly file in the /var/www/html/ which is apache directory now .aptly/pulic has
dists pool var 
cd .aptly/public/dists/trusty/main/binary-amd64 has
Packages  Packages.bz2  Packages.gz  Release
i think var is extra directory or not?

**Comment by smira** [comment]
Filesystem view and "http" view should be the same.

Just try starting `aptly serve` to test it out, then fight with apache.
