### ISSUE TITLE
Snapshot: unable to parse command

### ISSUE THREAD

**Issue by 19kestier** [smira/aptly#207]
I created a mirror and updated it per the tutorial. http://www.aptly.info/tutorial/mirror/
It won't let me snaphot the mirror, though. It says `ERROR: unable to parse command`
![screenshot 2015-02-19 at 2 41 37 pm](https://cloud.githubusercontent.com/assets/4749568/6274445/b0fa1f56-b845-11e4-9ca6-08a110941e2f.png)

**Comment by smira** [comment]
@19kestier I believe you need `mirror` in your command:

`aptly snapshot create google64-... from mirror google64`
