### ISSUE TITLE
Online help (aptly publish help switch) issues

### ISSUE THREAD

**Issue by oCCtet** [smira/aptly#208]
Online help for aptly CLI command `publish switch` contains references to `publish update`, possibly confusing users. See command examples in the help output below:

    $ aptly publish help switch
    Usage: aptly publish switch <distribution> [[<endpoint>:]<prefix>] <new-snapshot>

    Command switches in-place published repository with new snapshot contents. All
    publishing parameters are preserved (architecture list, distribution,
    component).

    For multiple component repositories, flag -component should be given with
    list of components to update. Corresponding snapshots should be given in the
    same order, e.g.:

        aptly publish update -component=main,contrib wheezy wh-main wh-contrib

    Example:

        $ aptly publish update wheezy ppa wheezy-7.5

**Comment by smira** [comment]
Thanks for noticing that!
