### ISSUE TITLE
No way to set S3 endpoint hostname

### ISSUE THREAD

**Issue by wolfgang42** [smira/aptly#209]
AWS seems to have recently had some sort of policy change for new buckets. I created a bucket and tried to publish my aptly repository, but got this message:
```
$ aptly publish snapshot vagrant-1.7.2 s3:vagrant-deb.wolfgang42:
Loading packages...
Generating metadata files and linking package files...
ERROR: unable to publish: unable to process packages: error getting information about pool/main/v/vagrant/vagrant_1.7.2_x86_64.deb from S3: us-east-1:vagrant-deb.wolfgang42/: Head : 301 response missing Location header
```

When I visit a URL of the form <code>http://s3.amazonaws.com/vagrant-deb.wolfgang42/<var>[path]</var></code>, I get such an error message:
```xml
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>vagrant-deb.wolfgang42</Bucket><Endpoint>vagrant-deb.wolfgang42.s3.amazonaws.com</Endpoint><RequestId>...</RequestId><HostId>...</HostId></Error>
```
And indeed, visiting <code>http://vagrant-deb.wolfgang42.s3-us-west-2.amazonaws.com/<var>[path]</var></code> works properly.

It would seem that it's now necessary to specify the endpoint manually, but I can't find any way to do that in aptly.conf.

**Comment by smira** [comment]
I'll take a look, thanks for reporting that!

**Comment by smira** [comment]
@wolfgang42 when you access URL like http://s3.amazonaws.com/vagrant-deb.wolfgang42/ from your browser, you would expected redirect to http://vagrant-deb.wolfgang42.s3-us-west-2.amazonaws.com/. This is how HTTP access to the bucket works.

But I wonder - does it work if you change region to `us-west-2` in `aptly.conf`?

**Comment by smira** [comment]
More info here: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by smira** [comment]
Ok, I managed to reproduce it - if I create bucket in `Oregon` and set region to `us-east-1` in `aptly.conf` I get exactly the same error.

So you need to put correct region into aptly settings.

**Comment by wolfgang42** [comment]
Aha--I feel silly now. The AWS web console apparently puts `/s3/?region=us-east-1` in the URL even if your bucket is elsewhere, and I didn't stop to think that Oregon isn't actually on the East coast.

Thank you for your help--hopefully this will help someone else who makes the same mistake in the future.
