### ISSUE TITLE
Prefixes with slashes and API endpoints

### ISSUE THREAD

**Issue by zerkms** [smira/aptly#210]
Technically it's possible to create a `publish` with a nested directories prefix like `a/b/c`.

The problem is that current GIN routes don't allow so, eg:

    root.PUT("/publish/:prefix/:distribution", apiPublishUpdateSwitch)

Sending a request to `/publish/a/b/c/distro` fails with `404` since GIN cannot match any route to handle it.

**Comment by smira** [comment]
It's not documented yet, but you need to replace `/` with `_` in prefixes, and `_` with `__`.
