### ISSUE TITLE
[API] withDeps=1 does not seem to play well with query string (and it's position dependent)

### ISSUE THREAD

**Issue by zerkms** [smira/aptly#212]
These 2 requests return **different** results:

    curl http://localhost/api/repos/test-one/packages?q=package-b&withDeps=1
    curl http://localhost/api/repos/test-one/packages?withDeps=1&q=package-b

The first one returns 1 matched package (the exact match by name), the second one returns all the packages from the repository.

Neither of results is correct though: the `package-b` depends on `package-c`:

    Depends: php5-cli, package-c (>= 0.0.114-0)

and there is `"Pall package-c 0.0.115-0 fe0268e3209d793f"` in the repository that qualifies the dependency.

**Comment by smira** [comment]
Just in case, could you please send what curl sends to the server, i.e. request part from `curl -v` output?

**Comment by zerkms** [comment]
Good news here.

It works - it was my mistake of not putting the url in quotes so `&` was treated as a part of shell command. With quotes everything works as expected.

Sorry :-)
