### ISSUE TITLE
mirror, repo, and snapshot search should exit with search results

### ISSUE THREAD

**Issue by eheydrick** [smira/aptly#213]
Related to https://github.com/smira/aptly/issues/188, which sets exit status for package search, repo, mirror, and snapshot search should exit with a non-zero status if the search fails.

**Comment by smira** [comment]
Fixed in `master`.

**Comment by eheydrick** [comment]
Does this work for package search, repo search, and mirror search? Looks like just snapshot search was done.

**Comment by smira** [comment]
Package search is #188, other "searches" are all in single command, so it should work for all search commands.
