### ISSUE TITLE
Strange error output

### ISSUE THREAD

**Issue by mynamewastaken** [smira/aptly#219]
When the aptly db is locked due to another operation (in my case mirror update), attempting to tab complete results in this:

    aptly@host:~$ aptly mirror search <tab>
    cant         ERROR:       resource     unavailable
    database:    open         temporarily

**Comment by smira** [comment]
That's general problem in aptly: it should report errors to `stderr`.

**Comment by smira** [comment]
aptly should now report errors to `stderr`
