### ISSUE TITLE
API: use nginx to serve api

### ISSUE THREAD

**Issue by erickeller** [smira/aptly#229]
Hi Andrey,

I played a bit with the new Aptly API features, works great so far. I was wondering if there was a plan to host the api through nginx instead of using the `aptly api serve` command?

I did not find any reference within the documentation about it.

Thanks

**Comment by smira** [comment]
@erickeller you can proxy aptly API using any HTTP reverse proxy, including nginx. But you need to run `aptly api serve`, as it provides real API :)
