### ISSUE TITLE
Database locked while running api serve

### ISSUE THREAD

**Issue by davewongillies** [smira/aptly#234]
While running aptly's api service, commands such as `mirror` don't work as the api service locks the database. Is this expected behaviour?

**Comment by smira** [comment]
Yes, this is expected. There's a plan to include mirror into API as well. Also probably having CLI commands issue API requests to service when appropriate.

**Comment by fpytloun** [comment]
Hello, we are facing the same issue.
Lock file is created on first API request and never removed while api server is running.
In my opinion this is a regular bug - API server should remove lock file when action/call that locked the database is over.

Of course best for the future would be API server supporting all actions and aptly client that would be able to use API.

**Comment by smira** [comment]
@fpytloun you can try to close database in `api/api.go`, `cacheFlusher` function. This would release the lock, but next API call might fail if database is locked.

**Comment by Jan-Marcek** [comment]
I'm just curious: Why don't you use apache2 as web server?

**Comment by fpytloun** [comment]
@Jan-Marcek how does it relate to API server? Api serve is executed from init script and requests are comming through Nginx proxy.

**Comment by Jan-Marcek** [comment]
I'm sorry I missed the fact that API had been introduced to aptly. I was not aware of it.

**Comment by avongluck-r1soft** [comment]
Being able to execute aptly from the command line would be a *really* nice feature.  An alternative would be to have the aptly tool detect a running API server in the local .aptly and attempt to run all commands through it.  The biggest issue with things like aptly-cli is the differing commands to perform tasks. (and aptly-cli is incomplete)
