### ISSUE TITLE
snapshot switch fails to respect the S3 plusWorkaround

### ISSUE THREAD

**Issue by derekwyatt** [smira/aptly#239]
(This is aptly `0.9.5`) I do all of my publishing to S3. The publishing works well, and respects the `plusWorkaround` kludge.  However, when trying to perform an `aptly publish switch` the file copies aren't maintained - i.e. the `plusWorkaround` doesn't seem to apply - and I get the all-too-familiar `404` when trying to access a file with a `+` in it.

I've worked around this by dropping the published record, and then doing an `aptly publish ...` instead of a `switch`.  This works great, is a bit slower, but not brutal.

**Comment by smira** [comment]
This is a bug, aptly first puts files with `+` replaced by ` `, but during cleanup phase after publish switch it removes all those "duplicates". It should filter out files with ` ` when listing published contents on S3.

**Comment by smira** [comment]
@derekwyatt could you please try with latest nightly, `aptly_0.9.6~dev+114+g38dfe34` ?

**Comment by derekwyatt** [comment]
It looks like it's working.  Thanks a lot!
