### ISSUE TITLE
Adding a package to existing mirror

### ISSUE THREAD

**Issue by ksalman** [smira/aptly#245]
I have a mirror to which I want to add a package that is not part of upstream repository. What is good way of doing that? Would I create a local repo with that package and then create a merged snapshot from the mirror and the local repo snapshot? Or is there another way?

**Comment by GLolol** [comment]
> Would I create a local repo with that package and then create a merged snapshot from the mirror and the local repo snapshot?

That's exactly what I do for this.

**Comment by ksalman** [comment]
Thanks, that worked just fine.
