### ISSUE TITLE
Aptly shouldn't quit on some errors

### ISSUE THREAD

**Issue by SamClinckspoor** [smira/aptly#251]
Currently aptly quits on all errors.
This is very frustrating when trying to publish very large mirrors to s3 or update large mirrors.
Its almost impossible to publish large repositories to s3 as there is always at least one package failing.

I think it would be better to send a warning to the user, and report all failed packages at the end of the run, with an option to retry.

The following commands would benefit from this change:
- aptly mirror update
- aptly task run
- aptly publish snapshot
- aptly publish repo
- aptly repo import

There might be more cases.

**Comment by smira** [comment]
@SamClinckspoor I think the best option here is to do retry for S3 publishing, so that it would do automatic retries on S3 errors. With `mirror update` there's no such option: aptly would restart where it left on errors, but mirror should be downloaded completely to make it usable.

**Comment by SamClinckspoor** [comment]
Automatic retries for s3 would also work.

**Comment by smira** [comment]
@SamClinckspoor I've created #255 to track S3 retries, don't think there's much else I can do

**Comment by smira** [comment]
S3 retries are available in nightly build, along with some other S3-related improvements.
