### ISSUE TITLE
Aptly: interaction between testing and production repos

### ISSUE THREAD

**Issue by vitalyisaev2** [smira/aptly#252]
Hi Andrey. We've been using `Aptly` since the `0.9` release (as we were waiting for REST API) and it works very well. Aptly gives a huge amount of features (like mirroring and snapshots), and for a novice sometimes it's hard to choose a right way of `Aptly` integration in a particular work flow. So it would be very nice to hear your opinion on the `Aptly` use in our case. Here's what we going to do:

1. `Git` events on `master` branch triggering `Jenkins` build jobs;
2. `Jenkins` launches `Docker` containers where `git-buildpackage` tries to compile code and build `deb` package.
3. If the build job has been finished succesfully, resulting `debs` are pushed to `Aptly`. Else exit.
4. `Jenkins` performes some tests with the most recent packages;
5. If the tests have been passed, the testing repo is synced with a production repo.

We have already implemented items 1 — 4 . Actually I'm asking about the implementation of the latter one. 

How should `Aptly` be configured for this task? Do we need to perform a command like 
```bash
aptitude download package && ./push_to_production_aptly.sh package.deb
```
after every successfull test passing? Or we can move packages among the `Aptly` repos without departing from the scope of server?

Please note that `Aptly` itself works in `Docker` container too, so we should rely on REST API commands (not CLI). Thank you very much.

**Comment by smira** [comment]
Hi Vitaly!

Once you're sure that package in testing repository is ready for production (tests are fine, ...), you can copy it from testing repository to production:

1. Figure out package ID. `GET /api/repos/:name/packages?q=my-package (version)'. This should return single result - package ID. (Show packages/search API)
2. Add package by ID to production repo. `POST /api/repos/:name/packages` with `PackageRefs` set to result of step 1. (Add packages by key API).
3. Take snapshot & publish switch (or update published repository), depends on your publishing workflow.

Steps 1 and 2 are equivalent to aptly CLI command `aptly repo copy testing-repo production-repo 'my-package (version)'`.

**Comment by vitalyisaev2** [comment]
Hello Andrey, thank you for a prompt reply! I'll try this approach soon.

**Comment by fpytloun** [comment]
Hello Vitaly, you could be interested in approach and tooling that we are using which is very similar to what you have described (https://github.com/tcpcloud/python-aptly)

**Comment by vitalyisaev2** [comment]
@fpytloun thank you, I'll definitely going to try your Python client (to be honest, I had to write my own one half a year ago, but I always wanted to find full-featured client library).

**Comment by fpytloun** [comment]
@vitalyisaev2 unfortunately it's not full featured yet, it's just low-level library for creating API connection + tooling for publishing.
But I would like to extend it to provide Python objects for Aptly ones with methods for all actions that can be done on them via API.
A good inspiration is python-foreman - https://github.com/david-caro/python-foreman
Which uses API definition in JSON to create Python objects using metaclasses - unfortunately there's no machine-readable definition of Aptly API resources yet to be able to use it as a source.
