### ISSUE TITLE
s3 region eu-central-1 is unknown

### ISSUE THREAD

**Issue by meyju** [smira/aptly#253]
Hi, 
I would like to host my repository in the aws region eu-central-1 witch is online since  23 Oct 2014.

If I configure a repository in that region, i get the following message:
ERROR: unknown region: "eu-central-1"

I think the awslib has to be updated for this new region

**Comment by smira** [comment]
Should be fixed in nightly build `aptly_0.9.6~dev+111+g9d298de`.
