### ISSUE TITLE
Allow repoquery-like output specification for repo search and package search

### ISSUE THREAD

**Issue by jdelic** [smira/aptly#254]
While working with aptly I now repeatedly wished for being able to use it in scripts more effectively. To do so, it would be very useful if you could not only query using reprepro-like syntax, like it is possible now, but also specify the output format. For example:

  * list all versions and revisions of a package in a repository:

```
$ aptly repo search mypackage -format="%{version} %{release} %{epoch}"
1.5.10 5 2
1.5.10 6 2
$ aptly package search mypackage -format="%{repo} %{version} %{release}"
stable 1.5.10 5
testing 1.6.3 1
upstream 2.0-dev 1
```

The benchmark here is probably yum's `repoquery -qf`, but even a simple implementation that does not support full `sprintf`-like syntax would be immensely useful for scripting. 

(I would love to label this as 'enhancement', but alas I'm not allowed to)

**Comment by smira** [comment]
I really love this feature, but I would probably choose different format based on Go templates, but the idea would be the same.

**Comment by smira** [comment]
Available in nightly build `aptly_0.9.6~dev+135+gba4669a`

**Comment by jdelic** [comment]
I can't wait for 0.9.6 :). Thanks for implementing this so quickly!

**Comment by quentinsf** [comment]
Yes - agreed - many thanks!
