### ISSUE TITLE
Can't remove published snapshot with '-','=' chars in it, even with '--'

### ISSUE THREAD

**Issue by damageboy** [smira/aptly#256]
Hi,
`aptly publish list -raw | grep =`:
```
-distribution=gitlab-trusty trusty
```

`aptly publish drop -- -distribution=gitlab-trusty`:
```
ERROR: unable to remove: published repo with storage:prefix/distribution ./-distribution=gitlab-trusty not found
```

**Comment by smira** [comment]
So you have prefix + distribution in `aptly publish list -raw`, in your case prefix is `-distribution=gitlab-trusty`, distribution is `trusty`.

So to drop it:

```
aptly publish drop trusty -distribution=gitlab-trusty
```

(`drop` like many commands accepts prefix as last argument).

**Comment by damageboy** [comment]
Ah!
Thanks, I feel stupid now...
