### ISSUE TITLE
table@build error I·0 "open /aptly/ubuntu/.aptly/db/000911.ldb: too many open files"

### ISSUE THREAD

**Issue by erickeller** [smira/aptly#260]
Hi Andey,

with aptly 0.9.5 version

I got this in the db/LOG, aptly was usable as no mirror ever existed.

the default for ulimit -n is 1024
so I doubled the limit to 2048 it worked fine.

But after doing some 

```
lsof -n -P | grep aptly
```

I noticed there where several thousand of files open during a simple aptly snapshot list operation

I also took a look at the db directory, and found out the number of *.ldb files is constantly growing, I do not know the internal of ldb, but seems these files form the DB, meaning at some point it will open all these files, maybe it will grow over the 2048 limit again.

any idea, did someone else encountered this problem?

**Comment by erickeller** [comment]
more details 

```
ulimit -n
2048
```

```
repo@vagrant-base-trusty-amd64:~/aptly/ubuntu$ aptly mirror list
No mirrors found, create one with `aptly mirror create ...`.
```

```
ls /aptly/ubuntu/.aptly/db/*.ldb | wc -l
2077
```

**Comment by erickeller** [comment]
apparently the aptly db cleanup use the leveldb compact command, resulting in less db/*.ldb files.
seems to be related to:
https://code.google.com/p/leveldb/issues/detail?id=175

Regards

**Comment by smira** [comment]
Yes, it looks to be one of the problems with LevelDB in general (and `goleveldb` in particular). If it creates too many table files.

Could be related: https://github.com/syndtr/goleveldb/issues/67

**Comment by smira** [comment]
At the same time aptly is using version of goleveldb which already includes fix from that issue.

@erickeller were all the files in `lsof` just table files `*.ldb`?

**Comment by erickeller** [comment]
I did not filter lsof on table file level, but I imagine that these are the one loaded by leveldb.
I could imagine to setup a container ulimit -n 42 and create some snapshot of a tiny mirror to force leveldb to create new table files. so you could reproduce the problem...

Regards

**Comment by smira** [comment]
So this make sense - with default ulimit of 1024 and goleveldb going up to 1000, aptly download might use other 24 left. Need to set goleveldb limit lower.
