### ISSUE TITLE
unable to initialize GPG verifier

### ISSUE THREAD

**Issue by timurb** [smira/aptly#272]
When I install Aptly on fresh MacOSX and try to run it I see the following error:
```
ERROR: unable to initialize GPG verifier: unable to execute gpgv: exec: "gpgv": executable file not found in $PATH (is gpg installed?)
```

At the same time I have `gnupg` installed from brew before doing that.
I've disabled `"gpgDisableVerify": true,` in `~/.aptly.conf` and all strated to work fine but I'd like to avoid that.

Probably updating installation docs for Mac should be enough to resolve this.

**Comment by smira** [comment]
@timurb you need to install GPG. You can do e.g. using Homebrew: `brew install gpg`

**Comment by timurb** [comment]
@smira 
It pulls `gnupg` which I already have installed but there is no binary named `gpgv` in the path.
There is but `gpgv2` in the path which probably does the same.

In any case could you please update the docs on aptly site regarding the installation?

**Comment by smira** [comment]
```
$ brew install gpg
==> Downloading https://homebrew.bintray.com/bottles/gnupg-1.4.19.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gnupg-1.4.19.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/gnupg/1.4.19: 53 files, 5.5M
$ gpgv --version
gpgv (GnuPG) 1.4.19
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

gpgv is just a different binary name for gpg, so you should either have both or none of them :)

**Comment by timurb** [comment]
Thanks! You are right, I've had a clash with MacGPG2 and that's why there was no gpgv in PATH.
