### ISSUE TITLE
aptly:  Unable to find expected entry 'main/binary-i386/Packages'

### ISSUE THREAD

**Issue by fankbach** [smira/aptly#273]
Hello,
aptly version: 0.9.5
step by step:
1. create mirror
aptly mirror create -architectures=amd64 trusty-ceph-hammer http://ceph.com/debian-hammer trusty main
2. update
aptly mirror update trusty-ceph-hammer
3. snapshot
aptly snapshot create trusty-ceph-hammer-20150721 from mirror trusty-ceph-hammer
4. publish
aptly publish snapshot -distribution=trusty-ceph-hammer trusty-ceph-hammer-20150721 trusty
5. add source to client system
deb http://server.fqdn/trusty/ trusty-ceph-hammer main
6. apt-get update

Get:1 http://server.fqdn trusty-ceph-hammer InRelease [1,788 B]
Hit http://server.fqdn trusty InRelease
Get:2 http://server.fqdn trusty-ceph-hammer/main amd64 Packages [7,335 B]
Hit http://server.fqdn trusty/main amd64 Packages
Hit http://server.fqdn trusty/main i386 Packages
Ign http://server.fqdn trusty/main Translation-en_US
Ign http://server.fqdn trusty/main Translation-en
Fetched 9,123 B in 2s (4,274 B/s)
W: Failed to fetch http://server.fqdn/trusty/dists/trusty-ceph-hammer/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
E: Some index files failed to download. They have been ignored, or old ones used instead.

There are non entries into the InRelease file with i386. So, I don't know, where the binary-i386 path come from
client: Linux Ubuntu Trusty 3.13.0-29-generic x86_64 GNU/Linux

with apt-cache show ceph, I get the additionally packets displayed.

(root@clientname:/etc/apt/sources.list.d $) apt-cache show ceph
Package: ceph
Priority: optional
Section: admin
Installed-Size: 61541
Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.hu>
Architecture: amd64
Version: 0.94.2-1trusty
![image](https://cloud.githubusercontent.com/assets/13470937/8855789/5ff04ebe-3167-11e5-9c5d-ccbe0300b82a.png)

Can anyone give a hint?
Best regards 
Frank

**Comment by smira** [comment]
Frank, to make apt happy, drop published repo:

```
aptly publish drop trusty-ceph-hammer trusty
```

And publish it forcing `i386` architecture:

```
aptly publish snapshot -architecures=am64,i386 -distribution=trusty-ceph-hammer trusty-ceph-hammer-20150721 trusty
```

This would generate empty indexes for i386 (as there are no i386 packages).

**Comment by fankbach** [comment]
Hello smira,
great! This works pretty good. Thank you for this quick answer!
Best regards
Frank
