### ISSUE TITLE
aptly tries to fetch Packages even after successful fetch of Packages.bz2

### ISSUE THREAD

**Issue by gdhbashton** [smira/aptly#274]
With aptly `0.9.5` I am unable to create a local mirror of Ubuntu repos:

```
# aptly mirror create -ignore-signatures=true ubuntu-main http://mirror.vorboss.net/ubuntu-archive/ trusty main
Downloading http://mirror.vorboss.net/ubuntu-archive/dists/trusty/Release...

Mirror [ubuntu-main]: http://mirror.vorboss.net/ubuntu-archive/ trusty successfully added.
You can run 'aptly mirror update ubuntu-main' to download repository contents.

# aptly mirror update -ignore-signatures=true ubuntu-main
Downloading http://mirror.vorboss.net/ubuntu-archive/dists/trusty/Release...
Downloading & parsing package files...
Downloading http://mirror.vorboss.net/ubuntu-archive/dists/trusty/main/binary-amd64/Packages.bz2...
Downloading http://mirror.vorboss.net/ubuntu-archive/dists/trusty/main/binary-arm64/Packages.bz2...
Downloading http://mirror.vorboss.net/ubuntu-archive/dists/trusty/main/binary-arm64/Packages.gz...
Downloading http://mirror.vorboss.net/ubuntu-archive/dists/trusty/main/binary-arm64/Packages...
ERROR: unable to update: HTTP code 404 while fetching http://mirror.vorboss.net/ubuntu-archive/dists/trusty/main/binary-arm64/Packages
```

`Packages.bz2` is shown with the ASCII progress meter to download OK - so why does aptly try to hit the `.gz` and uncompressed `Packages` file?

Am I doing something wrong?

Cheers,
Gavin.

**Comment by smira** [comment]
@gdhbashton this is common problem with Ubuntu repos. `Release` files lists many architectures as being supported, while not all of them have files. aptly processes `amd64`, then goes to `arm64`, which is missing.

Workaround is to restrict architecture list, either when you create the mirror or by editing it afterwards:

   aptly mirror create -architectures=amd64,i386 ... 

Or:

   aptly mirror edit -architectures=amd64,i386 ubuntu-main

**Comment by gdhbashton** [comment]
Thank you :) Just noticed I hadn't replied - how very rude of me!
