### ISSUE TITLE
GetContentsFromDeb fails on malformed tar archives without mentioning the culprit package

### ISSUE THREAD

**Issue by sobczyk** [smira/aptly#275]
example package http://old-releases.ubuntu.com/ubuntu/pool/universe/n/ns3/ns3-doc_3.15+dfsg-1_all.deb
It's a bad data.tar.gz in the .deb
it even fails with normal tar CLI tool

aptly should at least inform about the package name + repository/snapshot
and even better, suggest what to do (what filter to apply)

Right now the message is
```
Loading packages...
Generating metadata files and linking package files...
panic: unable to read .tar archive: unexpected EOF [recovered]
        panic: unable to read .tar archive: unexpected EOF

goroutine 1 [running]:
github.com/smira/aptly/cmd.func·028()
        /myhome/aptly/_vendor/src/github.com/smira/aptly/cmd/run.go:16 +0xa0
github.com/smira/aptly/deb.(*Package).CalculateContents(0xc20b5fdec0, 0x7f4882f94cc0, 0xc20807f2a0, 0x0, 0x0, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/aptly/deb/package.go:435 +0x336
github.com/smira/aptly/deb.(*PackageCollection).loadContents(0xc20807f340, 0xc20b5fdec0, 0x7f4882f94cc0, 0xc20807f2a0, 0x0, 0x0, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/aptly/deb/package_collection.go:183 +0x36f
github.com/smira/aptly/deb.(*Package).Contents(0xc20b5fdec0, 0x7f4882f94cc0, 0xc20807f2a0, 0x0, 0x0, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/aptly/deb/package.go:414 +0x106
github.com/smira/aptly/deb.(*ContentsIndex).Push(0xc2113f8080, 0xc20b5fdec0, 0x7f4882f94cc0, 0xc20807f2a0)
        /myhome/aptly/_vendor/src/github.com/smira/aptly/deb/contents.go:26 +0x4d
github.com/smira/aptly/deb.func·016(0xc20b5fdec0, 0x0, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/aptly/deb/publish.go:567 +0x899
github.com/smira/aptly/deb.(*PackageList).ForEachIndexed(0xc20b0d5080, 0xc20a7af750, 0x0, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/aptly/deb/list.go:139 +0xea
github.com/smira/aptly/deb.(*PublishedRepo).Publish(0xc2080f9860, 0x7f4882f94cc0, 0xc20807f2a0, 0x7f4882f94d78, 0xc20806e0b0, 0xc20810ae00, 0x7f4882f94c68, 0xc20960e7e0, 0x7f4882f94d08, 0xc20962fc50, ...)
        /myhome/aptly/_vendor/src/github.com/smira/aptly/deb/publish.go:592 +0x10ad
github.com/smira/aptly/cmd.aptlyPublishSnapshotOrRepo(0xc2080fde60, 0xc208036260, 0x4, 0x4, 0x0, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/aptly/cmd/publish_snapshot.go:143 +0x1775
github.com/smira/commander.(*Command).Dispatch(0xc2080fde60, 0xc208036260, 0x4, 0x4, 0x0, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/commander/commands.go:305 +0x653
github.com/smira/commander.(*Command).Dispatch(0xc208100240, 0xc208036250, 0x5, 0x5, 0x0, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x208
github.com/smira/commander.(*Command).Dispatch(0xc208100a20, 0xc208036240, 0x6, 0x6, 0x0, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x208
github.com/smira/aptly/cmd.Run(0xc208100a20, 0xc20800a010, 0xa, 0xa, 0x1, 0x0)
        /myhome/aptly/_vendor/src/github.com/smira/aptly/cmd/run.go:40 +0x1bd
main.main()
        /myhome/aptly/main.go:9 +0x80

goroutine 5 [syscall, 10 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 21 [sleep]:
github.com/cheggaaa/pb.(*ProgressBar).writer(0xc20d8a1ef0)
        /myhome/aptly/_vendor/src/github.com/cheggaaa/pb/pb.go:332 +0x62
created by github.com/cheggaaa/pb.(*ProgressBar).Start
        /myhome/aptly/_vendor/src/github.com/cheggaaa/pb/pb.go:101 +0xa8
```

**Comment by sobczyk** [comment]
ar->gzip->tar has a bug
when I ran a testcase against only gzip->tar (unpacked data.tar.gz) it worked fine
adding ar unpacker gives the error above, thus it's a library bug, not a broken deb

**Comment by sobczyk** [comment]
fixed here:
mkrautz/goar/pull/2

it was a bug that showed with large files

**Comment by pdf** [comment]
Getting a build against the fixed goar would be great, but I agree whole-heartedly that including some more useful context with the panic would be very useful.  I've got this error affecting some package in my repo, but I have no idea which one.

**Comment by smira** [comment]
@sobczyk thanks for cathing that!

**Comment by smira** [comment]
Should be fixed in `aptly_0.9.6~dev+143+gc160cbc`

**Comment by foursixnine** [comment]
Hi guys, i just happened to cross my roads with this bug. I'm using aptly version: 0.9.7. I remember that particularily for certain -doc packages of our releases, we had issues when trying to install. 

This might be related?

> root@algol-a:~# time aptly publish repo --distribution=trusty smartmatic 
> L> oading packages...
> Generating metadata files and linking package files...
> panic: unable to read .tar archive from /root/.aptly/pool/3b/93/package-name-hidden-0.6.143.265-i386-doc.deb: unexpected EOF [recovered]
> 	panic: unable to read .tar archive from /root/.aptly/pool/3b/93/package-name-hidden-0.6.143.265-i386-doc.deb: unexpected EOF
> 
> goroutine 1 [running]:
> github.com/smira/aptly/cmd.Run.func1(0x18d45f94)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/cmd/run.go:16 +0x67
> github.com/smira/aptly/deb.(*Package).CalculateContents(0x1a84f4a0, 0xb767e7d0, 0x18c105c0, 0x0, 0x0, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/deb/package.go:427 +0x169
> github.com/smira/aptly/deb.(*PackageCollection).loadContents(0x18c10650, 0x1a84f4a0, 0xb767e7d0, 0x18c105c0, 0x0, 0x0, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/deb/package_collection.go:183 +0x2c6
> github.com/smira/aptly/deb.(*Package).Contents(0x1a84f4a0, 0xb767e7d0, 0x18c105c0, 0x0, 0x0, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/deb/package.go:410 +0x61
> github.com/smira/aptly/deb.(*ContentsIndex).Push(0x1ab1a4e8, 0x1a84f4a0, 0xb767e7d0, 0x18c105c0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/deb/contents.go:26 +0x3b
> github.com/smira/aptly/deb.(*PublishedRepo).Publish.func1(0x1a84f4a0, 0x0, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/deb/publish.go:568 +0x75d
> github.com/smira/aptly/deb.(*PackageList).ForEachIndexed(0x18dcc9e0, 0x18d45a8c, 0x0, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/deb/list.go:169 +0xbd
> github.com/smira/aptly/deb.(*PublishedRepo).Publish(0x18d56000, 0xb767e7d0, 0x18c105c0, 0xb767e838, 0x18d5ea20, 0x18da7e60, 0xb767e7a0, 0x19152870, > 0xb767e7f8, 0x18dcc880, ...)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/deb/publish.go:593 +0xee9
> github.com/smira/aptly/cmd.aptlyPublishSnapshotOrRepo(0x18d69c20, 0x18da6ff0, 0x1, 0x2, 0x0, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/cmd/publish_snapshot.go:145 +0x117e
> github.com/smira/commander.(*Command).Dispatch(0x18d69c20, 0x18da6ff0, 0x1, 0x2, 0x0, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:305 +0x4d4
> github.com/smira/commander.(*Command).Dispatch(0x18d69e60, 0x18da6fe8, 0x2, 0x3, 0x0, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x17a
> github.com/smira/commander.(*Command).Dispatch(0x18da82d0, 0x18da6fe0, 0x3, 0x4, 0x0, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x17a
> github.com/smira/aptly/cmd.Run(0x18da82d0, 0x18c0a0c8, 0x4, 0x5, 0x875be01, 0x0)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/cmd/run.go:40 +0x144
> main.main()
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/main.go:9 +0x65
> 
> goroutine 33 [syscall, 34 minutes]:
> os/signal.loop()
> 	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:22 +0x1a
> created by os/signal.init.1
> 	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:28 +0x36
> 
> goroutine 40 [sleep]:
> time.Sleep(0xbebc200, 0x0)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/time.go:59 +0xe6
> github.com/cheggaaa/pb.(*ProgressBar).writer(0x1aa7f950)
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/cheggaaa/pb/pb.go:332 +0x5a
> created by github.com/cheggaaa/pb.(*ProgressBar).Start
> 	/Users/smira/Documents/go/src/github.com/smira/aptly/_vendor/src/github.com/cheggaaa/pb/pb.go:101 +0x9c
>

**Comment by smira** [comment]
Quick workaround is to `--skip-contents` when publishing, so that this code path is skipped completely
