### ISSUE TITLE
CalculateContents is slow

### ISSUE THREAD

**Issue by sobczyk** [smira/aptly#276]
it extracts contents on every publish, even if contents of a package did not change

CalculateContents could use some cache ie leveldb
SHA256 -> {age, contents}
update age on use, after publish prune too old entries

right now trusty mirror update is extremely slow when generating contents

**Comment by smira** [comment]
It should cache contents on per-package basis, so it shouldn't do that on each publish

**Comment by sobczyk** [comment]
what I'm doing is mirroring ubuntu repository
```
aptly mirror create trusty-universe http://archive.ubuntu.com/ubuntu trusty universe
aptly mirror update trusty-universe
```
create local repository, and import the mirrors repos
```
aptly repo create trusty-universe
aptly repo import trusty-universe trusty-universe 'Name (~ .*)'
```
publish the repos as several internal releases (I want to maintain 1-1 naming convention with internal software releases) this should not have significant space or computation overhead since most of content extracton is done during first pubish
```
aptly publish repo -component=universe -distribution=distro1 trusty-universe
aptly publish repo -component=universe -distribution=distro2 trusty-universe
```

When I have some more time I'm going to time it

**Comment by smira** [comment]
Contents are cached per-package, and memory requirements were brought down recently in 1.0.0 release
