### ISSUE TITLE
Graph repo comments don't contain newlines

### ISSUE THREAD

**Issue by avongluck-r1soft** [smira/aptly#280]
The graph of repos doesn't show newlines in comments.

This means repo comments like this:

build XXX\n
This: 1.0.0\n
That: 1.0.1\n

Turn into this in the graph:

buildXXXThis: 1.0.0That: 1.0.1

**Comment by jola5** [comment]
I don't think this is still an issue: 

![Repo multiline comments](http://i.imgur.com/Ngde6Mr.png)

I suggest to close this bug as `fixed`

**Comment by smira** [comment]
Thanks, @jola5!
