### ISSUE TITLE
3 way snapshot merge -latest does not work properly

### ISSUE THREAD

**Issue by jrdyer** [smira/aptly#283]
I am not sure if what I am experiencing is a bug or I am misunderstanding how this functionality works.

I have three repos.  One contains our companies home grown packages.  The other is a snapshot of trusty main.  Another of security updates.

When I merge the three, I end up with overlaps in versions.  I would expect to only see the latest versions between the three.  As in I would not expect to see two different qemu_kvms.  

I tried rearranging the order in which I specified the repos to see if that impacted anything and it did not appear to.  Its as if the security updates 

root@aptly:~# aptly snapshot merge -latest test-101 trusty-main-10.29.14 company-1000.0-212 trusty-security-main-10.29.14

Snapshot test-101 successfully created.
You can run 'aptly publish snapshot test-101' to publish snapshot as Debian repository.
root@aptly:~# aptly snapshot show -with-packages test-101 |grep qemu
  ipxe-qemu_1.0.0+git-20131111.c3d1e78-2ubuntu1_all
  qemu-common_2.0.0+dfsg-2ubuntu1.3_all
  qemu-keymaps_2.0.0+dfsg-2ubuntu1.3_all
  qemu-kvm_2.1.0+company1000.0+7_amd64
  qemu-system_2.1.0+company1000.0+7_amd64
  qemu-system-arm_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-common_2.1.0+company1000.0+7_amd64
  qemu-system-mips_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-misc_2.1.0+company1000.0+7_amd64
  qemu-system-ppc_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-sparc_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-x86_2.1.0+company1000.0+7_amd64
  qemu-user_2.1.0+company1000.0+7_amd64
  qemu-utils_2.1.0+company1000.0+7_amd64
  qemu-kvm_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-arm_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-common_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-mips_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-misc_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-ppc_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-sparc_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-x86_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-utils_2.0.0+dfsg-2ubuntu1.3_i386
root@aptly:~# aptly snapshot show -with-packages trusty-main-10.29.14 | grep qemu
  ipxe-qemu_1.0.0+git-20131111.c3d1e78-2ubuntu1_all
  qemu-common_2.0.0~rc1+dfsg-0ubuntu3_all
  qemu-keymaps_2.0.0~rc1+dfsg-0ubuntu3_all
  qemu-kvm_2.0.0~rc1+dfsg-0ubuntu3_amd64
  qemu-system_2.0.0~rc1+dfsg-0ubuntu3_amd64
  qemu-system-arm_2.0.0~rc1+dfsg-0ubuntu3_amd64
  qemu-system-common_2.0.0~rc1+dfsg-0ubuntu3_amd64
  qemu-system-mips_2.0.0~rc1+dfsg-0ubuntu3_amd64
  qemu-system-misc_2.0.0~rc1+dfsg-0ubuntu3_amd64
  qemu-system-ppc_2.0.0~rc1+dfsg-0ubuntu3_amd64
  qemu-system-sparc_2.0.0~rc1+dfsg-0ubuntu3_amd64
  qemu-system-x86_2.0.0~rc1+dfsg-0ubuntu3_amd64
  qemu-utils_2.0.0~rc1+dfsg-0ubuntu3_amd64
root@aptly:~# aptly snapshot show -with-packages company-1000.0-212 | grep qemu
  qemu-kvm_2.1.0+company1000.0+7_amd64
  qemu-system_2.1.0+company1000.0+7_amd64
  qemu-system-common_2.1.0+company1000.0+7_amd64
  qemu-system-misc_2.1.0+company1000.0+7_amd64
  qemu-system-x86_2.1.0+company1000.0+7_amd64
  qemu-user_2.1.0+company1000.0+7_amd64
  qemu-utils_2.1.0+company1000.0+7_amd64
root@aptly:~# aptly snapshot show -with-packages trusty-security-main-10.29.14 | grep qemu
  qemu-common_2.0.0+dfsg-2ubuntu1.3_all
  qemu-keymaps_2.0.0+dfsg-2ubuntu1.3_all
  qemu-kvm_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-arm_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-common_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-mips_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-misc_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-ppc_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-sparc_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-system-x86_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-utils_2.0.0+dfsg-2ubuntu1.3_amd64
  qemu-kvm_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-arm_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-common_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-mips_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-misc_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-ppc_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-sparc_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-system-x86_2.0.0+dfsg-2ubuntu1.3_i386
  qemu-utils_2.0.0+dfsg-2ubuntu1.3_i386

root@aptly:~# aptly snapshot diff -only-matching trusty-main-10.29.14 company-1000.0-212 | grep qemu-kvm
! amd64  | qemu-kvm                                 | 2.0.0~rc1+dfsg-0ubuntu3                  | 2.1.0+company1000.0+7
root@aptly:~# aptly snapshot diff -only-matching trusty-main-10.29.14 trusty-security-main-10.29.14 | grep qemu-kvm
! amd64  | qemu-kvm                                 | 2.0.0~rc1+dfsg-0ubuntu3                  | 2.0.0+dfsg-2ubuntu1.3
root@aptly:~# aptly snapshot diff -only-matching company-1000.0-212 trusty-security-main-10.29.14 | grep qemu-kvm
! amd64  | qemu-kvm                                 | 2.1.0+company1000.0+7                    | 2.0.0+dfsg-2ubuntu1.3

**Comment by smira** [comment]
This sounds like a bug.

**Comment by smira** [comment]
@jrdyer it looks like it's not a bug

You don't have any duplicates in package lists, there are packages for `i386` and `amd64` architectures. One version for amd64 arch gets overridden, because you have it, and other version for `i386` is not overridden. Depending on your goals, you might want to stop mirroring `i386` or filter out `i386` in your snapshot.

**Comment by jrdyer** [comment]
I have tried adding the -architectures=amd64 to my snapshot merge command, but am still getting i386 packages.  What am I missing for proper filtering?

**Comment by smira** [comment]
snapshot merge doesn't use this flag, you need to do e.g. `aptly snapshot filter` with query `$Architecture (amd64)`.
