### ISSUE TITLE
Drop multiple snapshots at once

### ISSUE THREAD

**Issue by luhkevin** [smira/aptly#284]
I don't think it is possible to do this yet? This would really speed along snapshot deletion when one is playing around with aptly and generates a bunch of snapshots.

**Comment by GLolol** [comment]
:+1: I use snapshots for publishing and create a new one (by date) whenever I publish. This means that over many months, I accumulate a ton of these old snapshots that aren't used anymore, and there's no easy way to remove them.

**Comment by Jan-Marcek** [comment]
+1

However I'm using this script.
```
aptly snapshot list  -config=/home/aptly/.aptly.conf |  grep "snapshot-[0-9]*" -o | xargs -I{} aptly snapshot  -config=/home/aptly/.aptly.conf drop
```

**Comment by smira** [comment]
You can always use something like that:

     aptly snapshot list -raw | grep something | xargs -n 1 aptly snapshot drop

**Comment by smira** [comment]
With `-raw` aptly displays just snapshot names.
