### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by martinhoefling** [smira/aptly#285]
We are using aptly to publish a large snapshot to a S3 Bucket. We frequently hit a "net/http: TLS handshake timeout" error, which aborts our complete publishing process

    13396 / 45145  29.67 % 18m34s
    13399 / 45145  29.68 % 18m34s
    13402 / 45145  29.69 % 18m34s
    13402 / 45145  29.69 % 8m0s
    ?[2KERROR: unable to publish: unable to process packages: error getting information about pool/main/libc/libcsv-java/libcsv-java-doc_2.0-12_all.deb from S3: us-east-1:ourbucketname/: Head https:/ourbucketname/pool/main/libc/libcsv-java/libcsv-java-doc_2.0-12_all.deb: net/http: TLS handshake timeout

Any ideas how one could fix that? Maybe retrying such an upload n-times is an option to avoid re-upload of the entire snapshot? One could also increase the TLS timeout which is 10s in GO net/http by default.

**Comment by smira** [comment]
@martinhoefling it might have been already fixed in aptly nightly builds, see issue #255

**Comment by martinhoefling** [comment]
OK, I'll report back if a new release fixed our issue.

**Comment by smira** [comment]
Please feel free to reopen is problem is still there
