### ISSUE TITLE
Allow creation of a snapshot of an empty repository

### ISSUE THREAD

**Issue by vincentbernat** [smira/aptly#288]
Hi!

When trying to snapshot an empty repository, we get:

```
ERROR: unable to create snapshot: local repo doesn't have packages
```

This is easy to circumvent by creating an empty snapshot instead but it would be more convenient if aptly just created an empty snapshot in this case.

**Comment by fpytloun** [comment]
Hello,

I agree, there should be an option to allow creation of empty snapshots.
So one can create multi-component publish eg. with aptly-publisher even when there are no packages in some of the components.

**Comment by smira** [comment]
+1, this should be easy to fix, this is just check in the code which should be removed

**Comment by fpytloun** [comment]
Cool, thank you for fixing this :-)

**Comment by smira** [comment]
Should be available now in `aptly_1.0.0+30+ga245b72` nightly
