### ISSUE TITLE
weird R repo not publishing as expected

### ISSUE THREAD

**Issue by jschmidt3786** [smira/aptly#289]
after running the following:
```bash
gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keys.gnupg.net --recv-keys 381BA480
aptly mirror create -architectures="amd64,i386" cran3-jessie http://mirror.las.iastate.edu/CRAN/bin/linux/debian jessie-cran3/
aptly mirror update cran3-jessie
aptly snapshot create cran3-jessie-`date -I` from mirror cran3-jessie
aptly -distribution="jessie" -passphrase-file="${HOME}/.pass" publish snapshot cran3-jessie-`date -I` cran3-jessie
```
I end up with a rather strange published repo, and one that nginx is not happy with (nginx isn't serving up the '.-jessie-cran3-' directory, as expected).

```
mirror:
 * [cran3-jessie]: http://mirror.las.iastate.edu/CRAN/bin/linux/debian/ ./jessie-cran3/

snapshot:
 * [cran3-jessie-2015-08-26]: Snapshot from mirror [cran3-jessie]: http://mirror.las.iastate.edu/CRAN/bin/linux/debian/ ./jessie-cran3/

publish:
  * cran3-jessie-2015-08-26/.-jessie-cran3- [amd64, i386] publishes {main: [cran3-jessie-2015-08-26]: Snapshot from mirror [cran3-jessie]: http://mirror.las.iastate.edu/CRAN/bin/linux/debian/ ./jessie-cran3/}
```

is there a way to change this behavior?

**Comment by smira** [comment]
It looks like you've published with different command. First, publishing prefix was `cran3-jessie-2015-08-26`, and your command has `cran3-jessie`. Next, aptly tried to guess distribution name from your mirror distribution (flat repo) (which aptly shouldn't do) and ended up with weird `.-jessie-cran3-`. So it looks like `-distrubution=` flag was missing.

I would drop this repo:

```
aptly publish drop .-jessie-cran3- cran3-jessie-2015-08-26
```

And try re-publishing it.

**Comment by jschmidt3786** [comment]
that must've been it, seems fine now - I'll revisit the cron job that set that up.
thanks, Andrey!
