### ISSUE TITLE
Prevent 'aptly repo add <name> .' from a folder already belonging to aptly

### ISSUE THREAD

**Issue by cintiadr** [smira/aptly#293]
Last Friday I ran into a very weird behaviour. 

I was naively following some (misleading) instructions from a colleague, which recommended me to go to the aptly folder (default I believe is ```/home/aptly/aptly/public```), and run ``` aptly repo add <my_name> .```. It was a live repository, so it already had a few .deb deployed there. 

Clearly it is a silly thing to do. As documentation mentions, in case of a folder, aptly will recursively look for .deb and add them to the repo. Weird thing is I didn't receive any errors, but suddenly all the .deb in pool folder became empty (zero bytes). Which took me ages to realise, as apt-get update as working as before, I just was unable to install a package. 

While I know it was my fault for not having read the doco upfront, it wasn't a pleasant experience to have my first contact with aptly. I would love to have a huge warning like 'you are about to make something pretty stupid scanning the repository folder to add debian files, are you really sure?'. 

I'm using 0.8, not sure if 0.9 would help here, but I haven't found any issue closed for that.

**Comment by smira** [comment]
Yep, fixed in #127, please upgrade to the latest version.
