### ISSUE TITLE
Locking problem during "aptly repo add"?

### ISSUE THREAD

**Issue by dankegel** [smira/aptly#294]
Using aptly 0.9.5 on Ubuntu.
- aptly repo add -remove-files=true repo-foo-precise-rel incoming.tmpdir

ERROR: can't open database: resource temporarily unavailable

Some other buildslaves did things like 'aptly publish update' or 'aptly repo remove' vaguely around the same time, fwiw.

This is the first day of using aptly, so whatever it is, it's probably not too hard to reproduce.

**Comment by smira** [comment]
aptly locks the database before running any command (that's limitation of the db, LevelDB). So there should be exactly one aptly instance running at the same time...
