### ISSUE TITLE
gnupg 2.x support

### ISSUE THREAD

**Issue by philtay** [smira/aptly#296]
it would be nice if aptly could support gnupg 2.x out of the box (i.e. gpg2 instead of gpg)

currently only gnupg 1.x is supported

call gpg and if fails try gpg2 in all the lines like [this one](https://github.com/smira/aptly/blob/master/utils/gpg.go#L130)

**Comment by liliakai** [comment]
To support gpg2, it sounds like aptly just needs to run `gpg-agent` and `gpg-preset-passphrase` prior to signing.
