### ISSUE TITLE
regression of #117

### ISSUE THREAD

**Issue by rgevaert** [smira/aptly#298]
Hi,

I upgraded to aptly 0.9.5 and it seems I'm hitting bug #117 .  

    Mirror `wheezy-security` has been successfully updated.
    aptly@debs1:~$ echo $?
    123

**Comment by smira** [comment]
@rgevaert do you have complete log for this issue? I can't reproduce that and aptly has exactly three exit codes: `0`, `1` and `2`.

**Comment by rgevaert** [comment]
Hello, can you tell which options you want me to pass to aptly to get more verbose output?

Previously I used: "aptly mirror list -raw | grep ^$1 | xargs -n 1 aptly mirror update".  Now I have put in a for loop.

**Comment by smira** [comment]
Well in such command result code comes from xargs... right? Not aptly. 

In xargs `123 means "any invocation exited with a non-zero status"`, http://stackoverflow.com/questions/26540813/got-exit-code-123-in-find-xargs-grep

So you need to look through all commands xargs invoked and find the one which failed.

**Comment by smira** [comment]
Please feel free to re-open if you have new information
