### ISSUE TITLE
Cannot see number of security updates available using mirrors created by aptly

### ISSUE THREAD

**Issue by jmo-learnosity** [smira/aptly#306]
I'm running the latest stable version of aptly and have created and published a mirror for the main, security and updates repositories for Ubuntu Trusty:

```
$ aptly publish list --raw | grep ubuntu
s3:my-mirror:ubuntu trusty
s3:my-mirror:ubuntu-security trusty-security
s3:my-mirror:ubuntu-updates trusty-updates
```

I can see and download packages from these mirrors, but when I try to see how many packages that are available are security updates, it shows 0.

```
$ cat /etc/apt/sources.list
deb http://my.aptly.mirror/ubuntu/ trusty main
deb http://my.aptly.mirror/ubuntu-security/ trusty-security main
deb http://my.aptly.mirror/ubuntu-updates/ trusty-updated main
$ /usr/lib/update-notifier/apt-check --human-readable
124 packages can be updated.
0 updates are security updates.
```

While with the upstream repo used directly, I see:
```
$ cat /etc/apt/sources.list
deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe
deb http://us.archive.ubuntu.com/ubuntu/ trusty-security main universe
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main universe
$ /usr/lib/update-notifier/apt-check --human-readable
129 packages can be updated.
42 updates are security updates.
```

**Comment by smira** [comment]
@jmo-learnosity I believe this is because aptly doesn't correctly mirror all fields of the `Release` file

**Comment by jmo-learnosity** [comment]
@smira After having done some further investigation, I've found what causes this. It is to do with the Release file that is generated, but the issue is with the values set as the "Origin".

From the official Ubuntu mirror:
```
Origin: Ubuntu
Label: Ubuntu
Suite: trusty-security
Version: 14.04
Codename: trusty
<snip>
```

The one generated by aptly in my mirror:
```
Origin: ubuntu-security trusty-security
Label: ubuntu-security trusty-security
Suite: trusty-security
Codename: trusty-security
```

This Origin value is read by the scripts that are distributed with Ubuntu (and, presumably, Debian) that are used to check for pending updates and security updates. These scripts mark a package as a security update if the origin is `{distribution name}` (ie. "Ubuntu" in my case)

Is it an intentional decision to have this value rewritten to something other than the one given in the source repo?

**Comment by smira** [comment]
@jmo-learnosity you can override `Origin` with `-origin` flag for now (http://www.aptly.info/doc/aptly/publish/snapshot/). Long-term solution (there should be an issue for it already) is to preserve `Origin` value from the upstream mirror.

**Comment by jmo-learnosity** [comment]
@smira I'll work around this issue for the moment by providing that option at publish time. Happy to have this issue closed.

**Comment by smira** [comment]
Please see #184
