### ISSUE TITLE
Locking issues

### ISSUE THREAD

**Issue by mattes** [smira/aptly#310]
It seems as if database/ leveldb locking is a pain for aptly. https://github.com/smira/aptly/issues?utf8=%E2%9C%93&q=is%3Aissue+lock

If only one process can access the database, maybe we should follow a different approach:
An aptly daemon that exposes a unix/http socket. This is essentially how the Docker daemon works, too.

**Comment by smira** [comment]
yes, CLI could be rewritten to talk to API daemon, but this is complicated task

**Comment by smira** [comment]
aptly API now drops the lock on in inactivity, so it should be possible to use API and CLI concurrently. Also aptly drops the lock while downloading packages in `aptly mirror update`. So optimistic retry should avoid locking issues. We can add retry to aptly itself if required.
