### ISSUE TITLE
Is there any way transfer apt-mirror to aptly?

### ISSUE THREAD

**Issue by qzerolee** [smira/aptly#314]
Hi, 
I'm using aptly, it's pretty good. I made a local mirror using apt-mirror, it downloaded more than 240GB files, is there any way transfer that mirror to aptly?

Thanks for help.

**Comment by smira** [comment]
@qzerolee you can try mirroring from your local mirror, if you serve it as HTTP-accessible repository. So you start webserver at localhost, do aptly mirror from http://localhost/..., then you can drop that aptly mirror, create aptly mirror from upstream, but aptly won't download files once again - it will re-use whatever has already been downloaded.

**Comment by ealtintas** [comment]
I have written this script: https://github.com/ealtintas/aptly-convert.py and used it to trasnfer my local apt-mirror repositories to aptly. It saved me a lot of time and bandwidth. I hope it to be usefull for others.
