### ISSUE TITLE
ERROR: unable to update: fsync: invalid argument

### ISSUE THREAD

**Issue by erickeller** [smira/aptly#317]
Hi everyone,

currently getting the following error when updating mirror:

```
ERROR: unable to update: fsync: invalid argument
```

After some digging I found out that the aptly leveldb is hosted on a cifs share.

https://github.com/google/leveldb/issues/281

One idea would be to separate the leveldb from the "rootDir" defined in the .aptly.conf file.

Regards

Eric

**Comment by smira** [comment]
@erickeller you can use symlinks to put one part on regular FS and another on CIFS. But I haven't tested any of aptly work on CIFS, and I doubt it would work (hard links).

**Comment by erickeller** [comment]
thanks for the response, I was able to make this workaround, using a non cifs for hosting the db and mounting the pool as cifs.
But I will discourage this setup.

**Comment by erickeller** [comment]
Hi Andrey, I think you can close this issue...
