### ISSUE TITLE
support ceph s3/swift api

### ISSUE THREAD

**Issue by MrRagga-** [smira/aptly#318]
Hi,
it would be great if aptly also supports publishing to ceph s3/swift API

ceph S3: http://docs.ceph.com/docs/master/radosgw/s3/
ceph swift: http://docs.ceph.com/docs/master/radosgw/swift/

**Comment by smira** [comment]
Custom S3 should be supported via custom endpoint: http://beta.aptly.info/doc/feature/s3/

**Comment by grimmy** [comment]
I've set my endpoint to just a hostname (per the docs) and a full URL, but aptly keeps complaining about the region.

If I don't specify a region I get

```
ERROR: unknown region: ""
```

And if you do specify a real region I get 403 unauthorized, which a quick packet sniff shows DNS queries for s3-1.amazonaws.com and not for my rados gateway.

And if I specify a fake region (as per the docs) i get the same

```
ERROR: unknown region: ""
```

So

**Comment by smira** [comment]
@grimmy what version of aptly are you using? it should work with nightly builds given that you configure endpoint

**Comment by grimmy** [comment]
I was using the release version.  I worked around the problem for now by just writing a quick python script that dumps everything to ceph. I'll give it a go with the nightly though
