### ISSUE TITLE
Mirror Debian Security Repository

### ISSUE THREAD

**Issue by 001001** [smira/aptly#322]
I have difficulty mirroring and publishing the debian security repository in a format the installer likes. When I publish, aptly creates jessie-updates instead of jessie/updates. Reproduce:

aptly version: 0.8

aptly -architectures="amd64" -with-udebs=true mirror create jessie-security http://security.debian.org/ jessie/updates main contrib non-free
aptly snapshot create sec-snap from mirror jessie-security
aptly publish snapshot sec-snap

deb http://your-server/ jessie-updates main

aptly publish list
Published repositories:
  * ./jessie-updates [amd64] publishes {main: [sec-snap]: Snapshot from mirror [jessie-security]: http://security.debian.org/ jessie/updates [udeb]}

ls dists/jessie-updates/
InRelease  main  Release  Release.gpg

Is there another way I should do this?

**Comment by smira** [comment]
Please see #110 this is related to the way aptly handles published repositories, it changes `/` to `-` while publishing. When #110 is resolved, this should work as expected.
