### ISSUE TITLE
Aptly cannot update http://nginx.org/packages/ubuntu trusty nginx

### ISSUE THREAD

**Issue by JohannesEbke** [smira/aptly#328]
aptly version: 0.9.5
Pulling from http://nginx.org/packages/ubuntu trusty nginx:

Updating mirror nginx-repo...
Downloading http://nginx.org/packages/ubuntu/dists/trusty/InRelease...
Downloading http://nginx.org/packages/ubuntu/dists/trusty/Release...
Downloading http://nginx.org/packages/ubuntu/dists/trusty/Release.gpg...
ERROR: unable to update: malformed stanza syntax

Perhaps this is related to the fact that nginx uses an unarmored Release.gpg file:
http://nginx.org/packages/ubuntu/dists/trusty/Release.gpg

**Comment by eholzbach** [comment]
Still errors if you set ignore-signatures=true

Downloading http://nginx.org/packages/ubuntu/dists/trusty/Release...
ERROR: unable to fetch mirror: malformed stanza syntax

**Comment by smira** [comment]
Stanza is broken there:

```
SHA1
 ebd5d8eb8bea40a1f888eceafe885d913b4abf90 6004 nginx/binary-i386/Packages
...
SHA256
 8e22dc6c348baff78bb7d7cd0af13f99e0ac401ce944b7bde194a15e7ffc987d 6004 nginx/binary-i386/Packages
```

The `:` is missing after field name.

**Comment by thresheek** [comment]
It's now fixed - thanks for digging into!  was a typo in our repo generating scripts.
