### ISSUE TITLE
unable to guess distribution name on Ubuntu Trusty 14.04

### ISSUE THREAD

**Issue by pavel-odintsov** [smira/aptly#335]
Hello!

Thanks for awesome toolkit! It makes my life much times simpler =)

But I have got issue on my Ubuntu 14.04 box.

So aptly could not detect distribution name automatically:
```bash
./aptly publish snapshot  -gpg-key="mykeyid" -component=mytool  -passphrase-file=/root/xxxx first_test_release
```

```bash
ERROR: unable to publish: unable to guess distribution name, please specify explicitly
```

Could you add automatic dsitro name detection for Ubuntu 14.04? It's pretty popular and could improve aptly tool.

**Comment by smira** [comment]
This is not a bug. aptly guesses distribution name by following graph of of sources starting from the snapshot up to mirrors. If mirrors have different distribution names, or local repos, aptly would fail to guess it. 

This is not a problem, just specify distribution name with `-distribution=` while publishing.

**Comment by shivan1b** [comment]
Hi @smira!
I tried passing `-distribution=testing` while publishing the snapshot, I still get the same error. I checked the repo from which I created the snapshot, its `Distribution` field is empty. Could you please point to what am I doing wrong?
