### ISSUE TITLE
Locking issues, api calls non-functional after cli

### ISSUE THREAD

**Issue by avongluck-r1soft** [smira/aptly#343]
When running the apty 9.6.0 api in no-lock, api calls like graph.png break after cli aptly executes.

[GIN] 2016/02/03 - 13:05:20 | 200 | 1.991951807s | 127.0.0.1:55292 |   GET     /api/graph.png
run CLI tools
[GIN] 2016/02/03 - 13:16:04 | 500 | 169.975462ms | 127.0.0.1:55359 |   GET     /api/graph.png
[GIN] 2016/02/03 - 13:16:07 | 500 |  183.16334ms | 127.0.0.1:55292 |   GET     /api/graph.png
[GIN] 2016/02/03 - 13:16:08 | 500 |  180.58619ms | 127.0.0.1:55292 |   GET     /api/graph.png
[GIN] 2016/02/03 - 13:16:15 | 500 | 170.654224ms | 127.0.0.1:55292 |   GET     /api/graph.png

**Comment by avongluck-r1soft** [comment]
seems like not *all* api calls fail:
[GIN] 2016/02/03 - 13:22:18 | 200 |   4.319349ms | 127.0.0.1:55359 |   GET     /api/version
[GIN] 2016/02/03 - 13:22:53 | 200 | 881.603804ms | 127.0.0.1:55359 |   GET     /api/graph.png

**Comment by smira** [comment]
@avongluck-r1soft: PR #346 may fix this issue

**Comment by avongluck-r1soft** [comment]
A quick note that I've confirmed the issue is solved. Thanks!
