### ISSUE TITLE
API: Publish update slow since 0.9.6 / failing on BadGateway

### ISSUE THREAD

**Issue by fpytloun** [smira/aptly#345]
After upgrade from 0.9.5 to 0.9.6, publish update of large collection takes extremely long time (respectively it fails before it completes on 504 Bad Gateway on side of Nginx proxy).

I have noticed it calls `xz --decompress --stdout` as a part of this process which seems to be new in this release and connected with slow down. What was exactly changed?

Raising timeouts for both proxy and API client didn't help ending up with:
```
2016/02/08 12:20:45 [error] 12951#0: *13 upstream prematurely closed connection while reading response header from upstream, client: 10.0.107.171, server: apt01.prd.hv1.cloudlab.cz, request: "PUT /api/publish/nightly/trusty HTTP/1.1", upstream: "http://127.0.0.1:8080/api/publish/nightly/trusty", host: "apt01.cloudlab.cz:8081"
```

Request looks like this:
```
DEBUG:aptly.client:PUT http://apt01.cloudlab.cz:8081/api/publish/nightly/trusty, data={"ForceOverwrite": false, "Snapshots": [{"Component": "galera-s9s", "Name": "galera-s9s-1440419251"}, {"Component": "tcp-salt", "Name": "tcp-salt-1454695280"}, {"Component": "juno", "Name": "_juno-1454929768"}, {"Component": "extra", "Name": "_extra-1454929768"}, {"Component": "liberty", "Name": "_liberty-1454929768"}, {"Component": "tcp", "Name": "_tcp-1454926929"}, {"Component": "kilo", "Name": "_kilo-1454929768"}, {"Component": "security", "Name": "trusty-security-1454929528"}, {"Component": "main", "Name": "_main-1454929768"}, {"Component": "oc21", "Name": "oc21-1440419251"}, {"Component": "oc22", "Name": "oc22-1447341942"}]}
```

Everything works fine again after downgrade.

**Comment by smira** [comment]
Problem is Contents generation, it's very slow... Probably it should be disabled by default

**Comment by fpytloun** [comment]
Is it possible to disable/enable it over API?
I don't see this option in API documentation: http://www.aptly.info/doc/api/publish/

**Comment by smira** [comment]
yeah, that's missing in 0.9.6, I'll add that option and probably disable it by default in config

**Comment by smira** [comment]
Contents publishing can now be disabled with `"SkipContents": true` in publish APIs.

**Comment by smira** [comment]
`aptly_0.9.7~dev+17+gffafed4` nightly build includes this fix

**Comment by fpytloun** [comment]
Great, thank you :-)
Will implement the option in python-aptly's publisher.

**Comment by fpytloun** [comment]
Option `--publish-contents` introduced in tcpcloud/python-aptly 0.7.2
