### ISSUE TITLE
CLOSE_WAIT connection after s3 upload

### ISSUE THREAD

**Issue by damaex17** [smira/aptly#358]
We are using aplty to manage our repositories in S3.
It seems aplty (0.9.6) doesn't close the connection with S3 corrently which results in 20-40 CLOSE_WAIT connections for each publishing process.

**Comment by smira** [comment]
@damaex17 could you please try with latest nightly build? It has S3 code completely replaced, so I suspect that bug might have gone away...

**Comment by damaex17** [comment]
I tested with  0.9.7~dev+25+g067d197 and the s3 upload seems to be broken in this version.
We have a timeout of 300 seconds and this is not enough to publish to s3 anymore

**Comment by smira** [comment]
@damaex17 what are the hash sum mismatch errors? do they happen when mirror is being updated?

**Comment by damaex17** [comment]
I didn't really investigate and reverted back to 0.9.6.

All clients complained about the hash sum mismatch issue with any software I published via 0.9.7.
After reverting to 0.9.6 and publishing again everything started working again.

**Comment by smira** [comment]
Closing as `CLOSE_WAIT` bug seems to be resolved.
