### ISSUE TITLE
0.9.6 _very_ slow during aptly publish snapshot

### ISSUE THREAD

**Issue by mynamewastaken** [smira/aptly#359]
Hi,

During a chef run `aptly publish snapshot -distribution='precise' -component 'main' ubuntu-qa-20160302 ubuntu-qa` ran _very_ slowly, and eventually timed out after an hour. I ran it manually and saw that out of ~40k packages or so it slowed down immensely around the ~27k mark. `strace` seemed to indicate it was spending a lot of time waiting in futex, but I no longer have the log. Since the repo is important, I downgraded to 0.9.5 which seemed to solve the issue. I realize it's not a lot to go on, but wanted to file the issue to get this on the radar in case anyone else came looking.

This was on an Ubuntu 12.04 LTS box on aptly version 0.9.6 - downgrading aptly to 0.9.5 fixed it.

**Comment by smira** [comment]
@mynamewastaken see #87, you can use `-skip-contents` to avoid `Contents` indices generation.

**Comment by mynamewastaken** [comment]
@smira I don't have enough time to look at/update the Chef cookbook we use for aptly, so I think I will stay on 0.9.5 for now. Thanks for the quick response!
