### ISSUE TITLE
Memory usage skyrocketing when switching snapshots

### ISSUE THREAD

**Issue by atduke** [smira/aptly#369]
Hi,

I upgraded from aptly 0.9.5 to 0.9.6 a few days ago and tried switching published snapshots today. 

Switching was terribly slow so I took a closer look on the server. I discovered that it was swapping heavily, because aptly was eating up all available RAM. By the time I killed the aptly process, aptly already used 2G.

After downgrading to 0.9.5 everything went smoothly again.

I'll be happy to provide more information for debugging purposes.

Cheers,
Tom.

**Comment by smira** [comment]
@atduke please try `-skip-contents` flag for `aptly publish` command.

**Comment by atduke** [comment]
@smira yup, with -skip-contents aptly 0.9.6 is as fast as 0.9.5 and memory usage is about the same.

**Comment by daachi** [comment]
I'm seeing this behavior as well with 0.9.7. Publishing snapshots basically consumes all the memory and while the process finishes, used memory is not being freed.

**Comment by smira** [comment]
@daachi you can disable contents generation (which is one time for each package anyway)

**Comment by smira** [comment]
Should be fixed in `1.0.0`
