### ISSUE TITLE
Ubuntu 16.04: weak GPG hash used on clearsign

### ISSUE THREAD

**Issue by thebwt** [smira/aptly#380]
Howdy!

ubuntu 16.04's version of apt  seems to be getting strict on algorithms used for repos.

W: gpgv:/var/lib/apt/lists/FOOBAR_InRelease: The repository is insufficiently signed by key BARFOO (weak digest)

I'm pretty sure this is because the InRelease is signed with sha1. I don't see a flag to change that to something like sha256.

Am I doing it wrong/missing something?

You can see what I mean in aptly's own repos: http://repo.aptly.info/dists/squeeze/InRelease

**Comment by smira** [comment]
I think #366 fixed it

**Comment by thebwt** [comment]
That it does, we can close this. thanks!

**Comment by thebwt** [comment]
Backported the commit to v0.9.6 in case we don't get v0.9.7 before 16.04 goes GA

https://github.com/thebwt/aptly/tree/v0.9.6.1

**Comment by smira** [comment]
0.9.7 has been released, not announced yet
