### ISSUE TITLE
support APT 'by-hash' indexes

### ISSUE THREAD

**Issue by sandrotosi** [smira/aptly#381]
this is a new way to generate/fetch indexes: https://wiki.debian.org/RepositoryFormat#indices_acquisition_via_hashsums_.28by-hash.29 (lengthy discussion of the pro of this method: http://www.chiark.greenend.org.uk/~cjwatson/blog/no-more-hash-sum-mismatch-errors.html)

it would be good to have such support in aptly

**Comment by sandrotosi** [comment]
any news on this?

**Comment by smira** [comment]
We have PR #551, I consider merging it for 1.2.0

**Comment by smira** [comment]
New PR #664

**Comment by smira** [comment]
Should be available now in nightly build `aptly_1.1.1+75+g9cb2a30`
