### ISSUE TITLE
New release for SHA256 support?

### ISSUE THREAD

**Issue by alanfranz** [smira/aptly#383]
Hello,
I've seen that 1069458aee25b406c8d5b8c29d37a01b6786d2ef provides SHA256 support for APT repositories; that's great, but so far there was no stable release of aptly including that commit.

Some users of my repositories are beginning to complain about the warning, and since it will be enabled by default in the upcoming Ubuntu Xenial, I'd ask if it's possible to do a stable release of aptly before that date (I prefer not running straight from master).

Thanks,

Alan

**Comment by smira** [comment]
@alanfranz sure, making next release at the moment

**Comment by smira** [comment]
0.9.7 is built/available, but not announced yet

**Comment by alanfranz** [comment]
Installed and tested, working 100% for my use case. Thank you very much!
