### ISSUE TITLE
GPG signing (key with passphrase) without a TTY fails even if passphrase is passed by flag

### ISSUE THREAD

**Issue by ariaviran** [smira/aptly#385]
Hi,
I'm trying to execute a `publish` command automatically via SSH. My GPG key has a passphrase, so I pass it as a flag, but `aptly` fails due to a lack of tty, although no user input is needed.

Example:

```
[14:23:29] [ari@malory] % ssh <host with aptly> "sudo aptly publish switch -passphrase=<passphrase> <name> <snapshot>"
Loading packages...
Generating metadata files and linking package files...
Finalizing metadata files...
Signing file 'Release' with gpg, please enter your passphrase when prompted:
gpg: cannot open tty `/dev/tty': No such device or address
ERROR: unable to publish: unable to detached sign file: exit status 2
```

When forcing SSH to create a tty it works **without user intervention**:

```
[14:34:58] [ari@malory] % ssh -tt <host with aptly> "sudo aptly publish switch -passphrase=<passphrase> <name> <snapshot>"
Loading packages...
Generating metadata files and linking package files...
Finalizing metadata files...
Signing file 'Release' with gpg, please enter your passphrase when prompted:

You need a passphrase to unlock the secret key for
<key details>

Clearsigning file 'Release' with gpg, please enter your passphrase when prompted:

You need a passphrase to unlock the secret key for
<key details>

Cleaning up prefix "." components main...

Publish for snapshot <name> [amd64] publishes <snapshot> has been successfully switched to new snapshot.
Connection to <host with aptly> closed.
```

I believe this is a bug, a tty shouldn't be required if user intervention is not needed

**Comment by michaelimfeld** [comment]
Hi,
I think passing the `-batch=true` option to the aptly command should fix this issue.

**Comment by smira** [comment]
@michaelimfeld thanks, I think it should fix it... https://www.aptly.info/doc/aptly/publish/snapshot/

**Comment by ariaviran** [comment]
@michaelimfeld Thanks.
@smira - I now see it is properly documented in the URL you provided, thank you. I think it will also be useful to add it to the question regarding GPG signing automation in the [FAQ](https://www.aptly.info/doc/faq/), or even better, since aptly knows that I don't need user interaction since I passed the 'passphrase' flag, it could pass automatically pass the 'batch' flag to GPG.

Thanks again
