### ISSUE TITLE
aptly sorting algorithm when querying is incorrect

### ISSUE THREAD

**Issue by rul** [smira/aptly#386]
A piece of stdout is worth a thousand words:

    $ aptly repo search  my-repo "Name (my-package), Version (<= 0.167.8-1~trusty)"
    my-package_0.167.8-1~trusty_amd64
    my-package_0.167.7-1~trusty_amd64
    my-package_0.167.10-1~trusty_amd64

So, `my-package_0.167.10-1~trusty_amd64` shouldn't be there. Note that this a kind of important bug. I've detected it because I've a script to automatically delete old packages using that query, and it was deleting the more recent package.

**Comment by smira** [comment]
Please follow the documentation: https://www.aptly.info/doc/feature/query/

You need to use `$Version` or different query format to get correct comparison for package version.

**Comment by rul** [comment]
Oops, thanks for the pointer. I completely missed that one.
