### ISSUE TITLE
Missing xz-utils in package deps

### ISSUE THREAD

**Issue by XANi** [smira/aptly#393]
aptly publish dies with:

```
panic: unable to unxz data.tar.xz from /var/lib/aptly/pool/8b/67/0ad_0.0.17-1_amd64.deb: exec: "xz": executable file not found in $PATH [recovered]
    panic: unable to unxz data.tar.xz from /var/lib/aptly/pool/8b/67/0ad_0.0.17-1_amd64.deb: exec: "xz": executable file not found in $PATH
```

there is no xz-utils in deps of aptly(0.9.7) package (after install of xz-utils it works fine)

**Comment by smira** [comment]
Is it for package coming from Debian repository?

**Comment by XANi** [comment]
Yes. Should I file bug in Debian instead ?

**Comment by smira** [comment]
I will send email to Debian maintainer, I think I forgot to ask him to add this dependency.

**Comment by XANi** [comment]
bzip2 is also needed and it will be missing in barebones Debian install (I just found out after reinstalling VM from scratch)

**Comment by sdelafond** [comment]
0.9.7 is not yet packaged in Debian, it should happen soon.

The current version in Debian sid is 0.9.6-1, and it depends on both bzip2 and xz-utils.

**Comment by smira** [comment]
Oh, I think @XANi you're using package from `repo.aptly.info`? I think it has bzip2 and xz-utils under `Recommends:`

**Comment by XANi** [comment]
Yes. We install our servers with `APT::Install-Recommends "0";` which is probably cause for lack of those on clean install, however IMO it is really a requirement for any useful setup, so it should be required package.

**Comment by sdelafond** [comment]
Again, the package in Debian sid already depends on those:

  Package: aptly
  Maintainer: Sebastien Delafond <seb@debian.org>
  Depends: bzip2, xz-utils, gnupg, gpgv, libc6 (>= 2.3.2)

**Comment by linuxluser** [comment]
When getting Debian packages from `repo.aptly.info` repository, there is an odd inconsistency in whether or not the 'Depends' field even shows up. It appears that versions that are published by Sebastien Delafond are more complete and contain the 'Depends' field while versions that are published by Andrey Smirnov are less complete and do not container the 'Depends' field.

This is what I'm seeing from my box when I run `apt-cache show aptly`: https://gist.github.com/linuxluser/df267c0534f81d80be2c35294f1fe414

How can we get consistency when packages are added to `repo.aptly.info`?

**Comment by smira** [comment]
What's the real issue here, as packages from repo.aptly.info have the same packages in `Recommends` (they're not strictly required for aptly to function properly).

**Comment by XANi** [comment]
The issue is that publish does not work if package uses xz for compression (which AFAIK is how all new packages do it) so end result is  "working" aptly that can't actually publish the repository. So it really have to be in `Required` to work (and that is how Debian package does it currently).

Recommends works under default configuration but many server installs (including ours, which is why I noticed that) will have `APT::Install-Recommends` set to false to cut on unnecessary deps.

**Comment by smira** [comment]
So I really have no preference here... same way aptly needs gpg, bzip2, graphviz, image viewer and so on. 

Changing `Recommends` to `Depends` is easy, I will take that as action item to sync with upstream Debian package.

**Comment by fozboz** [comment]
This has suddenly become a problem again. I'm using "http://repo.aptly.info/" source. Was working fine last week.
`root@fosta:~# apt-cache depends aptly`
`aptly`

**Comment by smira** [comment]
@fozboz are you using nightly or release repository?

Fix was applied for `1.1.0`, which is not released yet (only nightly builds reflect the change)

**Comment by smira** [comment]
It's expected then, as change only would only apply to 1.1.0.

**Comment by fozboz** [comment]
I don't really understand what you are saying. You've made a change to your nightly build, which has removed dependencies from the release repository?

I'm using the release repo which installs 1.0.1. Last week, I was able to simply run "apt install aptly" and it would also install the dependencies bzip2, xz-utils, gnupg, gpgv, libc6.

This is no longer the case. It now has no dependencies whatsoever. It _only_ installs aptly. This is expected behaviour?

**Comment by smira** [comment]
Please refer to #548 for details. Packages for releases were never updated, so whatever you encounter is not related with the change. 1.1.0 release will have updated `Depends`.
