### ISSUE TITLE
aptly prevent any operation when no space left on device

### ISSUE THREAD

**Issue by erickeller** [smira/aptly#398]
Hi Andey,

after our normal mirror update operation got interrupted by a: "no space left on device" I tried to access to  the list of snapshot and cleanup the database but for some reason aptly cannot perform any operation when the disk is full:

```
[repo@repo ~]$ df -h | grep aptly
/dev/mapper/vg_aptly-lv_aptly
                      492G  492G   17M 100% /aptly
[repo@repo ~]$ aptly mirror list
ERROR: can't open database: write /aptly/ubuntu/.aptly/db/179528.ldb: no space left on device
[repo@repo ~]$ aptly db cleanup
Loading mirrors, local repos, snapshots and published repos...
ERROR: can't open database: write /aptly/ubuntu/.aptly/db/179528.ldb: no space left on device
```

This is kind of a dead end since I cannot even try to free some space, and it's probably not a good idea to wipe some packages from the pool.

So the only possibility in this case would be to expend the volume group...
any thoughts?
## Best Regards

Eric

**Comment by richard-scott** [comment]
What File System is /aptly? 

You could try this:
```
$ tune2fs -m 0 /dev/mapper/vg_aptly-lv_aptly
```

**Comment by smira** [comment]
Well, aptly requires some free space to create log for the database (it happens while opening DB). You can move DB to some other partition and symink DB directory back.

**Comment by erickeller** [comment]
@richard-scott /dev/mapper/vg_aptly-lv_aptly on /aptly type ext4 (rw)
@smira: the symbolic link did the trick.
