### ISSUE TITLE
aptly cmd tool does not sort package versions properly

### ISSUE THREAD

**Issue by donfranio** [smira/aptly#399]
```
$ aptly repo search <repo> 'Name (= <pkg>), Version (<= 8.9.8-511)'
<pkg>_2:8.9.30-533_all
<pkg>_2:8.9.47-551_all
<pkg>_2:8.9.8-511_all
```
2:8.9.47-551_all should be "greater than" 2:8.9.8-511, right?

**Comment by smira** [comment]
It doesn't use Debian version comparison rules when sorting, actually output is not guaranteed to be sorted.

**Comment by donfranio** [comment]
Thanks for your reply.
Maybe I described my issue badly. My Problem is not the order of the output.
I think that when searching for Packages, of which the Version should be less than 8.9.8-511, then a package with version 8.9.30-533 should not be returned at all.

**Comment by smira** [comment]
Please use `$Version`, not `Version` to get correct version matching. 

https://www.aptly.info/doc/feature/query/

```
$Version has the same value as Version, but comparison operators use Debian version precedence rules
```

**Comment by donfranio** [comment]
Thanks, worked!
