### ISSUE TITLE
Publish very slow with large number of packages

### ISSUE THREAD

**Issue by mikepurvis** [smira/aptly#421]
We're using Aptly (0.9.6) to warehouse packages containing debug symbols for binaries that are evolving over time. As a result, we have a repo containing ~50k packages which vary in size from 100k to 10MB.

Doing the "publish" operation on this repo is very slow with Aptly, consuming about 10 minutes at the end of our CI builds. Most of this time is spent in the `Generating metadata files and linking package files` step, which appears to be single threaded, but mostly disk bound blocking on reads. So my questions are:

- What is actually going on during this step? It looks like [this is the code][1], but I can't tell if it's maybe unpacking each archive to access the metadata? If so, could some of this be cached in the DB to avoid having to do it all each time?
- Is this something which could be better parallelized to take advantage of multi-core VMs, eg building up the index in memory and flushing to disk at the end?
- Would it be on your radar to work on this and/or provide design guidance to an external person to work on it?

Thanks for a great tool; any thoughts greatly appreciated.

[1]: https://github.com/smira/aptly/blob/d7665119e44b156541d5d80c0cbe20ce0caceae4/deb/publish.go#L517

**Comment by mikepurvis** [comment]
@smira I may be able to offer some time to helping with this, but I would need some implementation guidance. Do you have any thoughts on how we could make the publish step faster?

**Comment by sobczyk** [comment]
Some of the heavy stuff is parsing the package contents (if you enabled it)
My repos are over 80k packages and the snapshot switch takes extremely long time.

Right now I do some testing in replacing the go code with libarchive, initial tests show it to be faster, but there is a library dependency.

My test for trusty main:
```
aptly repo show test
Name: test
Comment: 
Default Distribution: 
Default Component: main
Number of packages: 28592
```

with optimizations
```
real    235m50.366s
user    217m59.507s
sys     3m18.563s
```

without:
```
real    289m38.725s
user    285m30.790s
sys     31m22.838s
```

still very long but 50 minutes faster

**Comment by mikepurvis** [comment]
@sobczyk Do you have a fork somewhere with this modification, which I could examine?

What is the data which is coming out of the archives? Wouldn't it be faster to read it once on initial insertion, and then cache it somewhere, so we don't need to be reopening the archives again later?

**Comment by sobczyk** [comment]
It is caching on publish not on insert (repo import/add/include)
see https://github.com/smira/aptly/issues/276#issuecomment-126452927

a second publish of the same data is much faster compared to first time publish
```
real    10m46.479s
user    8m20.164s
sys     0m11.789s
```

**Comment by sobczyk** [comment]
fork with my modifications https://github.com/sobczyk/aptly

**Comment by smira** [comment]
So the easiest way is to disable package contents generation altogether. And yes, aptly caches package contents once, so it's only one-time overhead. If you don't need contents indexes, it's fine to disable them.

**Comment by mikepurvis** [comment]
The Contents index could definitely be the issue for us. Is there an existing flag or configuration option to turn that off?

**Comment by smira** [comment]
It is supported via config: https://github.com/smira/aptly/blob/master/api/publish.go#L187

`"skipContentsPublishing": true` should do the trick

**Comment by mikepurvis** [comment]
I've added the flag to my `/etc/aptly.conf` file, which now looks like this:

```
{
  "rootDir": "/var/aptly",
  "downloadConcurrency": 4,
  "downloadSpeedLimit": 0,
  "architectures": [],
  "dependencyFollowSuggests": false,
  "dependencyFollowRecommends": false,
  "dependencyFollowAllVariants": false,
  "dependencyFollowSource": false,
  "gpgDisableSign": false,
  "gpgDisableVerify": false,
  "skipContentsPublishing": true
}
```

I've verified that there's no `~/.aptly.conf`, but the publish is still very slow (on the `Generating metadata files and linking package files` step), and my `Contents-amd64.gz` file is getting a new timestamp. I also tried giving the option explicitly on the CLI, with the same results:

```
aptly publish update -skip-contents=true trusty myrepo
```

This occurs with Aptly 0.9.6 and 0.9.7.

**Comment by smira** [comment]
I believe it has no effect on commands which update published repository, only those which create it (publish repo or snapshot) should process it. #347 has details

**Comment by mikepurvis** [comment]
@smira I've tried a couple times, and it seems that I get a long `Generating metadata files and linking package files` step on initial publish, after which successive updates are quick (and there are indeed no Contents-*.gz files generated).

Thanks!
