### ISSUE TITLE
Publishing single-component snapshot fails with unable to parse command 

### ISSUE THREAD

**Issue by brandonwastaken** [smira/aptly#447]
Just sat down to try Aptly for the first time and I'm running into an issue while publishing. 

Process:
`aptly mirror create -architectures=amd64 sec-updates http://security.ubuntu.com/ubuntu trusty-security main`
`aptly mirror update sec-updates`
`aptly snapshot create sec-updates from mirror sec-updates`

Everything up to this point works fine, however when I attempt to publish, I receive an error.

`aptly publish snapshot sec-updates -label="trusty-security" -origin="Ubuntu"`
`ERROR: unable to parse command`.

I understand this is a [past problem ](https://github.com/smira/aptly/issues/316) when using multi-component snapshots, but this is a single-component. I've also tried to publish by specifying the `main` component. Is this an issue or am I using incorrect syntax? Thanks for any help/input!

**Comment by smira** [comment]
Sorry for late reply, flags should go before args, so it's as easy as:

```
aptly publish snapshot -label="trusty-security" -origin="Ubuntu"  sec-updates
```
