### ISSUE TITLE
unable to unpublished

### ISSUE THREAD

**Issue by frederikguth** [smira/aptly#452]
I try to unpublish a repo 
aptly publish drop dev/foo/bar elastic

ERROR: unable to remove: published repo with storage:prefix/distribution elastic/dev/foo/bar not found

aptly publish list
elastic/dev/foo/bar [amd64] publishes {main: [elastic_2016XXXXXXXX]: Snapshot from mirror [elastic]: https://packages.elastic.co/elasticsearch/2.x/debian/ stable}

What am I doing wrong?

**Comment by smira** [comment]
@frederikguth please swap the args, prefix comes last, it should be `aptly publish drop elastic dev/foo/bar` or something like that.
