### ISSUE TITLE
Publish to Swift container

### ISSUE THREAD

**Issue by charz** [smira/aptly#457]
I configured the aptly.conf like below,

```
   "SwiftPublishEndpoints": {
       "test": {
            "osname": "charz",
            "password": "password",
            "authurl": "http://192.168.200.21/auth/v1.0",
            "container": "repo"
        }
    }
```
When I tried to publish snapshot to swift container and I got error in below,
```
$ aptly -distribution=trusty publish snapshot sp1 swift:test:
Loading packages...
Generating metadata files and linking package files...
ERROR: unable to publish: unable to process packages: error uploading $HOME/.aptly/pool/ae/a1/python-argh_0.26.2_all.deb to Swift: http://192.168.200.21/v1/AUTH_charz:repo/: Object Not Found
```

I think the correct URL path should be like `AUTH_charz/repo/<object>`, not `AUTH_charz:repo/<object>`.

https://github.com/smira/aptly/blob/2a95e0eb1bf9e66c6a89021b195d381ff383be10/swift/public.go#L109

**Comment by charz** [comment]
Here is the patch.
https://github.com/charz/aptly/commit/977a6c1e86af4965423750c2419e984b4cf9930c

**Comment by smira** [comment]
@charz would you mind submitting PR with that?
