### ISSUE TITLE
invalid cross-device link

### ISSUE THREAD

**Issue by geek876** [smira/aptly#464]
Hi,
We see that aptly publishes its repos to a folder called `public' under aptly's home folder.

(1) Is that configurable ? i.e. Is it possible to tell aptly to publish to say `/opt/published_repos` and not to `<aptly_home>/public` ?

(2) We trying to see if we can use a shared folder (like NFS) as `public` folder so then aptly can publish to it as usual but we can then mount that folder across multiple so called `nginx heads` to serve the repos. However when we do so, we getting error while doing `aptly publish`

``` unable to process packages: link /home/aptly/pool/04/31/stackdriver-agent_5.5.2-349.xenial_amd64.deb /home/aptly/public/xenial-stackdriver/2016-12-05T14-43-12Z/pool/main/s/stackdriver-agent/stackdriver-agent_5.5.2-349.xenial_amd64.deb: invalid cross-device link```

We have `/home/aptly` as local FileSystem however, `/home/aptly/public` is NFS mounted. Aptly's home is configured to be `/home/aptly`

**Comment by smira** [comment]
aptly is using hard links between internal package pool and external published location, so both directories should stay on the same filesystem.

There's no way to change `public/` directory (it's fixed location under `rootFolder` which is configurable).

But, published repositories under `public/` directory are just files on the filesystem, so you can say use `rsync` to copy it to your NFS location, or serve it as HTTP and proxy via HTTP reverse-proxy.
