### ISSUE TITLE
Please add command to see repo content

### ISSUE THREAD

**Issue by amarao** [smira/aptly#466]
There is only search command for 'aptly repo'.

Please add some command to see all packages in the given repo.

Thanks.

**Comment by eiginn** [comment]
you can show repo content using '-with-packages'

```
aptly repo show -with-packages test 
Name: test
Comment: 
Default Distribution: xenial
Default Component: main
Number of packages: 2
Packages:
  NessusAgent_6.8.1_amd64
  ossec-hids_2.8.3-4jessie_amd64
```

**Comment by smira** [comment]
Another option is to search with filter which matches anything, `aptly repo search <some-repo> 'Name'` (`Name` query means that package name is non-empty)

**Comment by amarao** [comment]
Thank you!
