### ISSUE TITLE
make src-package not working

### ISSUE THREAD

**Issue by kshcherban** [smira/aptly#468]
Hello,

Creating debian source package for aptly from sources fails.

```
git clone https://github.com/smira/aptly/
cd aptly
make src-package
rm -rf aptly-
mkdir -p aptly-/src/github.com/smira/aptly/
cd aptly-/src/github.com/smira/ && git clone https://github.com/smira/aptly && cd aptly && git checkout v
Cloning into 'aptly'...
remote: Counting objects: 8807, done.
remote: Total 8807 (delta 0), reused 0 (delta 0), pack-reused 8807
Receiving objects: 100% (8807/8807), 5.37 MiB | 406.00 KiB/s, done.
Resolving deltas: 100% (6197/6197), done.
Checking connectivity... done.
error: pathspec 'v' did not match any file(s) known to git.
Makefile:63: recipe for target 'src-package' failed
make: *** [src-package] Error 1
```

Trying from master
```
git show HEAD
commit bfb9045fa9ff8da098d32d9520e40795280bafa7
Merge: b6327ec 1c6b174
Author: Andrey Smirnov <Smirnov.Andrey@gmail.com>
Date:   Thu Dec 8 18:26:45 2016 +0300

    Merge pull request #465 from SHyx0rmZ/allow-empty-repo-edits-in-api
    
    Allow comment and defaults to be empty when editing a repo through the API
```

Seems that happens because variable `VERSION` is not set by default, but it can chosen from latest tag, i guess.

Also seems that tar uses incorrect option
```
tar cyf aptly-0.9.7-src.tar.bz2 aptly-0.9.7
tar: invalid option -- 'y'
Try 'tar --help' or 'tar --usage' for more information.
Makefile:63: recipe for target 'src-package' failed
```

**Comment by smira** [comment]
`make src-package` was supposed to be a simple way to provide tree with vendored deps for Debian packaging. Yes, `VERSION` should be set manually. And `y` is `bz2` for `tar` (but depends on `tar` origins).

**Comment by kshcherban** [comment]
I thought that `make src-package` will produce Debian source package. `-j, --bzip2` is for Debian tar.
Feel free to close it if you are not going to provide open sourced debianization for aptly.

**Comment by smira** [comment]
I'm not sure what do you mean by "open sourced"?

I don't maintain aptly Debian package (https://packages.debian.org/jessie/aptly). 

Packages which are built with `make package` go straight to binary with `fpm`.
