### ISSUE TITLE
Use stable sort for files in InRelease

### ISSUE THREAD

**Issue by Daniel15** [smira/aptly#476]
## Detailed Description
The file hashes in InRelease don't seem to be sorted, resulting in the `InRelease` file unnecessarily changing even when the file hashes themselves don't change. As an example of a change like this:

![](http://ss.dan.cx/2017/01/chrome_16-17.44.45.png)

In the example above,  `main/binary-i386/Packages` has remained 17215 bytes with a hash of `04aceea962e6ccb19932037ed24626b4`, however its position in the file listing has changed from line 24 in the old version to line 13 in the new one.

Perhaps these should be sorted by file name to avoid this happening.

## Context
I have an Aptly repo in a Git repo (long story short, we're temporarily using GitHub Pages to host the repo) so I'd like to avoid unnecessary changes to the metadata as they make the Git history a bit confusing.

## Your Environment
Development environment is Windows 10 + Windows Subsystem for Linux ("Bash for Windows"), Ubuntu 14.04, Aptly 0.9.7
Production environment is Debian Testing, Aptly 0.9.7

**Comment by smira** [comment]
Should be available as `aptly_0.9.8~dev+45+g8df6457` in nigthly

**Comment by Daniel15** [comment]
Thank you! 😃
