### ISSUE TITLE
Status Request Entity Too Large

### ISSUE THREAD

**Issue by ct-wn** [smira/aptly#483]
When using the API to upload files we are getting the response "The requested URL returned error: 413 Request Entity Too Large". The file is 2736M.

How can the size limit be adjusted?

## Detailed Description
Provide a configuration to increase or remove the limit.

## Context
This is completely breaking our usage of aptly. If this can't be fixed/patched in a very short amount of time we will have to abandon aptly.

## Your Environment
Ubuntu 16.04.1 LTS

**Comment by ct-wn** [comment]
Problem was actually in nginx

**Comment by monsdar** [comment]
Any directions on how to fix this would be helpful. Running into the same with running the docker container of urpylka/aptly:1.5.3

**Comment by monsdar** [comment]
As mentioned in the [README.md](https://github.com/urpylka/docker-aptly/blob/master/docs/README.md) in case of `urpylka/aptly:1.5.3` it's possible to set `NGINX_CLIENT_MAX_BODY_SIZE='100M'` to solve that issue.

**Comment by tomerschwartz24** [comment]
NGINX_CLIENT_MAX_BODY_SIZE is  already set for me  (urpylka/aptly:1.5.3) and it still happens
