### ISSUE TITLE
publish snapshot command says to separate components with comma, but space works instead

### ISSUE THREAD

**Issue by mjb2kmn** [smira/aptly#489]
When publishing a snapshot with multiple components I get "ERROR: unable to parse command".
I tried a space instead of a comma and it appears to have worked.

This command:
```
aptly publish snapshot -distribution=trusty-final-170213 -component="main,restricted" trusty-final-170213
```
fails and shows this under Options:
```
-component="": component name to publish (for multi-component publishing, separate components with commas)
```

This command: 
```
aptly publish snapshot -distribution="trusty-final-170213" -component="main restricted" trusty-final-170213
```

works and correctly shows this:
```
Now you can add following line to apt sources:
  deb http://your-server/ trusty-final-170213 main restricted
```

It looks like it's splitting on ",", so what could be the issue here?

https://github.com/smira/aptly/blob/v0.9.7/cmd/publish_snapshot.go#L16

aptly version: 0.9.7 on Ubuntu 14.04

**Comment by mjb2kmn** [comment]
My mistake, it's working. It's publishing as a component "main restricted".
There must be something wrong with my command syntax that I'm not seeing.

**Comment by smira** [comment]
@mjb2kmn number of snapshots should match number of components to publish, so that each components comes from its own snapshot

**Comment by mjb2kmn** [comment]
Thank you for the clarification. 
After re-reading the doc on [multi-component repository publishing](https://www.aptly.info/doc/feature/multi-component/), I now understand that I don't actually need multiple components.
