### ISSUE TITLE
RFE: aptly repo restore snapshot

### ISSUE THREAD

**Issue by fewaffles** [smira/aptly#496]
Request For Enhancement:
To better facilitate retroactive "branching", it is desirable to be able to create a 'repo' from an existing 'snapshot'.

## Detailed Description

The "repo import" and "repo copy" commands already exist to populate a 'repo' from an existing 'mirror' or 'repo' respectively.  But AFAICT there is no mechanism for populating a 'repo' from an existing 'snapshot'.

## Context

There doesn't appear to be any mechanism for manipulating the state of a 'repo' to match the state of a previous 'snapshot'.  Snapshots create the "backup", but there is no way to "restore" from that "backup".

If we wish to create a 'repo' for branching our project at a specific point in the past, (eg: Snapshot N-1, before a big feature was introduced) there exists no mechanism for doing so.

If the 'repo' were manipulated into a state that is no longer desirable (eg: new member of the team, or actions taken by mistake) the existing snapshots could currently be used to begin a manual recovery process of some sort.  But creating a new 'repo' and restoring an existing 'snapshot' to the 'repo' would be much simpler.

**Comment by akoudal** [comment]
👍

**Comment by smira** [comment]
👍  on that

that feature is available in the API (repo could be built from package refs directly), while not available in the CLI

the easiest way would be probably to "create" repo from snapshot, so that contents are populated from the snapshot, and existing `aptly repo` commands could be used to move/copy stuff around if additional processing is required

**Comment by fewaffles** [comment]
Thanks for the info about the APIs.  I hadn't focused much on the APIs because I was under the impression that they were a partial subset of the available CLI commands.

Based on the docs, it looks like I should be able to collect the list of packages in a given snapshot using the API documented here:
   https://www.aptly.info/doc/api/snapshots/#show-packages-search

Then I should be able to populate a given repo using the previous output as input to the API documented here:
   https://www.aptly.info/doc/api/repos/#add-packages-by-key

We've not had a need to use the aptly APIs to date.  If our aptly instance is on NFS and we end up running "aptly api serve" concurrently from multiple NFS clients, is all of the appropriate locking in place to avoid any problems?

**Comment by smira** [comment]
I wouldn't recommend running aptly concurrently from network file system. aptly is using file locks to avoid concurrent access to database, so if file locks are configured, aptly won't start 2nd instance if 1st instance is running.

For API mode, you can have 1 instance running and have all the users attached to it?
