### ISSUE TITLE
aptly graph doesn't open image

### ISSUE THREAD

**Issue by cobra** [smira/aptly#500]
`aptly graph` is supposed to open the generated image in a viewer, but nothing happens.
The image gets rendered properly, but aptly calls `/bin/open` on it, which is a symlink to `openvt` from the kbd package. I don't think that this is the intended command and suggest using xdg-util's `xdg-open` instead which will open the file in the user's preferred image viewer.
I'm a bit clueless how this got broken, are there setups where `open` is working as intended?

strace snippet:
````
write(1, "Rendered to png file: /tmp/aptly"..., 74Rendered to png file: /tmp/aptly-graph849633576.png, trying to open it...
) = 74
stat("/home/<user>/bin/open", 0xc8201849f8) = -1 ENOENT (No such file or directory)
stat("/usr/local/bin/open", 0xc820184ac8) = -1 ENOENT (No such file or directory)
stat("/usr/bin/open", 0xc820184b98)     = -1 ENOENT (No such file or directory)
stat("/bin/open", {st_mode=S_IFREG|0755, st_size=19400, ...}) = 0
````
````
$ ls -l /bin/open
lrwxrwxrwx 1 root root 6 Jan  5  2016 /bin/open -> openvt
$ dpkg -S /bin/open
kbd: /bin/open
````

version: aptly 0.9.7 from debian 9 (currently testing)

**Comment by smira** [comment]
good point, `open` works fine on Mac though. I wonder what is the best way to be compatible with as many OS and distributions as possbile

Any suggestions are welcome

Something really close: https://github.com/google/pprof/blob/master/internal/driver/commands.go#L400

**Comment by cobra** [comment]
A compile time option might be the most elegant solution, but a config file option would also suffice. The config file option could also be handy for users not wanting to use their default application.

Somewhat automagical alternative: look for `xdg-open` and use that, if found. Else, check if `open` is not a symlink to `openvt` (aptly is quite debian-centric, so that symlink is not a rare edge case and worth the check, imho) and then use `open`.

The last resort would be a tiny downstream patch changing that one offending line, but I had hoped to avoid this to ease future maintenance. On the other hand, such a patch might still make it into stretch before release.

**Comment by smira** [comment]
Something we could try to follow here: https://github.com/google/pprof/blob/master/internal/driver/commands.go#L336

**Comment by cobra** [comment]
runtime.GOOS sounds really useful for things like this. I'd opt for doing the same - if darwin use open, else try xdg-open, if that fails, fail the same way as now (until someone comes up with the next useful special case).
What are your thoughts about stretch? Release a new version and try to get that in or rather fix this single issue with a patch?

**Comment by smira** [comment]
I'm open to patching that particular issue in stretch. I'll try to prepare PR today and we'll see how it goes. Next aptly release doesn't have a fixed date yet.

**Comment by cobra** [comment]
Any news so far? I created (and tested, ofc) a trivial `open`→`xdg-open` quilt patch and will submit that to the Debian bug tracker unless there's a different preferred solution.

**Comment by smira** [comment]
Please feel free to proceed with the patch, I'm digging into another issue right now

**Comment by cobra** [comment]
Filed as Debian bug [#858387](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858387).
btw: thank you for developing aptly, I really like it.

**Comment by smira** [comment]
Available in nightly since `aptly_0.9.8~dev+117+g92c844b`
