### ISSUE TITLE
Add COPY/MOVE packages between repos via API

### ISSUE THREAD

**Issue by lesykm** [smira/aptly#501]
Add more endpoints to API fro management of packages

## Context
It would be very convenient for build system/web tool/whatever to move/copy packages between repositories, for example move from `unstable` to `stable`

## Possible Implementation
Just add already implemeted commands...

## Your Environment
Components: Unstable/Testing/Stable

**Comment by lesykm** [comment]
Did not see, it is already described:
https://www.aptly.info/doc/api/

**Comment by smira** [comment]
yep, aptly API is really flexible, you can get package refs from multiple sources, combine them and push as repo/snapshot/... 

aptly CLI doesn't offer such generic interface
