### ISSUE TITLE
Minor: Invoking gpg2 with --no-use-agent outputs a warning

### ISSUE THREAD

**Issue by jdelic** [smira/aptly#514]
On Debian Stretch RC2 with 
```
$ gpg --version
gpg (GnuPG) 2.1.18
...
```

invoking `aptly publish repo ...`

leads to
```
gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
```

**Comment by smira** [comment]
I've got very promising result so far with Go internal `openpgp` package, looking towards that as replacement for invoking `gpg` command line utility.

I don't feel supporting wild mix of all the `gpg` versions makes any sense.
