### ISSUE TITLE
Add a parameter to allow overriding of the gpg binary

### ISSUE THREAD

**Issue by jdelic** [smira/aptly#515]
In Debian Stretch gpg2 replaces `/usr/bin/gpg`. gpg2 requires gpg-agent and uses a pinentry system that I can't get to work with `-passphrase`, `-passphrase-file` and `-batch`. It always shows a pinentry dialog. While gpg1 is still available as the Debian package `gpgv1`, aptly can't invoke it. Replacing `/usr/bin/gpg` with gpg1 seems to break `apt`.

Pragmatic solution: Add a command-line parameter to `aptly publish` that allows the user to override the used gpg binary.

**Comment by smira** [comment]
Good point... should we try to use environment variables or config file?

I think command line params might be too much work to type every time

**Comment by jdelic** [comment]
> Good point... should we try to use environment variables or config file?
> I think command line params might be too much work to type every time

Good question...
I would be +1 on extending the config file, especially since "kind-of-related #423" is another case where extending it would be very useful.
