### ISSUE TITLE
0.9.7 regression? -force-replace doesn't work anymore?

### ISSUE THREAD

**Issue by travisgriggs** [smira/aptly#518]
I'm trying to determine if -force-replace has regressed...

## Detailed Description

I used to use a command like

    aptly repo add -force-replace -remove-files twigpilot-nic pilot-yubikeys_0.0.5_armhf.deb

To upgrade package in my repository from 0.0.4 to 0.0.5. It would tell me both that it had added the new version AND removed the older version. I was running 0.9.5 or 0.9.6, I'm not sure. Now when I do the same with 0.9.7, it does not remove the older version. I have to use a `repo show -with-packages` and then a `package remove` to get it removed. Was the old behavior a mis-feature? Or has the newer version regressed?

## Your Environment

0.9.7 (fetched straight from the aptly repository) running on Ubuntu 16.04 LTS (Xenial Xerus)

**Comment by smira** [comment]
https://www.aptly.info/doc/aptly/repo/add/

`-force-replace` should have never removed different version of the same package, it is supposed to remove only same name-version-arch packages (which are conflicting with each other)

**Comment by smira** [comment]
https://github.com/smira/aptly/blob/master/deb/import.go#L173

I don't think it had changes recently

**Comment by travisgriggs** [comment]
OK, I assume protocol is for me to close the issue then... Is there a different sequence that will automatically just retain the latest version of a package then? I'm not interested in keeping older versions around in our own repository. Or do I just need to do some tooling that does the add, and then queries for older versions and then removes them?

**Comment by smira** [comment]
I have one feature in the work for a long time which would allow to query slice of package versions, so that you could easily say `remove all but the N latest versions`, but it's not there yet. It could be still done today with some tooling around `aptly ... search` and `aptly ... remove`, but not as straightforward as I want it to be.

**Comment by travisgriggs** [comment]
Cool. Look forward to that. Thanks!
