### ISSUE TITLE
filter-with-deps does not include "pre-depends"

### ISSUE THREAD

**Issue by tpdownes** [smira/aptly#524]
`Depends` is not the only absolute dependency defined by debian control files. `Pre-Depends` requires that another package be installed prior to the other package even attempting installation. `filter-with-deps` should get both but only gets `Depends`.

~~It would also be useful for a separate command `filter-with-recs` as the default behavior of `apt-get` is to install `Recommended` packages.~~ (WOOPS, it exists!)

**Comment by smira** [comment]
@tpdownes just double-checked, and aptly should always include `Pre-Depends`. Do you have any example that it doesn't do that?

**Comment by tpdownes** [comment]
I found that
```
aptly mirror create -filter="zfs-dkms" -architectures="amd64" -filter-with-deps zfs-jessie http://my.mirror/debian jessie-backports main contrib
```
Was not bringing in `spl-dkms` unless I specifically filtered for `zfs-dkms | spl-dkms`. This is running with 0.9.7 from your debian repo.
