### ISSUE TITLE
Cannot update s3 published repo if created from snapshot

### ISSUE THREAD

**Issue by cpoole** [smira/aptly#525]
When attempting to publish a snapshot to s3 it appears only one snapshot can be published to a specific path:

I create a snapshot of a mirror and publish it to s3 using `aptly publish snapshot some-snap-name s3:main:prefix/` 

Then a week later after testing we want to update the path in the bucket to contain the latest content from the mirror

I create a new snapshot after running a mirror update and attempt to publish this:
`aptly publish snapshot new-snap-name s3:main:prefix/`

I am greeted with the following:
```ERROR: prefix/distribution already used by another published repo: s3:main:1.3.0-xenial-main/xenial [amd64] publishes {main: [snapshot-1490159920]: Snapshot from mirror [xenial-main]: http://us.archive.ubuntu.com/ubuntu/ xenial}```

If I run 
`aptly publish update snapshot new-snap-name s3:main:prefix/`
I get the error saying this operation is not possible. the docs seems to suggest the `publish update` command is only for local repositories. 

## Context

At our organization we have a need to host internal mirrors of the public ubuntu repos but with a few packages excluded or held back.

I'd like a flow like this:

1. Test on an internally available repository (published locally using aptly).
2. Testing finishes so I snapshot the local repository
3. publish this snapshot to a specific path in s3
4. repeat 1 & 2 and publish new snapshot to the _same_ path in s3

This is useful because it means we never have to change the path in `/etc/apt/sources.list` on our machines in order to get the contents of the newly approved "snapshot".

Currently I end just making changes directly to the local repository and then running aptly publish update. But I lose the ability to have snapshots

**Comment by cpoole** [comment]
Also this could totally be possible but I havent figured it yet. I've only been playing with aptly for two days.

**Comment by smira** [comment]
@cpoole you need `aptly publish switch` (https://www.aptly.info/doc/aptly/publish/switch/)

**Comment by cpoole** [comment]
beautiful! thanks @smira sorry for the spam
