### ISSUE TITLE
Support for Acquire-by-hash feature of APT 1.2.0

### ISSUE THREAD

**Issue by erickeller** [smira/aptly#536]
It could be that some racing condition around an apt checksum missmatch ocurrs when `apt-get update` and aptly generates a new Release file.

## Detailed Description
More information from package cloud.io
blog.packagecloud.io/eng/2016/09/27/fixing-apt-hash-sum-mismatch-consistent-apt-repositories/

Thanks @tuxtimo for pointing to this reference

Cheers

**Comment by smira** [comment]
Thanks for the link, that should be really interesting feature, but not very trivial to implement (as we need to generate those links by hash and clean them up eventually).

**Comment by neolynx** [comment]
Hello!
More info on that topic: http://www.chiark.greenend.org.uk/~cjwatson/blog/no-more-hash-sum-mismatch-errors.html

I did a first implementation, please let me know what you think about it. Works well with ubuntu yakkety. I did not look into mirroring repos with Acquire-By-Hash yet.

**Comment by smira** [comment]
This looks great, I'm looking forward towards it!
