### ISSUE TITLE
aptly repo import doesnt respect "$Source (src_pkg_name)"

### ISSUE THREAD

**Issue by sandrotosi** [smira/aptly#537]
Hello,
with aptly version 1.0.0 (it might be the case even for previous version, IIRC this was happening also on 0.9.7) we noticed that

```aptly repo import jessie-backports-main INTERNAL_REPO "$Source (src_package_name)```

(with `jessie-backports-main` being a mirror of jessie backports main suite, `INTERNAL_REPO` and internal repository where we want to import the packages and `src_package_name` the source package we want to import) doesnt import all the binary packages (note: we dont think it's related to the `jessie-backports-main` mirror, this is just an example).

for example let's take python-cryptography, https://tracker.debian.org/pkg/python-cryptography: the source package `python-cryptography` generates 3 binary packages (as you can see in the binaries box in the bottom left of the PTS page), but if you import it:

```
aptly repo import jessie-backports-main INTERNAL_REPO "$Source (python-cryptography)"
Loading packages...
[o] python-cryptography_1.3.4-1~bpo8+2_amd64 imported
```

so only the binary package with name equals to the source package is imported, the py3k and -doc packages are left out.

is there a different query we should use or is there something else going on?

thanks

**Comment by smira** [comment]
@sandrotosi first of all, this kind of query certainly works:

```
$ aptly mirror search j-c '$Source (freexl)'
libfreexl1-dbg_1.0.0g-1+deb8u3_amd64
libfreexl-dev_1.0.0g-1+deb8u3_amd64
libfreexl1_1.0.0g-1+deb8u3_amd64
```

Looking at the line you posted, I wonder if double quotes make your shell evaluate `$Source` as shell variable most probably rendering it as empty value.

**Comment by sandrotosi** [comment]
holy smokes, you're right! it's a classi case of double-quote vs single-quote syndrome:

```
aptly repo import jessie-backports-main TEST '$Source (python-cryptography) | python-cryptography {source}'
Loading packages...
[o] python-cryptography_1.3.4-1~bpo8+2_amd64 imported
[o] python-cryptography-doc_1.3.4-1~bpo8+2_all imported
[o] python3-cryptography_1.3.4-1~bpo8+2_amd64 imported
[o] python-cryptography_1.3.4-1~bpo8+2_source imported
```

so it correctly imported the 3 binary packages and the source pkgs.

sorry for the noise, there's nothing wrong here!
