### ISSUE TITLE
Error restricting IAM permissions to a subdirectory of an s3 bucket

### ISSUE THREAD

**Issue by liliakai** [smira/aptly#540]
My repository is located in a subdirectory of my bucket. I can publish snapshots but cannot switch between them.

```
> aptly publish switch -config=.aptly.conf xenial s3:some-bucket-name: mySnapshot
```
The above eventually fails with
```
ERROR: unable to publish: unable to rename: error deleting dists/xenial/main/Contents-amd64.tmp.gz from S3: us-west-1:some-bucket-name/prefix/prefix: AccessDenied: Access Denied
```
I don't think it's an aws permissions problem because I am able to delete the object using aws-cli:
```
> aws s3 rm s3://some-bucket-name/prefix/prefix/dists/xenial/main/Contents-amd64.tmp.gz
delete: s3://some-bucket-name/prefix/prefix/dists/xenial/main/Contents-amd64.tmp.gz
```
Could this be a bug with how aptly handles the prefix config? Here's my .aptly.conf:

```
{
  "S3PublishEndpoints": {
    "endpoint-name": {
      "region": "us-west-1",
      "bucket": "some-bucket-name",
      "prefix": "prefix/prefix",
      "acl": "public-read",
      "plusWorkaround": false,
      "disableMultiDel": false
    }
  }
}
```

## Your Environment
OSX
aptly version: 0.9.7

**Comment by liliakai** [comment]
Looks like this is permissions-related afterall. If I apply the IAM policy found [here](https://www.aptly.info/doc/feature/s3/) to the top-level bucket arn, everything works:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowDirectoryActions",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:ListObjects",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::some-bucket-name",
                "arn:aws:s3:::some-bucket-name/*"
            ]
        }
    ]
}
```        

However, if I scope that policy's `Resources` to the resource arn with the prefix, I get the ERROR shown above.
```
            "Resource": [
                "arn:aws:s3:::some-bucket-name/prefix",
                "arn:aws:s3:::some-bucket-name/prefix/*"
            ]
```
Is it possible to limit the IAM policy to a subdirectory of the bucket and still publish/switch snapshots with aptly?

**Comment by liliakai** [comment]
By trial and error, I found that the following permissions must be set on the bucket root or switching will fail. Also ListBucket is required on the root for initially publishing the snapshot to s3. This is unfortunate, if I do not want to grant (e.g.) DeleteObject across the whole bucket, because I only want to grant write access to the prefix subdirectory.

```
            "Action": [
                "s3:ListBucket",
                "s3:ListObjects",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::some-bucket-name",
                "arn:aws:s3:::some-bucket-name/*"
            ]
```

**Comment by smira** [comment]
I never tried setting polices on prefixes, but I think it's related to some policy problem.

You can try setting `debug` to `true` in aptly S3 endpoint settings to see the requests going out. Looking at aptly source code, I see that all the operations have correct prefix scope.

**Comment by smira** [comment]
Closing on inactivity, please feel free to reopen.
