### ISSUE TITLE
how to backup

### ISSUE THREAD

**Issue by scifire91** [smira/aptly#542]
Whats the right way to backup aptly?

i didn´t found a how to what is the right way to backup aptly and restore it correctly? 
Is it just backing up the aptly folder, aptly.conf and apache conf? 

For recover i found https://www.aptly.info/doc/aptly/db/recover/ 

Thanks for help

**Comment by smira** [comment]
First of all, `aptly db recover` does completely different thing - it tries to recover LevelDB after the crash. 

To do proper aptly backup, it's enough to backup aptly root dir (`~/.aptly`) and config (`~/.aptly.conf`). Backup tool should be smart enough to detect hardlinks between `pool/` and `public/` directories contents.

**Comment by scifire91** [comment]
Okay thanks.

**Comment by aol-nnov** [comment]
sorry to bump a closed bug, but it's related to my problem.

@smira I've made an LVM snapshot of running aptly instance. After that I've discovered that files in `db` directory are empty (seems, it's an in-memory db and I know nothing about leveldb)

After that there was a power outage and operational instance of aptly was lost.

After rolling that backup I've ended up with consistent pool but completely corrupted database. Any chance to recover from such a situation and any advices concerned LVM snapshots backup strategy, please??

**Comment by aol-nnov** [comment]
@smira [here](https://stackoverflow.com/a/29497281) it is stated that consistent snapshot (using LVM, Btrfs, or other tools) of the data on disk should be a safe backup.

But why it is not the case for aptly?

Also, is it the only way to recover in my case by recreating repos manually and then iteratively calling `aptly repo add` from my published repos that survived the crash for each aptly repo?

**Comment by smira** [comment]
@aol-nnov aptly is using goleveldb which yet another implementation of LevelDB. DB files are written only once, so I have no idea how they ended up being empty. If consistent snapshot is taken, only changes which are not written disk (whatever aptly is working on at the moment) might be lost. Older data should be on disk and should never be affected.

If the DB is lost, unfortunately there's no good way to restore except for trying to re-add the packages back like you described.

**Comment by aol-nnov** [comment]
Sad, sad news.. 

Despite I've managed to restore database by re-adding packages, I'm now hesitant about aptly. I'm using it almost two years in our CI pipeline and it's still a bumpy road... gpg woes, corrupted databases, broken links in the internal pool and all other sorts of "joy".

Quite obvious, aptly has nice features like snapshots, publication and such, but yet, it does not "just work". It's been a year since I put aptly into the production pipeline and now I can't, literarly, sleep well because of that...

Btw, is there any way to flush aptly db data on disk before making a snapshot?

**Comment by smira** [comment]
I don't know which way you run aptly, but basically it flushes each time it completes handling some operation.

**Comment by aol-nnov** [comment]
I'm running it inside docker container via `aptly api serve`. Persistent docker volumes are backed by thinly provisioned lvm. 

Repos are manipulated via api mainly.

**Comment by smira** [comment]
I wonder if that is related to the DB being never closed.

I think `aptly api serve -no-lock` might be much more crash-resistant

**Comment by aol-nnov** [comment]
That's right, I'm using it with -no-lock. Sorry, I didn't mention that.
