### ISSUE TITLE
Ability to skip prefix cleanup on publish operations

### ISSUE THREAD

**Issue by cavedon** [smira/aptly#570]
I am publishing multiple large snapshot (e.g. Ubuntu security snapshots) under the same prefix.

I have noticed that aptly became very slow when switching and dropping publishes in that prefix, and the slow part is the "Cleaning up prefix "[...]" components main...".

If I am doing multiple switches or drops, that will take a lot of time and would not re really needed.

I am suggesting adding a -skip-cleanup component to the publish command, that would skip cleanup on all publish operations, and to add the ability to invoke the cleanup of a prefix on demand (aptly prefix cleanup).

Thanks!

**Comment by smira** [comment]
Could you please provide more details, are you publishing to local file system? aptly is trying to clean up `pool/` directory from package files which are not required anymore (which is non-trivial, as it has to check all the distributions published under this prefix). I wonder which part takes more time here (walking file system or loading package lists).

**Comment by cavedon** [comment]
> are you publishing to local file system?

yes

>  I wonder which part takes more time here (walking file system or loading package lists).

I looked at the process via htop and iotop, and it bounded by user-space CPU activity, and very little IO.
I suspect that the problem is that there are almost 200 published snapshot that share that same pool. Let me know what other info/test may help.

**Comment by smira** [comment]
I think we could allow aptly to skip cleanup if request. There's no problem in that except for the fact that we're going to end up with some package files sitting there forever even if they're not referenced anymore. But once publish is run with cleanup enabled, it will take care of those files.

**Comment by cavedon** [comment]
> I think we could allow aptly to skip cleanup if requested. There's no problem in that except for the fact that we're going to end up with some package files sitting there forever even if they're not referenced anymore. But once publish is run with cleanup enabled, it will take care of those files.

yes, that would be helpful when switching or dropping many published snapshots at once. Thanks!
