### ISSUE TITLE
Adding new distribution to an existing repo with its default distribution results in inheritance between the two distributions

### ISSUE THREAD

**Issue by jonathanmarsaud** [smira/aptly#576]
Hi,

When you add a new distribution (in this example, called **zesty**) to an existing repo which already contains a previous (which is the default distribution also) distribution (called **jessie** for example), all packages of **jessie** are available through the **zesty** distributions.

You can verify that by looking at `Packages/Packages.gz/Packages.bz2` of the `dists/zesty/binary-amd64`.

In simple words, it seems that zesty inherits all packages of jessie.
Is it the normal behaviour or a bug?
If it's normal, how can I disable this?

Regards,

**Comment by smira** [comment]
Jonathan, could you please show simple way to reproduce that?

aptly doesn't have pretty much concept of distribution, so I'm confused how you can distribution to existing repo.

Published repository in aptly have distribution (basically folder name), but you can't add distribution there. 

Local repositories/snapshots don't have distribution associated.

**Comment by jonathanmarsaud** [comment]
First step, adding a package to the default distribution of the created repo:
1) `aptly repo add create -architectures="amd64" -comment="Private Repository" -component="main" -distribution="jessie" privrepo`
2) `aptly repo add privrepo /data/some.deb`
3) `aptly snapshot create privrepo_snapshot from repo privrepo`
4) `aptly publish snapshot -distribution=jessie privrepo_snapshot privrepo`

Second step, adding another package to another distribution (!= jessie):
5) `aptly repo add privrepo /data/some_another.deb`
6) `aptly snapshot create privrepo_snapshot_zesty from repo privrepo`
7) `aptly publish switch zesty privrepo privrepo_snapshot_zesty`

What I obtained:
- `Packages.gz` contains *some.deb* for *jessie* (default distribution of the repo) ;
- `Packages.gz` contains *some.deb* PLUS *some_another.deb* for *zesty* (the second distribution of the repo).

What I expected:
- *some.deb* only available for `jessie` ;
- *some_another.deb* only available for `zesty`.

If this is the intended behaviour, do I have any other way to do this?

Regards,

**Comment by smira** [comment]
@jonathanmarsaud `distribution` in aptly is just a hint for the name of the published repository, it doesn't affect anything else. So it's more of way to skip specifying distribution while publishing. When you add another package to `privrepo`, it contains 2 packages and all of them would be published.

So if you want to support two distributions, you need 2 packages sources (most probably 2 local repos in your case).

**Comment by jonathanmarsaud** [comment]
@smira Thanks for your answer!

So it's not possible to have the common behaviour of most of the public repo:
`deb http://<domain>/software/ <jessie|stretch> main contrib non-free`

I must do something like:
`deb http://<domain>/software-jessie/ jessie main contrib non-free`
`deb http://<domain>/software-stretch/ stretch main contrib non-free`
which is not the common way and a bit "repeating".

Do you think that I can transform this bug as a "wishfeature" of it's not interesting?

**Comment by smira** [comment]
@jonathanmarsaud you still can do like you proposed, it's the way official Debian repos are laid out. You need to make sure though that packages for jessie and stretch are either identical between distributions or have different versions if they differ (that's restriction of directory layout).

So imagine you have two local repos, repo-jessie and repo-stretch filled with packages for jessie/stretch. 

You take snapshots, snap-jessie and snap-stretch and publish them as two different distributions:

1. aptly publish snapshot -distribution=jessie snap-jessie
2. aptly publish snapshot -distribution=stretch snap-stretch

As they're going to share same published pool/ directory, restriction on packages (which I mentioned above) applies here. If using two different prefixes, there's no restriction on packages at all. But having different version for different distributions is a good practice.
