### ISSUE TITLE
Allow aptly to add a package to a repo from a location in s3

### ISSUE THREAD

**Issue by cpoole** [smira/aptly#578]
Currently `aptly repo add` only allows addition of a local debian file. Since many places are already archiving their build artifacts to s3 straight from their CI tooling it would be beneficial for aptly to add to a repo directly from an s3 link.

## Detailed Description

The aptly add functionality should be able to take an s3 location and use the aws key pair given in the aptly config to fetch a file from s3 and then add that file to a local repo

## Context

Streamlines getting a package from s3 into your repo. Reduces complexity and stops us from needing to download the package and then add it (two copies of the package)

## Possible Implementation

would be rather simple in the add code to detect if the path starts with s3 protocol and use the aws go sdk to download first to a /tmp location and then add from there, and finally delete the /tmp file

## Your Environment

I'll get a PR submitted for this if the community is interested

**Comment by smira** [comment]
aptly anyway needs to download first to temp location, followed by adding to the repo (as it needs to parse package details). 

So is it easier to download using say AWS CLI, followed by `aptly repo add` on temp path?

**Comment by cpoole** [comment]
It's not overly complicated but I thought it would be easier if aptly could just handle this natively. That way your CI tooling only needs to issue a single easy to read command. 

If you think this functionality does not fit into aptly ill close this

**Comment by smira** [comment]
I'm just afraid that it my never end, like pulling from S3, over SSH, FTP, HTTP, Swift, ... :)

You see my point here, and each protocol requires decent amount of work to work correctly with all the providers.  It shouldn't be hard to implement just S3, but it might come to non-AWS S3 implementations which require custom endpoints, region names, hostname addressing scheme and so on.

Basically we would need to support almost same amount of options as we do for publishing to S3.

**Comment by cpoole** [comment]
ok, understood. I'll close this out
