### ISSUE TITLE
Can't delete s3 repo

### ISSUE THREAD

**Issue by bentech** [smira/aptly#584]
## Detailed Description

I published my repo with "aptly publish snapshot -force-overwrite=true -component=main -distribution=xenial main1.0 s3:repo:"

My graph is as follows
https://cl.ly/2I0j3U3d3B3w

I've tried:

  aptly publish drop .xenial
  aptly publish drop ./xenial
  aptly publish drop s3:repo ./xenial
  aptly publish drop s3:repo ./xenial
  aptly publish drop main ./xenial
  aptly publish drop xenial-main
  aptly publish drop aptly publish list -raw
  aptly publish drop xenial
  aptly publish drop s3:repo:. xenial
  aptly publish drop s3:repo:.xenial
  aptly publish drop s3:repo:./xenial
  aptly publish drop main
  aptly publish drop s3:repo:./xenial
  aptly publish drop s3:repo:xenial
  aptly publish drop s3:repo:./xenial
  aptly publish drop .:./xenial
  aptly publish drop s3:repo:./xenial

## Context

I am currently deleting my repo and starting fresh
Published repositories:
  * s3:repo:./xenial [armhf] publishes {main: [main1.0]: Snapshot from local repo [main]}

## Your Environment

aptly version: 1.0.1
macOS

**Comment by lazyfrosch** [comment]
Not using s3, but I believe the correct syntax would be

    aptly publish drop xenial s3:repo

Similar to my environment, where it would be:

   aptly publish drop local-xenial ubuntu

While the repo has been published to the `.../public/ubuntu/` directory as dist `local-xenial`
