### ISSUE TITLE
Cannot add new packages due to 'file already exists and is different' error

### ISSUE THREAD

**Issue by law** [smira/aptly#586]
Aptly refuses to publish a snapshot with the following error message: 

unable to publish: unable to process packages: error linking file to /var/aptly/public/pool/main/m/mycorp-api/mycorp-api_0.2.16_all.deb: file already exists and is different","meta":"Operation aborted"}]

however the file we're trying to upload is something like 'mycorp-api_YYYYMMDDHHMM_all.deb', which is not pre-existing in the repo at the time of upload.  Further, all files are uploaded/imported with "forceReplace: 1", presuming it should prevent this exact problem - perhaps I'm mistaken on this?

## Detailed Description
We currently have three repos that are independently managed from each other (i.e. we don't promote snapshots from -dev to -staging to -prod, we rely on CI to manage that for us), "mycorp-dev", "mycorp-staging", and "mycorp-prod".  Our CI server does the needful for a given build-ref, creates a package via fpm (-dev gets a version number like mycorp-api-YYYYMMDDHHMM, -staging and -prod get semver-compatable version numbers like mycorp-api-X.Y.Z), and uses the following shell script wrapper around curl to upload the .deb to the appropriate repository:
 
https://paste.fedoraproject.org/paste/XsbvgmDR4nUFEl~dLtAmTQ

the real meat of the script happens at line 60, where curl proceeds to upload/import the .deb, removes the previous active snapshot, then creates/publishes the new snapshot with the latest .deb.  The error message fires at the Publish step, line 70.  

## Context
This is preventing us from deploying to all of our environments.  

## Your Environment
This is Aptly v 1.0.1 on Ubuntu Xenial.  /etc/aptly.conf is defined as:
https://paste.fedoraproject.org/paste/HR2iQTtZp~RavpF2-b5uYg

**Comment by lazyfrosch** [comment]
Aptly is storing files internally by package name + version.

This is the same on Debian / Ubuntu mirrors, (with the pool), a file has to be unique versioned to be correct.

Debian was build around moving releases, where backports happen with a special version.

We build release builds where we publish all packages like `1.0.0-1`, but add a `~jessie` suffix to every build.

**Comment by lazyfrosch** [comment]
Our build system does this automatically:

```
export DEBFULLNAME="Our Build System"
export DEBEMAIL="info@example.com"

debian_version=`dpkg-parsechangelog -l"${project}/debian/changelog" -S Version`
version=`echo "$debian_version" | cut -d- -f1`
package_version="${debian_version}.${dist}"
target_dist="project-${dist}"

dch --force-bad-version --newversion="$package_version" --distribution="$target_dist" -- \
  "Debian/Ubuntu package for $target_dist" < /dev/null
```

**Comment by smira** [comment]
I would second what @lazyfrosch said above, plus https://www.aptly.info/doc/feature/duplicate/ from the docs.

So this is all about publishing, and aptly follows Debian repository structure. Debian repository structures shares `pool/` directory between all the distributions under same prefix. It's not aptly restriction, but rather Debian repository guideline.

@law the easiest way would be to use different prefixes when publishing which would isolate `pool/` subdirectory per prefix.

**Comment by law** [comment]
Awesome, thank you all for the clarification!  I'm not entirely sure, yet, how to re-do our pipeline to accommodate for this, but I see in the Aptly docs that "If you’re completely sure that this update operation is correct, you can use flag -force-overwrite to disable check for conflicting package files."  If we wanted to just unblock this now, which API call in our script would we need to add 'force-overwrite' to?

**Comment by lazyfrosch** [comment]
I think @smira would recommend this together with the nightly builds, where the global pool is now using hashing to keep the packages.

Then force-overwrite (when adding an upload to a repository) would just add (and "replace") the default package for that in the global pool

I *think* the package in the individual repo publishes still would be the correct version.

Though I personally would suggest you to *really* change the individual versions. This would also allow you so see which build version is actually installed on a system.

Individual dist builds usually matter only on arch specific stuff, and then it is really important (from a logical and debugging perspective), that individual builds do not share the same version...

**Comment by smira** [comment]
> I think @smira would recommend this together with the nightly builds, where the global pool is now using hashing to keep the packages.

I don't think it's the case here. 

There are two distinct pools in aptly:

1. Internal aptly package pool (`~/.aptly/pool`) - it stores packages files, it's primary source of all the package files. In all versions of aptly pool is using filename which includes part of hash of package contents, so even if packages have identical filename, with high probability they would end up having different paths in internal pool. In `master` branch path generation was improved to guarantee that even accidentally we don't have conflicts. But I don't think that's the problem @law described.

2. Pool of files in published directory (e.g. `~/.aptly/public/pool/...`). This directory structure is described in https://wiki.debian.org/DebianRepository/Format. The way package files are laid out there, it's not possible to have identical package files with different contents under single prefix (as they share `pool/` subdirectory. This has nothing to do with aptly.

**Comment by law** [comment]
Pardon my ignorance, but is there a way to add a prefix in such a way that it doesn't mess with the version numbering?  The -dev environment can be whatever, it's supposed to be a fast n' loose place for packages to get pushed out.  -staging and -prod need a bit more rigor, as during normal operation our CM software has instructions to deploy the latest from those repositories.  If the prefix mucks with the version calculation, we're going to have a bad time.

**Comment by smira** [comment]
Prefix doesn't have anything to do with version numbering. Prefix is just subdirectory, not more than that.

**Comment by smira** [comment]
Closing on inactivity, please feel free to reopen.

**Comment by ZamanOof** [comment]
> @law the easiest way would be to use different prefixes when publishing which would isolate `pool/` subdirectory per prefix.
so how to do it with aptly?
