### ISSUE TITLE
GPGME support

### ISSUE THREAD

**Issue by zhsj** [smira/aptly#588]
I see there's an open PR that replaces gpg command with golang openpgp.

I do agree that interacting with external gpg command is complicated.
But please give an change to consider the gpgme library[1].
There's also a golang wrapper to the library[2].
 
I store the gpg private key in a yubikey[3], but the golang openpgp won't interact with it. 
I appreciate if you can take this into consideration.

[1] https://www.gnupg.org/software/gpgme/index.html
[2] https://github.com/proglottis/gpgme
[3] https://www.yubico.com/products/yubikey-hardware/

**Comment by smira** [comment]
Thanks for your feedback. First of all, I'm not replacing current external `gpg` with Golang internal implementation. aptly would provide an option to use one of the solutions. 

Personally I'm all fed up interacting with `gpg` from many different languages (including Go). If anyone wants to provide gpgme-powered backend, I'm all for it. One thing which might things worse is that it requires `cgo` which brings a lot of problems for cross-compilation.

**Comment by zhsj** [comment]
Thanks for the clarify. Since there's no deprecation of the external `gpg` command, then there's no need to use gpgme.

gpgme can avoid the complicated gpg command flags, however it introduces the cgo dependence. I have no strong preference to use the gpgme, so you can close this issue if you want.

**Comment by smira** [comment]
Thanks, @zhsj
