### ISSUE TITLE
Batch mode in aptly API should pass --batch to gpg

### ISSUE THREAD

**Issue by rmcfatter** [smira/aptly#591]
Despite the fix in smira/aptly#122, the "Batch" mode in the API fails to sign packages if run as a service.  Symptom is "gpg: cannot open tty `/dev/tty`: No such device".

## Detailed Description
#122 accepts a "Batch" signing option (from client JSON or a command-line argument). If present,
aptly adds the "--no-tty" argument to gpg.  That's insufficient (both in gpg 1.4 and 2.1): that argument affects tty output, not input.  The "--batch" argument should also get added to gpg to prevent it from trying to open /dev/tty for input.

## Context
Unable to run "aptly api serve" as a systemd service.

## Possible Implementation
This looks like a pretty straightforward fix: at the point where "--no-tty" is added as a gpg
argument, add "--batch" also.

## Your Environment
Ubuntu 16.04 (amd64)
Aptly 1.0.1

**Comment by smira** [comment]
Thanks, I'll get it implemented.

**Comment by rmcfatter** [comment]
I'm no longer convinced that the "Batch" signing option is working at all in 1.0.1: I captured the command line arguments passed to gpg and don't see "--no-tty" either, despite the "Batch" parameter being in the JSON parameters.  (This snippet is converted to
actual JSON by Python's *requests* module).
~~~~~~~~{.python}
json={
    "Signing": {
        "Batch": True,
        "GpgKey": settings.APTLY_GPG_KEY_NAME,
        "Keyring": settings.APTLY_GPG_KEYRING,
        "SecretKeyring": settings.APTLY_GPG_SECRET_KEYRING,
        "PassphraseFile": settings.APTLY_PASSPHRASE_FILE
    }
}
~~~~~~~~

The "PassphraseFile" parameter is working.  The gpg arguments that result from publishing this are:
~~~~~~~~{.sh}
--list-keys --dry-run --no-auto-check-trustdb
-o /tmp/aptly851824793/Release.gpg --digest-algo SHA256 --armor --yes --no-use-agent --passphrase-file /var/www/.signing-pp --detach-sign /tmp/aptly851824793/Release
-o /tmp/aptly851824793/InRelease --digest-algo SHA256 --yes --no-use-agent --passphrase-file /var/www/.signing-pp --clearsign /tmp/aptly851824793/Release
~~~~~~~~

**Comment by smira** [comment]
I've added some debugging output and ran tests with `"Batch": true`:

```
[-o /var/folders/qj/0x8mhy9n1qx2nqkkgpj2yzw80000gn/T/aptly827018523/Release.gpg --digest-algo SHA256 --armor --yes --no-auto-check-trustdb --no-default-keyring --keyring /Users/smira/Documents/go/src/github.com/smira/aptly/system/files/aptly.pub --secret-keyring /Users/smira/Documents/go/src/github.com/smira/aptly/system/files/aptly.sec --no-tty --batch --detach-sign /var/folders/qj/0x8mhy9n1qx2nqkkgpj2yzw80000gn/T/aptly827018523/Release]
```

Looks like both options are applied successfully (I'm running this in my dev branch)

**Comment by smira** [comment]
Please feel free to re-open if problem persists with nightly build
