### ISSUE TITLE
Blacklist for Packages

### ISSUE THREAD

**Issue by mischelebuha** [smira/aptly#592]
Is there a negative filter?

The virus scanner of our company blocks some Debian packages. Is it possible to create a kind of blacklist so that aptly blocks the specified packages? Can this be solved with the use of a filter?

**Comment by smira** [comment]
Package queries support negative filtering, so that should be doable if you attach filter to every mirror you have. But nothing on global level

**Comment by smira** [comment]
https://www.aptly.info/doc/feature/query/ for the reference
