### ISSUE TITLE
[question] Any plans on releasing 1.1.0?

### ISSUE THREAD

**Issue by aol-nnov** [smira/aptly#594]
@smira, the [roadmap](https://www.aptly.info/download/) on site states Jun 2017, but there is no release yet.
Or is go-build-your-own-release is the best bet for now? :)

As far as I learned from docs, 1.0.1 has legacy repository layout. I'd like to start using aptly, but I don't want to migrate really soon from my start.

Any new timeframe for 1.1.0?
Thank you!

**Comment by smira** [comment]
There's one thing left before 1.1.0 would be released: https://github.com/smira/aptly/labels/1.1.0 (internal PGP support).
