### ISSUE TITLE
repo update fails with timeout awaiting response headers

### ISSUE THREAD

**Issue by nikunj12** [smira/aptly#598]
aptly mirror update usually fails following errors, errors are observed after downloading the repo 

Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-340/nvidia-340_340.96-0ubuntu3_amd64.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/main/libh/libhybris/libandroid-properties1_0.1.0+git20151016+6d424c9-0ubuntu7_i386.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-361/nvidia-361-dev_361.42-0ubuntu2_amd64.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/main/libh/libhybris/libandroid-properties-dev_0.1.0+git20151016+6d424c9-0ubuntu7_amd64.deb...
ERROR: unable to update: download errors:
  http://in.archive.ubuntu.com/ubuntu/pool/main/m/mobile-broadband-provider-info/mobile-broadband-provider-info_20140317-1_all.deb: Get http:/ubuntu/pool/main/m/mobile-broadband-provider-info/mobile-broadband-provider-info_20140317-1_all.deb: net/http: timeout awaiting response headers
  http://in.archive.ubuntu.com/ubuntu/pool/main/c/corosync/libcorosync-common4_2.3.5-3ubuntu1_amd64.deb: Get http:/ubuntu/pool/main/c/corosync/libcorosync-common4_2.3.5-3ubuntu1_amd64.deb: net/http: timeout awaiting response headers

## Detailed Description

updated to latest nightly version of aptly 
aptly version: 1.0.0+107+gfcd4531

In previous version(0.9.0) was getting EOF error 

## Context

Because of this error I am unable to create snapshot
root@repo01:/repo/lnxrepo# aptly snapshot create u16041 from mirror ubuntu1604-main
ERROR: unable to create snapshot: mirror not updated
root@repo01:/repo/lnxrepo#

Basically If you create the multiversion repo for ubuntu then it will helpful

## Your Environment

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

root@bng-lnx-repo01:/repo/lnxrepo# aptly version
aptly version: 1.0.0+107+gfcd4531

aplty conf file

{
  "rootDir": "/repo/lnxrepo",
  "downloadConcurrency": 4,
  "downloadSpeedLimit": 0,
  "architectures": [],
  "dependencyFollowSuggests": false,
  "dependencyFollowRecommends": false,
  "dependencyFollowAllVariants": false,
  "dependencyFollowSource": false,
  "gpgDisableSign": false,
  "gpgDisableVerify": false,
  "downloadSourcePackages": false,
  "ppaDistributorID": "ubuntu",
  "ppaCodename": "",
  "FileSystemPublishEndpoints": {
  "test1": {
    "rootDir": "/repo/lnxrepo/branch1/aptly_public",
    "linkMethod": "symlink"
  },
  "test2": {
    "rootDir": "/repo/lnxrepo/branch2/aptly_public",
    "linkMethod": "copy",
    "verifyMethod": "md5"
  },
  "test3": {
    "rootDir": "/repo/lnxrepo/branch3/aptly_public",
    "linkMethod": "hardlink"
  }
},

  "S3PublishEndpoints": {},
  "SwiftPublishEndpoints": {}
}

**Comment by smira** [comment]
@nikunj12 I don't have much to say here, this looks like networking/mirror problem. You can try using different mirror (aptly would still use already downloaded packages).

**Comment by nikunj12** [comment]
I will try to use other mirror, However, There is no issue on network because I got error at last stage, It downloaded almost 8 GB repo and at last it failed 

Secondly,
It tries to find http:/   so which is also something wondering..

Get http:/ubuntu/pool/main/c/corosync/libcorosync-common4_2.3.5-3ubuntu1_amd64.deb: net/http: timeout awaiting response headers

I think similar kind of issue was reported where it was throwing the EOF error but in my case it is showing timeout awaiting response header with aptly 1.x version

**Comment by nikunj12** [comment]
Thanks - I will update you after changing the mirror as well.

**Comment by nikunj12** [comment]
I also tried with other mirror , it failed at following point .

Is there any way that can I create the snapshot by ignoring these errors? may be forceful option should be there because because of these errors I am unable to create the snapshot from the mirror 


Downloading http://us.archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-proxy_1.11.5-1ubuntu3_amd64.deb...
Downloading http://us.archive.ubuntu.com/ubuntu/pool/main/c/corosync/libcorosync-common4_2.3.3-1ubuntu1_amd64.deb...
Downloading http://us.archive.ubuntu.com/ubuntu/pool/main/libp/libpackage-deprecationmanager-perl/libpackage-deprecationmanager-perl_0.13-1_all.deb...
Downloading http://us.archive.ubuntu.com/ubuntu/pool/main/c/corosync/libcorosync-common-dev_2.3.3-1ubuntu1_amd64.deb...
Downloading http://us.archive.ubuntu.com/ubuntu/pool/main/libh/libhybris/libandroid-properties1_0.1.0+git20131207+e452e83-0ubuntu12_amd64.deb...

ERROR: unable to update: download errors:
  http://us.archive.ubuntu.com/ubuntu/pool/main/libh/libhybris/libandroid-properties-dev_0.1.0+git20131207+e452e83-0ubuntu12_amd64.deb: Get http:/ubuntu/pool/main/libh/libhybris/libandroid-properties-dev_0.1.0%2bgit20131207%2be452e83-0ubuntu12_amd64.deb: net/http: timeout awaiting response headers
  http://us.archive.ubuntu.com/ubuntu/pool/main/u/unity/libunity-2d-private-dev_7.2.0+14.04.20140416-0ubuntu1_all.deb: Get http:/ubuntu/pool/main/u/unity/libunity-2d-private-dev_7.2.0%2b14.04.20140416-0ubuntu1_all.deb: net/http: timeout awaiting response headers
  http://us.archive.ubuntu.com/ubuntu/pool/main/m/mobile-broadband-provider-info/mobile-broadband-provider-info_20140317-1_all.deb: Get http:/ubuntu/pool/main/m/mobile-broadband-provider-info/mobile-broadband-provider-info_20140317-1_all.deb: net/http: timeout awaiting response headers

**Comment by smira** [comment]
Snapshot can't be create from mirror which has never been updated, as aptly doesn't have all the package files. One option is to cut down mirror size by filtering out stuff you don't need. But `aptly mirror update` should resume downloading from the place where it was stopped.

**Comment by smira** [comment]
So if looks like you have three packages which failed to download, are they failing all the time? (if you retry aptly mirror update?)

**Comment by nikunj12** [comment]
It keeps failing  with same error 

I am getting same problem in ubuntu140.4 and ubuntu 160.04 repos, even it download till 376 MB  repo and at last it failed with same errors and as a result I can not create the snapshop

Secondly - 

I dont think so download resume is working in all cases


in following example I started download of 376 MB repo and in between I stopped but it didnt resume from the place where it stopped ...

Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-304-updates/nvidia-experimental-304-dev_304.131-0ubuntu3_amd64.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-304-updates/nvidia-current-updates_304.131-0ubuntu3_amd64.deb...
 59.12 MiB / 376.55 MiB [========================>--------------------------------------------------------------------------------------------------------------------------------]  15.70% 509.55 KiB/s 10m37s 60.24 MiB / 376.55 MiB [========================>--------------------------------------------------------------------------------------------------------------------------------]  16.00% 507.22 KiB/s 10m38s^C
root@bng-lnx-repo01:~# aptly mirror update ubuntu1604-main
Downloading http://in.archive.ubuntu.com/ubuntu/dists/xenial/InRelease...
gpgv: Signature made Thu 21 Apr 2016 04:25:09 PM PDT using DSA key ID 437D05B5
gpgv: Good signature from "Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>"
gpgv: Signature made Thu 21 Apr 2016 04:25:09 PM PDT using RSA key ID C0B21F32
gpgv: Good signature from "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>"
Downloading & parsing package files...
Downloading http://in.archive.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/Packages.gz...
Downloading http://in.archive.ubuntu.com/ubuntu/dists/xenial/main/binary-i386/Packages.gz...
Downloading http://in.archive.ubuntu.com/ubuntu/dists/xenial/restricted/binary-amd64/Packages.gz...
Downloading http://in.archive.ubuntu.com/ubuntu/dists/xenial/restricted/binary-i386/Packages.gz...
Building download queue...
Download queue: 102 items (376.55 MiB)
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-361/nvidia-352_361.42-0ubuntu2_i386.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-304-updates/nvidia-experimental-304_304.131-0ubuntu3_i386.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/main/libh/libhybris/libandroid-properties1_0.1.0+git20151016+6d424c9-0ubuntu7_i386.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-304-updates/nvidia-current-updates-dev_304.131-0ubuntu3_amd64.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/main/c/corosync/libcorosync-common4_2.3.5-3ubuntu1_amd64.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-352-updates/nvidia-346-updates_352.63-0ubuntu3_i386.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-340/nvidia-331-updates-dev_340.96-0ubuntu3_i386.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-361/nvidia-361_361.42-0ubuntu2_i386.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-340/nvidia-340-updates_340.96-0ubuntu3_amd64.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-352-updates/nvidia-346-updates-dev_352.63-0ubuntu3_i386.deb...
Downloading http://in.archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-304-updates/nvidia-304-updates_304.131-0ubuntu3_i386.deb...
 832.79 KiB / 376.55 MiB [>-----------------------

**Comment by nikunj12** [comment]
I would suggest that we can ignore such errors and we can create the snapshop with some flags.

**Comment by nikunj12** [comment]
I found there are few packages are not downloadable from repo for example if you put following link in browser then it will not get the package but manually you can get it from "http://in.archive.ubuntu.com/ubuntu/pool/main/s/sssd" 

http://in.archive.ubuntu.com/ubuntu/pool/main/s/sssd/sssd-proxy_1.13.4-1ubuntu1_i386.deb

I dont know what is the issue but it would be great if we can ignore such errors using any flags.

**Comment by smira** [comment]
This still sounds like mirror problem or issue with your networking. If it fails with the same package over and over, you can filter it out with `-filter` flag, but if failures are random, there's not much we can do. Snapshot creation is not allowed as aptly doesn't have package files for all the packages, so subsequent attempt to publish that snapshot would fail.

On download not resuming - that's the case with nightly or 1.1.0 - as the database is closed while downloading, aptly can't import already downloaded files. I don't have solution for that so far. In the worst case you can try mirroring through caching proxy like https://www.unix-ag.uni-kl.de/~bloch/acng/

Please feel free to re-open if there's something else I can do.

**Comment by tirolerstefan** [comment]
I experience a similar problem when updating our mirror (aptly 1.1.1): 

ERROR: unable to update: download errors:
  http://archive.ubuntu.com/ubuntu/pool/main/libo/liboauth/liboauth0_1.0.3-1_i386.deb: Get http://archive.ubuntu.com/ubuntu/pool/main/libo/liboauth/liboauth0_1.0.3-1_i386.deb: net/http: timeout awaiting response headers

I repeated the update and got:

ERROR: unable to update: download errors:
  http://archive.ubuntu.com/ubuntu/pool/main/libf/libfontenc/libfontenc1_1.1.3-1_amd64.deb: Get http://archive.ubuntu.com/ubuntu/pool/main/libf/libfontenc/libfontenc1_1.1.3-1_amd64.deb: net/http: timeout awaiting response headers

I think, network problems can occur at any time - that's normal. But in case of such a timeout, a retry behaviour would be very nice, because we do an update within a nightly cronjob and it would be more comfortable not to write an exit code checking bash script with for loop.

**Comment by nikunj12** [comment]
@tirolerstefan  try to download problematic packages manually and check the package integrity. 

Indeed, I have wrote the script to perform these tasks seems its working well for me!

**Comment by tirolerstefan** [comment]
Correction: I saw, there is already a retry flag ... sorry!

https://www.aptly.info/doc/aptly/mirror/update/
-max-tries=1: Max download tries till process fails with download error

**Comment by chicofranchico** [comment]
Trying to update a mirror but I get the following:
``Downloading & parsing package files...
Downloading http://downloads.linux.hpe.com/SDR/repo/mcp/dists/xenial/current/non-free/binary-amd64/Packages.bz2...
Building download queue...
Download queue: 1 items (9.36 MiB)
Downloading http://downloads.linux.hpe.com/SDR/repo/mcp/pool/non-free/ssacli-3.10-3.0_amd64.deb...
ERROR: unable to update: download errors:
  http://downloads.linux.hpe.com/SDR/repo/mcp/pool/non-free/ssacli-3.10-3.0_amd64.deb: Get http:/SDR/repo/mcp/pool/non-free/ssacli-3.10-3.0_amd64.deb: net/http: timeout awaiting response headers``


But the download works fine, albeit with a pause (just before the 200OK) on the awaiting response part:

```time wget http://downloads.linux.hpe.com/SDR/repo/mcp/pool/non-free/ssacli-3.10-3.0_amd64.deb
--2018-06-05 11:30:39--  http://downloads.linux.hpe.com/SDR/repo/mcp/pool/non-free/ssacli-3.10-3.0_amd64.deb
Resolving downloads.linux.hpe.com (downloads.linux.hpe.com)... 15.249.152.85
Connecting to downloads.linux.hpe.com (downloads.linux.hpe.com)|15.249.152.85|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9811948 (9.4M)
Saving to: ssacli-3.10-3.0_amd64.deb

ssacli-3.10-3.0_amd64.deb                                           100%[===================================================================================================================================================================>]   9.36M  --.-KB/s    in 0.09s

2018-06-05 11:31:16 (103 MB/s) - ‘ssacli-3.10-3.0_amd64.deb’ saved [9811948/9811948]


real	0m36.765s
user	0m0.017s
sys	0m0.013s
```

Is there a way to increase the timeout?

**Comment by smira** [comment]
Timeout for response headers it hardcoded at 30 seconds. If you would like to see that configurable, please open an issue (this issue is closed). For me this mirror works just fine, do you have a proxy in your environment?

**Comment by chicofranchico** [comment]
I know that there are plenty of firewalls between the server and that mirror. I'm guessing there might be something doing DPI. I managed to compile a version with the timeout at 60 and it works. I'm going to look with the networking engineers for that.
