### ISSUE TITLE
Repo copy of non-existent package should return error

### ISSUE THREAD

**Issue by Grimm75** [smira/aptly#605]
Running:
`
aptly repo copy jessie-stable stretch-stable 'i_do_not_exist (>0)'  ;  echo $?`

Result: 0

Above exit status should be non-zero.

## Context
When scripting with aptly, this will allow correct handling of above situation without parsing aptly output.

## Your Environment
aptly-1.0.1
Debian Jessie 8.8

**Comment by smira** [comment]
I don't think that copy command should fail if no packages matched query. You can use `repo search` with same query right before `copy` to verify if any packages match query. (`search` commands exit with error if nothing is found)

**Comment by Grimm75** [comment]
Agree - this will solve the problem - search before copy. Thanks.
