### ISSUE TITLE
question: why the architecture in the package key is preceded by a 'P' ?

### ISSUE THREAD

**Issue by sandrotosi** [smira/aptly#606]
Hello!
when working with the APIs, i noticed the architecture for a package key has a leading 'P', like:

```
    "Psource python-aptly 0.8.1-1 d7f915f6c589eed2",
    "Pall aptly-publisher 0.8.1-1 7c2b1e61105279bf",
    "Pall python3-aptly 0.8.1-1 1dd4d1b2b961706f",
    "Psource aptly 0.9.7-1 e233ee3a093a4989",
    "Pall python-aptly 0.8.1-1 51398db7b8760874",
    "Pamd64 aptly 0.9.7-1+b1 fbd23e479b367ced",
```

(as available in debian stretch ;) )

can you clarify what is the reason for it? it is mainly a curiosity, but it may be worth it to document it. f.e. i may have understoond 'P' for binary packages and 'S' for source packages, but they are all marked as 'P' (even arch:all)

thanks!

**Comment by smira** [comment]
This is package id, it shouldn't  be parsed directly, as it might change in the future. Internally `P` stands for the `P`ackage, but this is not guaranteed to be the same going forward. If you want to get details, pull info about package by id.

**Comment by smira** [comment]
Closing on inactivity, please feel free to re-open
