### ISSUE TITLE
aptly doesn't send a 100 CONTINUE (API with curl freezes via Proxy)

### ISSUE THREAD

**Issue by Dees7** [smira/aptly#609]
I use aptly in docker

Docker host 192.168.100.100

I build container from aptly_1.0.1_linux_amd64

FROM  alpine:edge
EXPOSE 9988:9988

When I try to POST file like there:
curl -v -s -X POST -F file=@mypackaga.deb http://192.168.100.100/api/files/mypackage.deb

all ok.

After it I install polipo

/etc/polipo/config
socksParentProxy = "localhost:9898"
socksProxyType = socks5

make ssh tunnel:
/usr/bin/ssh -f -N -D 9898 -l user 192.168.100.100

and restart polipo.

Now we have HTTP->Socks5 proxy via direct ssh to docker host.

Enable proxy
http_proxy=http://127.0.0.1:8123
curl -v -s -X POST -F file=@mypackaga.deb http://192.168.100.100/api/files/mypackage.deb

curl frize because curl waiting for 100-continue.

It looks like APTLY doesn't sent 100-continue correctly (http://www.iandennismiller.com/posts/curl-http1-1-100-continue-and-multipartform-data-post.html)

log with proxy

* Trying 192.168.56.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8123 (#0)
> POST http://192.168.100.100:9988/api/files/mypackaga.deb HTTP/1.1
> Host: 192.168.100.100:9988
> User-Agent: curl/7.47.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> Content-Length: 1499011
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------67bb663ad0e09fb2
>
* Done waiting for 100-continue
< HTTP/1.1 100 Continue
< Proxy-Connection: keep-alive
< Connection: keep-alive`

log without proxy
*  Trying 192.168.100.100...
* Connected to 192.168.100.100 (192.168.100.100) port 9988 (#0)
> POST /api/files/mypackaga.deb HTTP/1.1
> Host: 192.168.100.100:9988
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 1499011
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------222dc10c4c42d126
>
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 03 Aug 2017 10:01:10 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 88
< Connection: keep-alive
< 

In case I use http 1.0 (curl -0) it works well.

**Comment by smira** [comment]
@Dees7 it looks like aptly does send `100 Continue` correctly, in fact your log "without proxuy" above shows that. I would assume it's proxy which breaks `100 Continue` flow:

```
$ curl -v -s -X POST -F file=@system/files/libboost-program-options-dev_1.49.0.1_i386.deb http://localhost:8080/api/files/a.deb
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /api/files/a.deb HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 2976
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------be4d821d2252f565
>
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Tue, 08 Aug 2017 21:04:58 GMT
< Content-Length: 57
<
["a.deb/libboost-program-options-dev_1.49.0.1_i386.deb"]
```

So I can't blame aptly, as it sends response correctly.

**Comment by smira** [comment]
Closing on inactivity, please feel free to re-open
