### ISSUE TITLE
print "Unable to open database, sleeping" to stderr

### ISSUE THREAD

**Issue by jspricke** [smira/aptly#610]
With current master aptly prints the error "Unable to open database, sleeping" to stdout, next to the real output. This makes it impossible to directly use the output in a shell script.

## Possible Implementation

Change https://github.com/smira/aptly/blob/master/context/context.go#L265 to print to stderr. (I don't have the Go skills right now to do it).

## Your Environment

Current aptly master

**Comment by smira** [comment]
Thanks, I will get it fixed in a few!
