### ISSUE TITLE
S3 publishing endpoint appears to reupload everything

### ISSUE THREAD

**Issue by MMartyn** [smira/aptly#619]
I am investigating slowness around publishing new snapshots to s3. I turned on debugging and the ListObjects call appeared to double up on the prefix ie 
`GET /?max-keys=1000&prefix={prefix}%2F{prefix}%2F`. 

As far as I can tell I have the s3 endpoint configured correctly and I am not sending a prefix in the command but do have the prefix configured in the endpoint. 

Unless I am reading the code incorrectly it looks like that is happening as a result of these 2 lines:
https://github.com/smira/aptly/blob/master/s3/public.go#L270
https://github.com/smira/aptly/blob/master/s3/public.go#L325

**Comment by smira** [comment]
thanks, nice catch!

there's no error but it gets empty listing and decides to re-upload everything :(
