### ISSUE TITLE
Can't drop published repo with leading hyphen

### ISSUE THREAD

**Issue by ijpulidos** [smira/aptly#625]
aptly publish lets me publish a repo with leading hyphen (I did that by mistake) but now I can't drop it, since aptly tries to understand the name of the repo as an argument (which doesn't exist). I think this is related to issue #561 but not sure.
The commands that show the issue are as follow:

`aptly publish list`

which outputs

```
Published repositories:
  * -force-overwrite=true/stretch <all the snapshots merged here>
```

And when I try to drop it using  `aptly publish drop -force-overwrite=true/stretch` I get: `flag provided but not defined: -force-overwrite`

I expect aptly to be able to drop something it allowed me to create.

**Comment by smira** [comment]
Same thing as for every other cli out there: use `--` to stop flag parsing:

`aptly publish drop -- stretch -force-overwrite=true`
