### ISSUE TITLE
How can i search multiple packages with the snapshot api

### ISSUE THREAD

**Issue by mischelebuha** [smira/aptly#626]
Search one Package works well:

`curl http://xxx/api/snapshots/debian_2017-07-20/packages?withDeps=1&q=nano`

But how i search with a query as paramter?

`["curl","nano",...]`

**Comment by smira** [comment]
Exactly same way as in the cli, you just need to build query like `curl | nano` and pass it as query parameter (of course, urlencoded).

**Comment by mischelebuha** [comment]
In the CLI it works with:
`aptly snapshot --with-deps filter xxx xxx {'nano','curl'}`

and with curl it works too:
`curl "http://xxx/api/snapshots/debian_2017-07-20/packages?withDeps=1&q={nano,curl}"`

But with the Browser (Chrome) i struggle with: 
`http://xxx/api/snapshots/debian_2017-07-20/packages?withDeps=1&q={nano,curl}`

and have this error:
`[{"error":"parsing failed: unexpected token {: expecting field or package name","meta":"Operation aborted"}]`

**Comment by smira** [comment]
`{` is special character for shell, it gets removed actually. 

So just do `nano,curl` without curly braces

**Comment by mischelebuha** [comment]
These requests are answered correctly:

`.../api/snapshots/debian_2017-07-20/packages?withDeps=1&q=nano`
`["Parmhf libcurl3 7.38.0-4+deb8u5 bb04734e903e4856","Parmhf multiarch-support 2.19-18+deb8u9 706f2ae02a95d228", ... ]`

`.../api/snapshots/debian_2017-07-20/packages?withDeps=1&q=curl`

`["Parmhf libgcc1 1:4.9.2-10 6bbcba4df2db4180","Parmhf libpcre3 2:8.35-3.3+deb8u4 60d4fe6da9d6de5","Parmhf install-info 5.2.0.dfsg.1-6 915cc1ba4376190a","Parmhf multiarch-support 2.19-18+deb8u9 706f2ae02a95d228", ... ]`

But the response of this request ist only a emty Array with the status code 200 OK:

`.../api/snapshots/debian_2017-07-20/packages?withDeps=1&q=nano,curl`
`[ ]`
