### ISSUE TITLE
aptly api serve locks the db forever

### ISSUE THREAD

**Issue by jmellor** [smira/aptly#634]
aptly api serve locks the db forever

## Detailed Description
After a relatively small delay (<10 minutes), or immediately after an api call failure, aptly api serve locks the db, resulting in a total loss of service.

## Context
Blocking bug.  Complete failure of all access methods for aptly is always the result.
Aborting the api serve service immediately unlocks the db, allowing other forms of access (e.g. CLI) to continue.

## Possible Implementation
There should be no service exit paths that leave the db locked.  There is also something that locks the db after a few minutes with no api access required.

## Your Environment
Using aptly 1.1.1 on Ubuntu 14.04.5.
Example api service invocation:
> $ aptly api serve -listen=:11604 -config=$HOME/.aptly-xenial.conf
Example aptly config content:
> $ cat .aptly-xenial.conf
> {
>   "rootDir": "/home/esadmin/.aptly-xenial",
>   "downloadConcurrency": 2,
>   "downloadSpeedLimit": 0,
>   "architectures": [],
>   "dependencyFollowSuggests": false,
>   "dependencyFollowRecommends": false,
>   "dependencyFollowAllVariants": false,
>   "dependencyFollowSource": false,
>   "gpgDisableSign": false,
>   "gpgDisableVerify": false,
>   "downloadSourcePackages": false,
>   "ppaDistributorID": "ubuntu",
>   "ppaCodename": "",
>   "S3PublishEndpoints": {}
> }

**Comment by smira** [comment]
https://www.aptly.info/doc/api/:

```
API service and CLI tool could be used from the same aptly root (to enable concurrent CLI and API usage, add -no-lock flag to aptly api serve command).
```

So without `-no-lock` flag API is expected to lock the DB for the whole duration of time while process is running.

**Comment by jmellor** [comment]
Andrey stated:
> to enable concurrent CLI and API usage, add -no-lock flag to aptly api serve command

Understood. My prototyping seems to show that this works. Thanks!

However, I have a poor understanding of what locking is still being performed when the -no-lock flag is being used. Is any secondary locking in place, so that simultaneous CLI and API calls do not get their queues, db entries and content mixed up? I.e, do I have to wrapper every CLI and API call with my own explicit locking code because internal locking is now disabled?


On Thu, 2017-09-14 at 12:14 -0700, Andrey Smirnov wrote:

https://www.aptly.info/doc/api/:

API service and CLI tool could be used from the same aptly root (to enable concurrent CLI and API usage, add -no-lock flag to aptly api serve command).


So without -no-lock flag API is expected to lock the DB for the whole duration of time while process is running.

**Comment by smira** [comment]
> However, I have a poor understanding of what locking is still being performed when the -no-lock flag is being used. Is any secondary locking in place, so that simultaneous CLI and API calls do not get their queues, db entries and content mixed up? I.e, do I have to wrapper every CLI and API call with my own explicit locking code because internal locking is now disabled?

"Locking" here refers to aptly internal DB lock. In any case, only one instance of aptly would be accessing database. 

With `-no-lock` flag, aptly would try to grab and release the lock only for the duration of the API call. So when API is idle, DB is not locked, and CLI commands would be running fine.

In any case, when trying to acquire the lock, aptly (both CLI and API) would perform several attempts to acquire the lock waiting between the attempts, so even if you have a lot of activity happening at the same time, you don't need anything special to handle it
