### ISSUE TITLE
Add api validation debugging capability

### ISSUE THREAD

**Issue by jmellor** [smira/aptly#639]
Add api validation debugging capability

## Detailed Description
If something is wrong in a very complex api call like a publish of multiple repo snapshots, all that is returned is a useless message rejecting the call with no specific reason.  This makes the api much harder to use than it should be, as the effort required to get it right via trial-and-error is astronomical.
"Method not allowed" is not a useful debugging message.  e.g: What was passed in and why is it not allowed should be returned in the 404 message.

E.g: a publish post message like:

  curl --trace - -s -X PUT -H 'Content-Type: application/json' \
                                         --data '{"SourceKind": "snapshot", \
                                                  "Distribution": "'${Company}-${Product}'", \
                                                  "Architectures": ["i386", "amd64"], \
                                                  "Sources": [{"Component": "dev",        "Name": "'snap-${Product}-dev-latest'"},     \
                                                              {"Component": "testing",    "Name": "'snap-${Product}-testing-latest'"}, \
                                                              {"Component": "stable",     "Name": "'snap-${Product}-stable-latest'"},  \
                                                              {"Component": "production", "Name": "'snap-${Product}-production-latest'"} ]}' \
                                         http://${RepoHost}:${RepoPort}/api/publish/${Company}-${Product} \
                                    || exit 1
must have something wrong with it, but nobody here can see it.  The api serve does not even see the event, and the error message is very unhelpful.  The job log from the above call results it (typical):
  00:13:48.435 DEBUG: Publishing esentire-esensor-10
  00:13:48.435 == Info:   Trying 10.1.110.127...
  00:13:48.435 == Info: Connected to build-repo.internal (10.1.110.127) port 11604 (#0)
  00:13:48.435 => Send header, 173 bytes (0xad)
  00:13:48.435 0000: 50 55 54 20 2f 61 70 69 2f 70 75 62 6c 69 73 68 PUT /api/publish
  00:13:48.435 0010: 2f 65 73 65 6e 74 69 72 65 2d 65 73 65 6e 73 6f /esentire-esenso
  00:13:48.435 0020: 72 2d 31 30 20 48 54 54 50 2f 31 2e 31 0d 0a 48 r-10 HTTP/1.1..H
  00:13:48.435 0030: 6f 73 74 3a 20 62 75 69 6c 64 2d 72 65 70 6f 2e ost: build-repo.
  00:13:48.435 0040: 69 6e 74 65 72 6e 61 6c 3a 31 31 36 30 34 0d 0a internal:11604..
  00:13:48.435 0050: 55 73 65 72 2d 41 67 65 6e 74 3a 20 63 75 72 6c User-Agent: curl
  00:13:48.435 0060: 2f 37 2e 34 37 2e 30 0d 0a 41 63 63 65 70 74 3a /7.47.0..Accept:
  00:13:48.435 0070: 20 2a 2f 2a 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79  */*..Content-Ty
  00:13:48.435 0080: 70 65 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f pe: application/
  00:13:48.435 0090: 6a 73 6f 6e 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65 json..Content-Le
  00:13:48.435 00a0: 6e 67 74 68 3a 20 37 33 38 0d 0a 0d 0a          ngth: 738....
  00:13:48.435 => Send data, 738 bytes (0x2e2)
  00:13:48.435 0000: 7b 22 53 6f 75 72 63 65 4b 69 6e 64 22 3a 20 22 {"SourceKind": "
  00:13:48.435 0010: 73 6e 61 70 73 68 6f 74 22 2c 20 20 20 20 20 20 snapshot",      
  00:13:48.435 0020: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0030: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0040: 20 20 20 20 20 20 20 20 20 20 20 20 20 22 44 69              "Di
  00:13:48.435 0050: 73 74 72 69 62 75 74 69 6f 6e 22 3a 20 22 65 73 stribution": "es
  00:13:48.435 0060: 65 6e 74 69 72 65 2d 65 73 65 6e 73 6f 72 2d 31 entire-esensor-1
  00:13:48.435 0070: 30 22 2c 20 20 20 20 20 20 20 20 20 20 20 20 20 0",             
  00:13:48.435 0080: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0090: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 00a0: 20 20 20 20 20 20 22 41 72 63 68 69 74 65 63 74       "Architect
  00:13:48.435 00b0: 75 72 65 73 22 3a 20 5b 22 69 33 38 36 22 2c 20 ures": ["i386", 
  00:13:48.435 00c0: 22 61 6d 64 36 34 22 5d 2c 20 20 20 20 20 20 20 "amd64"],       
  00:13:48.435 00d0: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 00e0: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 00f0: 20 20 20 20 20 20 20 20 20 20 20 20 22 53 6f 75             "Sou
  00:13:48.435 0100: 72 63 65 73 22 3a 20 5b 7b 22 43 6f 6d 70 6f 6e rces": [{"Compon
  00:13:48.435 0110: 65 6e 74 22 3a 20 22 64 65 76 22 2c 20 20 20 20 ent": "dev",    
  00:13:48.435 0120: 20 20 20 20 22 4e 61 6d 65 22 3a 20 22 73 6e 61     "Name": "sna
  00:13:48.435 0130: 70 2d 65 73 65 6e 73 6f 72 2d 31 30 2d 64 65 76 p-esensor-10-dev
  00:13:48.435 0140: 2d 6c 61 74 65 73 74 22 7d 2c 20 20 20 20 20 20 -latest"},      
  00:13:48.435 0150: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0160: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0170: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0180: 20 20 20 20 20 20 20 20 20 20 20 20 20 7b 22 43              {"C
  00:13:48.435 0190: 6f 6d 70 6f 6e 65 6e 74 22 3a 20 22 74 65 73 74 omponent": "test
  00:13:48.435 01a0: 69 6e 67 22 2c 20 20 20 20 22 4e 61 6d 65 22 3a ing",    "Name":
  00:13:48.435 01b0: 20 22 73 6e 61 70 2d 65 73 65 6e 73 6f 72 2d 31  "snap-esensor-1
  00:13:48.435 01c0: 30 2d 74 65 73 74 69 6e 67 2d 6c 61 74 65 73 74 0-testing-latest
  00:13:48.435 01d0: 22 7d 2c 20 20 20 20 20 20 20 20 20 20 20 20 20 "},             
  00:13:48.435 01e0: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 01f0: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0200: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0210: 20 20 7b 22 43 6f 6d 70 6f 6e 65 6e 74 22 3a 20   {"Component": 
  00:13:48.435 0220: 22 73 74 61 62 6c 65 22 2c 20 20 20 20 20 22 4e "stable",     "N
  00:13:48.435 0230: 61 6d 65 22 3a 20 22 73 6e 61 70 2d 65 73 65 6e ame": "snap-esen
  00:13:48.435 0240: 73 6f 72 2d 31 30 2d 73 74 61 62 6c 65 2d 6c 61 sor-10-stable-la
  00:13:48.435 0250: 74 65 73 74 22 7d 2c 20 20 20 20 20 20 20 20 20 test"},         
  00:13:48.435 0260: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0270: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0280: 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20                 
  00:13:48.435 0290: 20 20 20 20 20 20 20 7b 22 43 6f 6d 70 6f 6e 65        {"Compone
  00:13:48.435 02a0: 6e 74 22 3a 20 22 70 72 6f 64 75 63 74 69 6f 6e nt": "production
  00:13:48.435 02b0: 22 2c 20 22 4e 61 6d 65 22 3a 20 22 73 6e 61 70 ", "Name": "snap
  00:13:48.435 02c0: 2d 65 73 65 6e 73 6f 72 2d 31 30 2d 70 72 6f 64 -esensor-10-prod
  00:13:48.435 02d0: 75 63 74 69 6f 6e 2d 6c 61 74 65 73 74 22 7d 20 uction-latest"} 
  00:13:48.435 02e0: 5d 7d                                           ]}
  00:13:48.435 == Info: upload completely sent off: 738 out of 738 bytes
  00:13:48.435 <= Recv header, 33 bytes (0x21)
  00:13:48.435 0000: 48 54 54 50 2f 31 2e 31 20 34 30 35 20 4d 65 74 HTTP/1.1 405 Met
  00:13:48.435 0010: 68 6f 64 20 4e 6f 74 20 41 6c 6c 6f 77 65 64 0d hod Not Allowed.
  00:13:48.435 0020: 0a                                              .
  00:13:48.435 <= Recv header, 41 bytes (0x29)
  00:13:48.435 0000: 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74 65 Content-Type: te
  00:13:48.435 0010: 78 74 2f 70 6c 61 69 6e 3b 20 63 68 61 72 73 65 xt/plain; charse
  00:13:48.435 0020: 74 3d 75 74 66 2d 38 0d 0a                      t=utf-8..
  00:13:48.435 <= Recv header, 33 bytes (0x21)
  00:13:48.435 0000: 58 2d 43 6f 6e 74 65 6e 74 2d 54 79 70 65 2d 4f X-Content-Type-O
  00:13:48.435 0010: 70 74 69 6f 6e 73 3a 20 6e 6f 73 6e 69 66 66 0d ptions: nosniff.
  00:13:48.435 0020: 0a                                              .
  00:13:48.435 <= Recv header, 37 bytes (0x25)
  00:13:48.435 0000: 44 61 74 65 3a 20 4d 6f 6e 2c 20 31 38 20 53 65 Date: Mon, 18 Se
  00:13:48.435 0010: 70 20 32 30 31 37 20 31 34 3a 34 36 3a 30 38 20 p 2017 14:46:08 
  00:13:48.435 0020: 47 4d 54 0d 0a                                  GMT..
  00:13:48.435 <= Recv header, 20 bytes (0x14)
  00:13:48.435 0000: 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 Content-Length: 
  00:13:48.435 0010: 31 39 0d 0a                                     19..
  00:13:48.435 <= Recv header, 2 bytes (0x2)
  00:13:48.435 0000: 0d 0a                                           ..
  00:13:48.435 <= Recv data, 19 bytes (0x13)
  00:13:48.435 0000: 4d 65 74 68 6f 64 20 4e 6f 74 20 41 6c 6c 6f 77 Method Not Allow
  00:13:48.435 0010: 65 64 0a                                        ed.
  00:13:48.435 Method Not Allowed
  00:13:48.435 == Info: Connection #0 to host build-repo.internal left intact

Since there is nothing obviously wrong with this call, there is no way to fix it.

## Context
It is not currently possible to debug weird api problems, due to lack of information being returned by Aptly.  This prevent use of the api due to the rediculously slow debugging-by-friction required.

## Possible Implementation
Reimplement the api semantic checking to actually be useful to the user.

## Your Environment
Aptly 1.1.1 on Ubuntu 14.04.5/latest.

**Comment by smira** [comment]
It's pretty precise error message - the route you're calling doesn't exist.
