### ISSUE TITLE
Running aptly publish with -passphrase-file still attempts to open /dev/tty

### ISSUE THREAD

**Issue by PaulShore** [smira/aptly#642]
Trying to script an aptly publish as root, running aptly publish within the script as:

su -c 'aptly publish snapshot -passphrase-file=/storage/aptly/passphrase-key.txt -component=main -distribution=xenial xenial-docker-main-2017092217 docker-2017092217' - aptly

Getting the error:
gpg: cannot open tty `/dev/tty': No such device or address
With a exit status of 2

## Detailed Description

Is it possible to call gpg so it doesn't open /dev/tty so this can be scripted?

## Context

Need to be able to script publishing of aptly snapshots

## Your Environment

ubuntu 16.04, aptly 1.1.1

**Comment by smira** [comment]
You might want to try `-batch` flag, and also look towards internal PGP provider (`-gpg-provider=internal`)

**Comment by PaulShore** [comment]
Thanks - the manual page and the "aptly push snapshot help" sections all mention -batch=false.  This doesn't work, but if I use -batch=true it works OK.

Can I suggest two things
1) The aptly command captures the /dev/tty GPG error code and suggests using "-batch=true"  in an error or warning.  This could either check the status of /dev/tty in aptly before it calls gpg or capture the error from gpg.

2) The aptly manual page and help section are updated to mention "-batch=true" rather than -batch=false

I am going to close this as my problem is fixed.

Paul
