### ISSUE TITLE
Aply cannot handle deb packages using control.tar.xz

### ISSUE THREAD

**Issue by hosiet** [smira/aptly#655]
## Detailed Description

Ever since the release of dpkg 1.19.0, `dpkg-deb` enables `--uniform-compression` by default. This means `control.tar*` file will be compressed using `xz` by default (to be more precise, using the same compression method as `data.tar*` file). This claims `control.tar.xz` file inside `.deb` file instead of `control.tar.gz`.

Currently aptly does not seem to support handling `control.tar.xz` inside `.deb` file.

## Context

Using `.deb` packages built using `dpkg (>= 1.19.0)` will encounter this problem.

Currently it affects users of Debian Testing and Debian Unstable but we can expect more users affected by this bug due to downstream adaption of new dpkg.

## Possible Implementation
Do not assume hardcoded `control.tar.gz` inside `.deb` files. Instead, we should do an intelligent analysis about the compression method used for `control.tar.*` and `data.tar.*`.

## Your Environment
Debian Unstable, using dpkg 1.19.0.4.

**Comment by GLolol** [comment]
Confirming: this recently hit my builds too.

**Comment by guillemj** [comment]
Hmm, it seems I missed aptly when I was checking for other tools directly handling .deb packages for https://wiki.debian.org/Teams/Dpkg/DebSupport. Support for non-gzip compressed (or not compressed) control.tar is not recent (dpkg 1.17.6), so you might want to check the [deb(5)]( https://manpages.debian.org/unstable/deb.5) man page and that wiki page for any other features currently not supported, and while you are at it, fill the aptly stub entry I've just added there! Thanks. :)

**Comment by smira** [comment]
@guilhem thanks for the pointers, I'll improve compatibility and fill the Wiki page!

**Comment by smira** [comment]
Reopening to track wiki updates

**Comment by travisgriggs** [comment]
I just ran into this... is it fixed in the 1.1.1 version? Or do I need to pull the nightly version?

**Comment by babilen** [comment]
@travisgriggs It seems to be fixed in the nightly version, but still present in 1.1.1

**Comment by smira** [comment]
1.2.0 should have this fix (when it gets released)

**Comment by arno01** [comment]
Just in case if someone cannot yet upgrade aptly to ``1.2.0``, you can work this issue around by repacking the .deb so it gets ``{control,data}.tar`` gzipped, instead of xz'ed.

```
dpkg-deb -R package.deb tmp
rm package.deb
fakeroot dpkg-deb -Zgzip -b tmp package.deb
rm -rf tmp
```
