### ISSUE TITLE
Add SHA512 hashes

### ISSUE THREAD

**Issue by ryanolson** [smira/aptly#656]
https://github.com/smira/aptly/blob/2811ad02d5830cd31af7ae765a36765196095cb6/deb/remote.go#L394

Would it be possible to add SHA512 hashes?  I'm looking to mirror a repo that I don't control that only publishes SHA512 hashes in the InRelease file.

**Comment by smira** [comment]
@ryanolson should be relatively easy, I'll add that in!

**Comment by smira** [comment]
@ryanolson do you have sample of such repo? I would like to add system test

**Comment by flx42** [comment]
I do, that's my repo:
```
curl -L https://nvidia.github.io/libnvidia-container/gpgkey | sudo apt-key add -
aptly mirror create -keyring=/etc/apt/trusted.gpg libnvidia-container https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64 ./
aptly mirror update -keyring=/etc/apt/trusted.gpg libnvidia-container
```

**Comment by smira** [comment]
Fix is available in `aptly_1.1.1+45+g9c018ce`

**Comment by ryanolson** [comment]
Works great!
