### ISSUE TITLE
Unable to find control.tar.gz part in package composer

### ISSUE THREAD

**Issue by timwsuqld** [smira/aptly#669]
Attempting to add composer package (https://packages.ubuntu.com/bionic/composer) to our local repo. However, it errors with
```
[!] Unable to read file composer_1.5.2-1_all.deb: unable to find control.tar.gz part in package composer_1.5.2-1_all.deb
```

I am able to successfully extract both the control file (dpkg-deb -e) as well as the files manually. Is it really a broken package, or is aptly misreading something?

## Your Environment
```
$ aptly version
aptly version: 1.1.1

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by timwsuqld** [comment]
Just to add to this, `composer_1.5.1-1_all.deb` from artful works fine.

**Comment by smira** [comment]
@timwsuqld I believe it's #635 or #655 (fixed in nightly builds)

**Comment by timwsuqld** [comment]
Thanks. That explains why I was confused as well, I looked at the source code and could see it trying different control.tar.* options, but that's because I was looking at the master branch.
