### ISSUE TITLE
Update published Snapshot

### ISSUE THREAD

**Issue by starflighter** [smira/aptly#670]
Hi,
is it possible to update a published snapshot?

I created a snap from a mirror, then I published the snap. I want for example a consistent state for a month.
After the month I want (automatically) to (re)publish a new (or better updated) snapshot with the same name from the same mirror.

At the moment my solution is:
- aptly mirror update
- aptly publish drop
- aptly snapshot drop
- aptly snapshot create
- aptly publish snapshot

Is there something faster?

Thanks.
starflighter

**Comment by tfylling** [comment]
How about

**Comment by tfylling** [comment]
How about:
- aptly mirror update mirrorname
- aptly snapshot create newsnapshot from mirror mirrorname
- aptly publish switch publishpoint newsnapshot
- aptly snapshot drop currentsnapshot
- aptly snapshot rename newsnapshot currentsnapshot

This should certainly have a lot less downtime, even if it isn't exactly atomic.

**Comment by smira** [comment]
@tfylling thanks for awesome answer!
