### ISSUE TITLE
Publish snapshot and local repo in one repository

### ISSUE THREAD

**Issue by pohmelie** [smira/aptly#672]
I have snapshot from mirror and local repo. I want publish repository with two components for this setup. But it looks like there is no api/cli methods for this. What is the reason for this feature?
Solutions here are pretty simple (but annoying):
* don't use aptly mirror, and just create local repo from remote packages
* create separate public repository from mirror snapshot

**Comment by smira** [comment]
Mirror is moving target, so it can't be published.

Idea of aptly is to have reproducible results, so I would suggest to take snapshots of both mirror and local repo and publish 2 snapshots.

**Comment by pohmelie** [comment]
@smira 
Question is actually about why we can publish from multiple local repos, can publish from multiple snapshots, but can't publish mix of them?
