### ISSUE TITLE
Aptly doesn't create metadata files

### ISSUE THREAD

**Issue by rameshshihora** [smira/aptly#684]
776M	jessie
1.2G  	precise
1.8G	trusty
776M	vivid
776M	wheezy
776M	wily
1.7G	        xenial
776M	yakkety
776M	zesty

public/dists/jessie:
InRelease  main  Release  Release.gpg

public/dists/precise:
InRelease  main  Release  Release.gpg

public/dists/trusty:
<---------------------- It didn't created any files here where publish was successful ----->
public/dists/vivid:
InRelease  main  Release  Release.gpg

public/dists/wheezy:
InRelease  main  Release  Release.gpg

public/dists/wily:
InRelease  main  Release  Release.gpg

public/dists/xenial:
InRelease  main  Release  Release.gpg

public/dists/yakkety:
InRelease  main  Release  Release.gpg

public/dists/zesty:
InRelease  main  Release  Release.gpg

## Detailed Description
1. is there any size limits either per repo or per packages?
2. Any workaround?

## Context
1. I am getting rid of reprepro and wanted to use aptly but looks like its buggy.

**Comment by smira** [comment]
@rameshshihora could you please provide any additional context? it's hard to understand what happened.
