### ISSUE TITLE
Error 500 : error listing under prefix  in S3 with Swift basic Auth

### ISSUE THREAD

**Issue by plumcraft** [smira/aptly#687]
## Detailed Description
Hello,

I've been trying many methods but could not figure out the issue :
- error listing under prefix  in S3

I have an instance with swift configure with simple authentification and running aptly (version 0.9.7)

I can curl swift endpoint with basic curl
```
root@9308368a2a8e:/opt/aptly# curl -i -H "X-Auth-User: admin:admin" -H "X-Auth-Key: admin" http://172.18.0.1:8080/auth/v1.0/
HTTP/1.1 200 OK
X-Storage-Url: http://172.18.0.1:8080/v1/AUTH_admin
X-Auth-Token-Expires: 80176
X-Auth-Token: AUTH_tkacf2df102bd04117a3b4912a2082dbd2
Content-Type: text/html; charset=UTF-8
X-Storage-Token: AUTH_tkacf2df102bd04117a3b4912a2082dbd2
Content-Length: 0
X-Trans-Id: tx2d7fedf8e00c43a8993ab-005a304e21
Date: Tue, 12 Dec 2017 21:46:09 GMT
```

But with this aptly configuration 

S3PublishEndpoints": {
    "test": {
      "bucket": "aptlybucket/",
      "endpoint": "http://172.18.0.1:8080",
      "region": "aptlybucket",
      "awsAccessKeyID": "admin:admin",
      "awsSecretAccessKey": "admin",
      "acl": "none",
      "plusWorkaround": false,
      "disableMultiDel": true,
      "forceSigV2": true,
      "debug": true
    }

But when i try to push a snapshot to aptly, i got an error 500

- aptly publish snapshot xenial-main s3:test:

```
ERROR: unable to publish: unable to process packages: error caching paths under prefix: error listing under prefix  in S3: aptlybucket:aptlybucket/: InternalError: We encountered an internal error. Please try again.
	status code: 500, request id: txff8d9e008a51422eb7127-005a3051ec
```

I put a region because according to the documentation this field is mandatory but not used if an endpoint is set, not sure about it ?

It could be a ssl certificate issue, do you know if there is a flag to disable it ?

Note : I've tried with boto python library and i can read et write into "aptlybucket" bucket.

Thanks

**Comment by smira** [comment]
@plumcraft are you trying to use Swift in S3 mode? I'm confused here. 

You might want to try native aptly Swift support.

With `debug: true` you should have some additional info in the log on the failure anyway

**Comment by plumcraft** [comment]
@smira : I was confused too. It's now working with swift connector.
