### ISSUE TITLE
aptly unable to publish on debian 9.3 stretch (signing with gpg fails)

### ISSUE THREAD

**Issue by steinarb** [smira/aptly#689]
When I try to publish a repo I am never prompted for a passphrase, and gpg fails with a timeout:
```
sb@lorenzo:~$ aptly publish repo stable
Loading packages...
Generating metadata files and linking package files...
Finalizing metadata files...
Signing file 'Release' with gpg, please enter your passphrase when prompted:
gpg: signing failed: Timeout
gpg: signing failed: Timeout
ERROR: unable to publish: unable to detached sign file: exit status 2
sb@lorenzo:~$
```

When I try providing the passphrase in a file I am told 'gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect' and then gpg signing fails with a timeout (and aptly publishing fails):
```
sb@lorenzo:~$ aptly publish repo -passphrase-file=.gpg/passphrase stable
Loading packages...
Generating metadata files and linking package files...
Finalizing metadata files...
Signing file 'Release' with gpg, please enter your passphrase when prompted:
gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
gpg: signing failed: Timeout
gpg: signing failed: Timeout
ERROR: unable to publish: unable to detached sign file: exit status 2
sb@lorenzo:~$
```
 
gpg version, is gnupg 2.1.18-8~deb9u1

**Comment by smira** [comment]
aptly doesn't work well with gnupg 2.x, and this is known problem unfortunately. 

But your issue is related to `gpg` itself, I would guess it's timing out talking to `gpg-agent`.

You can try searching for that error message.

**Comment by steinarb** [comment]
I tried killing the running gpg-agent and setting GPG_TTY as outlined in [no password prompt, process keeps waiting](https://bbs.archlinux.org/viewtopic.php?id=227486), ie.
```
export GPG_TTY=$(tty)
```

But that didn't give me any prompt for passphrase either. I got the same error messages as above.

**Comment by steinarb** [comment]
My problem was that I was logged in to the server I was running "aptly publish" on, using [mosh](https://mosh.org) which has no X forwarding.  And gpg-agent wanted to open a GUI dialog to ask me for the passphrase.

When I used a terminal window on the MATE desktop of the computer, publishing worked fine:
```
sb@lorenzo:~$ aptly publish repo stable
Loading packages...
Generating metadata files and linking package files...
Finalizing metadata files...
Signing file 'Release' with gpg, please enter your passphrase when prompted:
Clearsigning file 'Release' with gpg, please enter your passphrase when prompted:

Local repo stable has been successfully published.
Please setup your webserver to serve directory '/home/sb/.aptly/public' with autoindexing.
Now you can add following line to apt sources:
  deb http://your-server/ stable main
Don't forget to add your GPG key to apt with apt-key.

You can also use `aptly serve` to publish your repositories over HTTP quickly.
sb@lorenzo:~$
```

So, as you say, nothing directly to do with aptly (except for it being somewhat annoying that I can't do "aptly publish" from a remote login...)

Thanks for the help!

**Comment by jringoot** [comment]
@smira 

> aptly doesn't work well with gnupg 2.x, and this is known problem unfortunately.

But what do you suggest instead?

**Comment by apachelogger** [comment]
gpg1

**Comment by jringoot** [comment]
In Debian 9, gpg1 it's binary is installed as /usr/bin/gpg1 and gpg2 as /usr/bin/gpg 
After install of gpg1 it is still the same error, most likely because it uses still gpg2
Moving gpg binary and replacing it by gpg1 binary gives other errors, most likely because it depends on other binaries or libraries from gpg1 
Reading passphrase from file descriptor 3    
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
ERROR: unable to publish: unable to detached sign file: exit status 2


removing the password from the gpg key allows automated snapshot publishing:
gpg --edit-key <<gpgkeyname>>
(passwd on the new prompt)

**Comment by smira** [comment]
@jringoot created #699 to track that, thanks

**Comment by jringoot** [comment]
Thank you @smira , you created a very useful package for staging repositories, the snapshot switch is great to move a snapshot that was used as in testing to production.
