### ISSUE TITLE
Permission denied on add file from directory to repository

### ISSUE THREAD

**Issue by pohmelie** [smira/aptly#690]
Env:
* aptly 1.1.1 (api started with `-no-lock=true`)
* ubuntu 16.04

I have small code in python, which use `requests` to call some aptly api. Code make requests like this:
``` python
requests.post("/api/files/tmp", files=files)
requests.post("/api/repos/my_repo/file/tmp", ...)
```
And sometimes (10% of cases) I have response like:
```
{
    'FailedFiles': ['/srv/repos/aptly/upload/tmp/package.deb'], 
    'Report': {
        'Warnings': ['Unable to import file /srv/repos/aptly/upload/tmp/package.deb into pool: open /srv/repos/aptly/pool/1f/4a/2723b1b97b64b4c6ea6cb81425db_package.deb: permission denied'], 
        'Removed': [], 
        'Added': [...]
    }
}
```
Here is real log from aptly api:
```
[GIN] 2017/12/29 - 22:35:36 | 200 | 107.371083ms | 10.10.121.153:50574 |   GET     /api/repos/orion-astra15-kt/packages
[GIN] 2017/12/29 - 22:36:31 | 200 | 50.448255712s | 10.10.121.153:50576 |   POST    /api/files/6a32a50c14cc419ebbe55cf4996053f3
[GIN] 2017/12/29 - 22:36:32 | 200 |  24.207958ms | 10.10.121.153:50578 |   GET     /api/files/6a32a50c14cc419ebbe55cf4996053f3
[GIN] 2017/12/29 - 22:36:55 | 200 | 23.839689833s | 10.10.121.153:50580 |   POST    /api/repos/orion-astra15-kt/file/6a32a50c14cc419ebbe55cf4996053f3
```
1. Get list of existing packages.
2. Upload some packages.
3. Verify uploaded files.
4. Add uploaded files to repo.

**Comment by smira** [comment]
The error tells that aptly can't open destination file to import file to, so I assume you have run aptly under different user, and some parts of the `pool/` are owned by user other than the one is used to run aptly

**Comment by pohmelie** [comment]
@smira 
Will check this soon, thanks for good idea :+1:

**Comment by pohmelie** [comment]
You were right. I have some directories/files in pool, which have wrong user/group. So, am I right in understanding, that in pool files stored in tree structure by some hash/uuid/etc and the problem is that when I'm trying to add some file, which should be stored in directory in pool, which have wrong permission I see this error?

**Comment by pohmelie** [comment]
Seems like this was the problem. Will reopen if not.
