### ISSUE TITLE
reverse proxy on repo get 502 bad gateway on apt update

### ISSUE THREAD

**Issue by Ludea** [smira/aptly#695]
## Detailed Description

I create local repository , add debian package (architecture = all, distribution= stretch, signed)
I create snapshot from this repo, and publish it.
The snapshot is published. So I point my reverse proxy into /aptly/public like this :
```server {
        listen 443;
        server_name myhostname;
        root /aptly/.aptly/public;
        location / {
            autoindex on;
        }
    }
```
But, when i add https://myhostname stretch main into apt list, and do apt update, I have 502 bad gateway.
In nginx logs,  have this:  `10#10: *8651 no live upstreams while connecting to upstream, client: 81.48.153.19, server: myhostname, request: "GET /dists/stretch/InRelease HTTP/1.1", upstream: "http://myhostname/dists/stretch/InRelease", host: "myhostname" `

## Context

I would like use a reverse prox for publish my package.
I have docker with multiple container with reverse proxy to serve all my dockerized sites

## Your Environment

The docker nginx I use is  https://github.com/jwilder/nginx-proxy with let's encrypt support.

**Comment by Ludea** [comment]
After some work, it seems it is a gnupg issue.
The error message is
`gnutls_handshake() failed: The TLS connection was non-properly terminated.`
I import my public key, add with apt-key, all seems good.
I don't understand what is wrong :s

**Comment by Ludea** [comment]
After some work, it seems it is a gnupg issue.
The error message is
`gnutls_handshake() failed: The TLS connection was non-properly terminated.`
I import my public key, add with apt-key, all seems good.
I don't understand what is wrong :s

**Comment by smira** [comment]
I think what you see is error accessing https:// which has nothing to do with aptly nor apt-key. So apt can't download over https:// for some reason which you can try reproducing with curl/wget.
