### ISSUE TITLE
-no-lock option for aptly serve is not recognised

### ISSUE THREAD

**Issue by jringoot** [smira/aptly#700]
In the manpages there is an option _"-no-lock"_ described:
https://www.aptly.info/doc/aptly/serve/
But it is not recognised, I get this error:
```
flag provided but not defined: -no-lock
Usage: aptly serve
```

## Context

This could enable me to switch the published snapshot without restarting the server

## Your Environment

debian 9.3

**Comment by smira** [comment]
Yep, thanks, documentation bug. `aptly serve` doesn't lock the database at all actually, this was supposed to be docs for `aptly api serve`
