### ISSUE TITLE
Patch: Add zsh completion

### ISSUE THREAD

**Issue by steinymity** [smira/aptly#701]
## Detailed Description
I am using the zsh where the bash completion script does not work unfortunately (not even with with bashcompinit). That's why I have developed a zsh completion function including extensive help (most of the manpage is include).

## Context
Will make the life of zsh users a lot easier.

## Possible Implementation
See [my git repo](https://github.com/steinymity/aptly-zsh).

## Your Environment
Debian stable, aptly version 0.9.7-1+b1 (though, completion was developed with version 1.2.0 from Debian testing in mind).

**Comment by smira** [comment]
It would be really great to see that part of aptly distribution! Would you mind submitting a PR?

If you want to keep it in your repo, I could have provided a link to it from aptly README/docs.

**Comment by steinymity** [comment]
Yeah, I guess it's best to integrate it in the aptly distribution to keep it in sync with further development. Should I integrate it into the bash_completion.d (and possible rename that directory), or create a new one instead?
