### ISSUE TITLE
publish snapshot prompts for password

### ISSUE THREAD

**Issue by thyzoul** [smira/aptly#709]
## Detailed Description
when executing :   
```
aptly publish snapshot -passphrase=blablabla
```
"-passphrase" seems to be ignored and gpg prompts for the signing key password

## Context
Should be able to be used without a user imput, like in a script

## Possible Implementation
maybe use  "--batch" in the call on gpg

## Your Environment
launched in a docker container based on debian stretch

**Comment by SerhiyMakarenko** [comment]
I have the same issue running any command -passphrase flag. Aptly version: 1.2.0.

**Comment by apachelogger** [comment]
publish has the flag `  -batch: run GPG with detached tty`

What you are experiencing is #657 maybe?

I certainly fail to reproduce the behavior with gpg1

**Comment by thyzoul** [comment]
Hi @apachelogger , I suppose you are right. I'm currently without access to the machine running APTLY but I know its running on Debian Stable. But as said by @Mischelebuya in issue #657, Debian Stable packages for GPG are in version 2.1+ ... I hope APTLY guys will upgrade it to support debian stable.
Thanks, I hereby close the thread and will post on #657. Cheers
