### ISSUE TITLE
support of changes files

### ISSUE THREAD

**Issue by deknos** [smira/aptly#71]
Hi,
we would like to replace our repository-tools with aptly. 
It would be nice, if aptly supports changes-files.

We build our own Debian-Packages and we include them into dak and reprepro-repositories. Since changes-files include a list of source- and deb-Packages, it is easier to import own packages with that file, since automatically both types are included into our repository.

**Comment by smira** [comment]
@oCCtet thanks for the great case!

**Comment by kived** [comment]
I wrote my own script to process `.changes` files and import packages into aptly. My `.changes` files aren't signed, so the script doesn't handle that part, but it compares file sizes and checksums before importing. It works for me using inoticoming to trigger it, YMMV.

https://gist.github.com/kived/68ad4f035a80fb2488d3

**Comment by smira** [comment]
Work on this feature has been sponsored by **sipgate GmbH** (http://www.sipgate.de/).

First version is available as nightly build `aptly_0.9.6~dev+28+g67a31d5`.

**Comment by smira** [comment]
Done in `master`, available as nightly build `aptly_0.9.6~dev+53+g3c20b54`. 

Documentation: http://beta.aptly.info/doc/aptly/repo/include/

**Comment by npf** [comment]
Hi, issue #278 reports a issue when including a package to a backports distribution.
