### ISSUE TITLE
Adding new packages to existing published repo using Rest API

### ISSUE THREAD

**Issue by congaframe** [smira/aptly#714]
Hi, 
What is the best way to add new package to existing published repo using Rest API?
I used the following method in CLI: 
```
Create new local repo
Adding new  packages to new local repo
Creating new snapshot from new local repo

Filter and compare new snapshot with existing snapshot
merge them into new snapshot and publish this new snapshot
```

**Comment by apachelogger** [comment]
It'd be really lovely if you used the mailing list to ask questions. https://www.aptly.info/support/

**Comment by congaframe** [comment]
thanks, apachelogger
