### ISSUE TITLE
apt repo public key expiration

### ISSUE THREAD

**Issue by jsbs** [smira/aptly#720]
## Detailed Description
The public key used to verify the http://repo.aptly.info/ squeeze main repo expired today `03-15-2018`
````
/etc/apt/trusted.gpg.d/aptly.gpg
--------------------------------
pub   2048R/9C7DE460 2016-03-15 [expired: 2018-03-15]
uid                  Andrey Smirnov <me@smira.ru>
````
## Context
Need to be able to apt-get install aptly from http://repo.aptly.info/ squeeze main

## Possible Implementation
Update key

## Your Environment
Debian 8

**Comment by smira** [comment]
Please see #717, this is fixed already. Sorry for the inconvenience
