### ISSUE TITLE
Can't find local repo, snapshot or published repo via Rest API

### ISSUE THREAD

**Issue by congaframe** [smira/aptly#727]
We created local repo, snapshots and published a repo. It's been working fine for few weeks ( with Rest API), but today we cant list them on Rest API. It only returns blank result. 

I have logged into the server and run `aptly repo list, snapshot list` command and I can see they are all there. It's just that when you query those information via Rest API, they return blank value: no local repo, no snapshots, no publish repo 
Please note the server was restarted a day before we saw this issue. It seems like a data loss for me. 
Has anyone experienced this issue before ? 

Thanks

**Comment by congaframe** [comment]
ok i think i have fixed it. 
for some reasons, it loads up different config in `/root/ dir. perhaps we created new config there but didn't restart aptly so it didn't pick that up until it got restarted

**Comment by smira** [comment]
aptly creates default config if no config is available (and it defaults to ~/.aptly.conf), so what you described makes sense if you run it as `root`
